"use client";
import {lazy,Suspense,useCallback,useEffect,useRef,useState} from 'react';
import {BookOpen,Check,CheckCircle2,ChevronRight,Download,Expand,GraduationCap,Info,LoaderCircle,Play,Plus,RotateCcw,Search,Square,Trash2,Upload,X,Workflow,Plug,ShieldCheck,ArrowRight} from 'lucide-react';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {Textarea} from './ui/textarea';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from './ui/select';
import {Tabs,TabsList,TabsTrigger} from './ui/tabs';
import {Switch} from './ui/switch';
import {AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle} from './ui/alert-dialog';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from './ui/dialog';
import {nodeIcons} from './agent-workshop-icons';
import {assessWorkshop,executeWorkflow,exampleGraph,graphProblems,graphSchema,graphSignature,newNode,nodeCatalog,nodeKinds,scenarios,systems,type CheckResult,type FlowData,type NodeConfig,type NodeKind,type RunEvent,type RunResult,type ScenarioId,type TraceStep,type WorkshopGraph} from '@/lib/agent-workshop';
const Canvas=lazy(()=>import('./agent-workshop-canvas'));
const ProcurementLab=lazy(()=>import('./procurement-agent-lab'));
const guides=[
 {title:'让主 Agent 分配任务',text:'主 Agent 负责调度，订单、生产、运输三个子 Agent 各自查询事实。试着切换串行与并行，再观察日志里的执行波次。',target:'dispatch'},
 {title:'沿着 MCP 找到系统数据',text:'选一个子 Agent，展开连接设置，看看发现服务、列出工具、调用工具的过程。关闭 TMS 连接再试跑，观察未知信息如何传递。',target:'tms'},
 {title:'把经验装进 Skill',text:'履约检查 Skill 会核对库存、计算生产与运输时间。把缓冲天数从 0 改为 1，预计到货时间也会改变。',target:'skill'},
 {title:'给异常留一个人工出口',text:'条件节点有两个出口。选「交期异常」运行，流程会停在人工复核；核对证据后再确认建议或退回。',target:'condition'},
 {title:'轮到你接手',text:'在节点库中添加知识检索、MCP 连接或插件，自己连线。准备好后进入综合挑战，修复一条有问题的流程。',target:'merge'},
];
const glossary=[
 ['调度 / 子 Agent','主 Agent 分解任务，子 Agent 完成有边界的子任务，再把结果交回。此处用确定性规则模拟分工，不调用真实模型。'],
 ['Skills','把可复用的方法写进 SKILL.md，也可带参考资料与脚本。此处把履约检查流程封装为技能，参数会参与计算。'],
 ['插件','一种扩展的包装与分发方式，可以提供工具、连接器或报告能力。这里可启停系统连接插件，也可添加报告插件节点。'],
 ['MCP','连接 AI 应用与外部工具、数据的协议。这里模拟服务发现、工具列表和调用；真实接入还需要服务端、认证与系统接口。'],
];
function Choice({label,value,onChange,options,disabled=false}:{label:string;value:string;onChange:(value:string)=>void;options:readonly (readonly[string,string])[];disabled?:boolean}){return <label className="aw-field"><span>{label}</span><Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(([value,label])=><SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></label>}
function EvidenceView({data}:{data:FlowData}){return <div className="aw-evidence">{systems.map(system=>{const evidence=data.evidence[system];return <div key={system}><strong>{system}</strong>{evidence?<><span>{Object.entries(evidence.facts).map(([key,value])=>`${({quantity:'数量',stock:'现货',dueDays:'交期（天）',productionDays:'生产（天）',remaining:'待产',transitDays:'运输（天）'} as Record<string,string>)[key]||key} ${value}`).join(' · ')}</span><small>{evidence.reference}</small></>:<span>尚无证据 · 不能推断为正常</span>}</div>})}</div>}
function NodeInspector({graph,selected,onPatch,onRemove,onConnect,onRemoveEdge,disabled}:{graph:WorkshopGraph;selected:string;onPatch:(patch:Partial<NodeConfig>)=>void;onRemove:()=>void;onConnect:(target:string,port:'out'|'normal'|'review')=>void;onRemoveEdge:(id:string)=>void;disabled:boolean}){
 const node=graph.nodes.find(n=>n.id===selected),[target,setTarget]=useState(''),[port,setPort]=useState<'out'|'normal'|'review'>('out');
 useEffect(()=>{setTarget('');setPort(node?.data.kind==='condition'?'normal':'out')},[selected,node?.data.kind]);
 if(!node)return <div className="aw-inspector-empty"><Info/><p>选中一个节点，调整它的参数和连线。</p></div>;
 const c=node.data,Icon=nodeIcons[c.kind];return <>
  <div className="aw-inspector-heading"><span><Icon size={18}/>{nodeCatalog[c.kind].label}</span><Button variant="ghost" size="icon" aria-label="删除选中节点" disabled={disabled} onClick={onRemove}><Trash2 size={16}/></Button></div>
  <p className="aw-help">{nodeCatalog[c.kind].description}</p>
  <fieldset disabled={disabled} className="aw-fields">
   <label className="aw-field"><span>节点名称</span><Input value={c.label} maxLength={60} onChange={e=>onPatch({label:e.target.value})}/></label>
   {c.kind==='supervisor'&&<><Choice label="调度方式" value={c.mode} onChange={mode=>onPatch({mode:mode as NodeConfig['mode']})} options={[["parallel","并行分工"],["sequential","逐个执行"]]}/>{c.mode==='parallel'&&<Choice label="最大并发" value={String(c.parallel)} onChange={v=>onPatch({parallel:Number(v)})} options={[["1","1 个分支"],["2","2 个分支"],["3","3 个分支"]]}/>}<div className="aw-note">并行适合相互独立的查询；后续汇总仍要等待所有分支返回。</div></>}
   {(c.kind==='agent'||c.kind==='mcp')&&<>
    {c.kind==='agent'&&<label className="aw-field"><span>分工说明</span><Textarea rows={3} maxLength={240} value={c.role} onChange={e=>onPatch({role:e.target.value})}/><small>说明会记录在执行日志；实际工具由下方选择决定。</small></label>}
    <Choice label="连接系统" value={c.system} onChange={system=>onPatch({system:system as NodeConfig['system']})} options={[["ERP","ERP · 订单与库存"],["MES","MES · 生产进度"],["TMS","TMS · 运输计划"]]}/>
    <div className="aw-connector"><strong><Plug size={16}/>MCP 模拟连接</strong><label>启用连接插件<Switch checked={c.plugin} onCheckedChange={plugin=>onPatch({plugin})} aria-label="启用连接插件"/></label><label>服务在线<Switch checked={c.connected} onCheckedChange={connected=>onPatch({connected})} aria-label="服务在线"/></label><Choice label="工具权限" value={c.permission} onChange={permission=>onPatch({permission:permission as NodeConfig['permission']})} options={[["read","允许只读查询"],["none","未授权"]]}/><Choice label="连接失败后" value={c.fallback} onChange={fallback=>onPatch({fallback:fallback as NodeConfig['fallback']})} options={[["handoff","保留未知，继续到复核"],["stop","停止本次运行"]]}/><small>工具：{c.system==='ERP'?'get_order':c.system==='MES'?'get_production':'get_shipment'}(order_id)</small></div>
   </>}
   {c.kind==='skill'&&<><Choice label="加载技能" value={c.skill} onChange={skill=>onPatch({skill:skill as NodeConfig['skill']})} options={[["delivery-check","履约检查"],["evidence-check","证据完整性检查"]]}/>{c.skill==='delivery-check'&&<label className="aw-field"><span>额外缓冲天数 · {c.buffer} 天</span><Input type="number" min={0} max={5} step={1} value={c.buffer} onChange={e=>onPatch({buffer:Math.max(0,Math.min(5,Number(e.target.value)||0))})}/></label>}<details className="aw-skill-file"><summary>查看 SKILL.md 示例</summary><pre>{c.skill==='delivery-check'?'name: delivery-check\ndescription: 检查订单履约风险\n\n1. 核对 ERP / MES / TMS 来源\n2. 现货不足时计入生产天数\n3. 加上运输与缓冲时间\n4. 与客户交期比较\n5. 缺失数据交给人工核实':'name: evidence-check\ndescription: 检查证据完整性\n\n1. 确认三个系统均有来源\n2. 列出缺失来源\n3. 不推测未知字段'}</pre></details></>}
   {c.kind==='condition'&&<><label className="aw-field"><span>延误超过多少天进入复核？</span><Input type="number" min={0} max={5} value={c.threshold} onChange={e=>onPatch({threshold:Math.max(0,Math.min(5,Number(e.target.value)||0))})}/></label><div className="aw-note">来源缺失或尚未测算时始终进入复核。0 表示任何延误都需复核。</div></>}
   {c.kind==='knowledge'&&<Choice label="检索规则集" value={c.policy} onChange={policy=>onPatch({policy:policy as NodeConfig['policy']})} options={[["standard","标准履约规则"],["conservative","保守规则 · 额外缓冲 1 天"]]}/>}
   {c.kind==='plugin'&&<label className="aw-toggle">启用履约报告插件<Switch checked={c.plugin} onCheckedChange={plugin=>onPatch({plugin})} aria-label="启用履约报告插件"/></label>}
   {c.kind==='output'&&<Choice label="交付格式" value={c.format} onChange={format=>onPatch({format:format as NodeConfig['format']})} options={[["brief","可读简报 + 证据"],["json","结构化 JSON"]]}/>}
   {c.kind==='start'&&<div className="aw-note">输入来自画布上方的测试订单。更换样例后需要重新运行。</div>}
   {c.kind==='approval'&&<div className="aw-note">运行到此处会暂停。你的确认只会继续模拟，不会修改真实业务单据。</div>}
   <div className="aw-connections"><h4>节点连线</h4>{graph.edges.filter(e=>e.source===selected||e.target===selected).map(e=><div key={e.id}><span>{e.target===selected?'← ':'→ '}{graph.nodes.find(n=>n.id===(e.target===selected?e.source:e.target))?.data.label}<small>{e.sourceHandle==='normal'?'常规':e.sourceHandle==='review'?'复核':''}</small></span><button aria-label={`删除 ${e.source} 到 ${e.target} 连线`} onClick={()=>onRemoveEdge(e.id)} type="button"><X size={14}/></button></div>)}
   {c.kind!=='output'&&<>{c.kind==='condition'&&<Choice label="选择出口" value={port==='out'?'normal':port} onChange={v=>setPort(v as 'normal'|'review')} options={[["normal","常规出口"],["review","复核出口"]]}/>}<Choice label="连接下一个节点" value={target} onChange={setTarget} options={graph.nodes.filter(n=>n.id!==selected&&n.data.kind!=='start').map(n=>[n.id,n.data.label])}/><Button type="button" size="sm" variant="outline" disabled={!target} onClick={()=>{onConnect(target,c.kind==='condition'?(port==='out'?'normal':port):'out');setTarget('')}}><Plus size={14}/>添加连线</Button></>}
   </div>
  </fieldset>
 </>
}
export default function AgentLab(){
 const [tab,setTab]=useState('canvas'),[graph,setGraph]=useState<WorkshopGraph>(()=>exampleGraph()),[selected,setSelected]=useState('dispatch'),[focus,setFocus]=useState({id:'',revision:0});
 const [query,setQuery]=useState(''),[scenario,setScenario]=useState<ScenarioId>('normal'),[guide,setGuide]=useState(0),[showGuide,setShowGuide]=useState(true),[wide,setWide]=useState(false),[showPalette,setShowPalette]=useState(true),[showInspector,setShowInspector]=useState(true);
 const [steps,setSteps]=useState<TraceStep[]>([]),[states,setStates]=useState<Record<string,TraceStep['state']>>({}),[result,setResult]=useState<RunResult|null>(null),[running,setRunning]=useState(false),[waiting,setWaiting]=useState<FlowData|null>(null),[errors,setErrors]=useState<string[]>([]);
 const [checks,setChecks]=useState<CheckResult[]>([]),[checkSignature,setCheckSignature]=useState(''),[quizMcp,setQuizMcp]=useState(''),[quizSkill,setQuizSkill]=useState('');
 const [completedAt,setCompletedAt]=useState<number|null>(null),[saveState,setSaveState]=useState<'idle'|'saving'|'saved'|'error'>('idle'),[saveError,setSaveError]=useState('');
 const [reset,setReset]=useState<'example'|'challenge'|null>(null),[concepts,setConcepts]=useState(false),[importError,setImportError]=useState('');
 const generator=useRef<Generator<RunEvent,RunResult,boolean|undefined>|null>(null),runToken=useRef(0),fileInput=useRef<HTMLInputElement>(null),consoleRef=useRef<HTMLDivElement>(null),saveToken=useRef(0);
 const [progressError,setProgressError]=useState('');
 const loadProgress=useCallback(async(signal?:AbortSignal)=>{setProgressError('');try{const response=await fetch('/api/workshop-progress',{signal});if(!response.ok)throw new Error(response.status===401?'登录后可读取和保存学习记录。':'学习记录暂未加载，当前练习仍可继续。');const data=await response.json() as {completedAt?:number};if(typeof data.completedAt==='number')setCompletedAt(data.completedAt)}catch(error){if(!signal?.aborted)setProgressError(error instanceof Error?error.message:'学习记录暂未加载。')}},[]);
 useEffect(()=>{const abort=new AbortController();void loadProgress(abort.signal);return()=>abort.abort()},[loadProgress]);
 useEffect(()=>()=>{runToken.current++;saveToken.current++;generator.current?.return(undefined as never)},[]);
 useEffect(()=>{if(!wide)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')setWide(false)};window.addEventListener('keydown',escape);return()=>{document.body.style.overflow=previous;window.removeEventListener('keydown',escape)}},[wide]);
 const stop=useCallback(()=>{runToken.current++;generator.current?.return(undefined as never);generator.current=null;setRunning(false);setWaiting(null);setStates(old=>Object.fromEntries(Object.entries(old).map(([id,state])=>[id,state==='running'||state==='waiting'?'warning':state])))},[]);
 function change(next:WorkshopGraph,semantic=true){setGraph(next);if(semantic){stop();setSteps([]);setStates({});setResult(null);setErrors([]);setChecks([]);setCheckSignature('');saveToken.current++;if(saveState==='saving')setSaveState('idle')}}
 function select(id:string,pan=false){setSelected(id);setShowInspector(true);if(pan)setFocus(old=>({id,revision:old.revision+1}))}
 async function pump(token:number,decision?:boolean){const current=generator.current;if(!current)return;let next=current.next(decision);while(!next.done&&token===runToken.current){const event=next.value;if(event.type==='wave'){setStates(old=>({...old,...Object.fromEntries(event.ids.map(id=>[id,'running' as const]))}));await new Promise(resolve=>setTimeout(resolve,360));if(token!==runToken.current)return}else{const step=event.step;setSteps(old=>[...old.filter(s=>s.nodeId!==step.nodeId),step]);setStates(old=>({...old,[step.nodeId]:step.state}));if(step.state==='waiting'){setWaiting(step.output as FlowData);select(step.nodeId);consoleRef.current?.scrollIntoView({behavior:'smooth',block:'nearest'});return}}next=current.next()}
  if(token===runToken.current&&next.done){setRunning(false);setWaiting(null);setResult(next.value);setErrors(next.value.errors);setStates(old=>Object.fromEntries(Object.entries(old).map(([id,state])=>[id,state==='running'?'skipped':state])));generator.current=null}
 }
 function run(nextScenario=scenario){stop();setScenario(nextScenario);const problems=graphProblems(graph);setErrors(problems);setStates({});setSteps([]);setResult(null);if(problems.length)return;const token=++runToken.current;generator.current=executeWorkflow(graph,nextScenario);setRunning(true);void pump(token)}
 function add(kind:NodeKind){if(graph.nodes.length>=30){setErrors(['最多添加 30 个节点。']);return}const id=kind+'-'+crypto.randomUUID().slice(0,8),anchor=graph.nodes.find(n=>n.id===selected),node=newNode(kind,id,(anchor?.position.x??0)+260,(anchor?.position.y??0)+170);change({...graph,nodes:[...graph.nodes,node]});select(id,true)}
 function patch(patch:Partial<NodeConfig>){change({...graph,nodes:graph.nodes.map(n=>n.id===selected?{...n,data:{...n.data,...patch}}:n)})}
 function connect(target:string,sourceHandle:'out'|'normal'|'review'){if(graph.edges.some(e=>e.source===selected&&e.target===target&&e.sourceHandle===sourceHandle))return;change({...graph,edges:[...graph.edges,{id:'edge-'+crypto.randomUUID(),source:selected,target,sourceHandle}]})}
 function loadTemplate(type:'example'|'challenge'){change(exampleGraph(type==='challenge'));setScenario('normal');setSelected('dispatch');setQuizMcp('');setQuizSkill('');setTab(type==='challenge'?'challenge':'canvas');setFocus(old=>({id:'dispatch',revision:old.revision+1}));setReset(null)}
 function exportGraph(){const blob=new Blob([JSON.stringify({format:'ai-practice-agent-workshop',...graph},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='智能体工坊-工作流.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 async function importGraph(file?:File){if(!file)return;setImportError('');if(file.size>100000){setImportError('流程文件不能超过 100 KB。');return}try{const parsed=graphSchema.parse(JSON.parse(await file.text()));change(parsed);select(parsed.nodes[0].id,true)}catch{setImportError('文件格式不正确，请选择从此工坊导出的 JSON。')}if(fileInput.current)fileInput.current.value=''}
 function verify(){stop();const assessment=assessWorkshop(graph);setChecks(assessment);setCheckSignature(graphSignature(graph));setErrors([])}
 const allPassed=checks.length===4&&checks.every(c=>c.passed)&&checkSignature===graphSignature(graph);
 async function finish(){const token=++saveToken.current;setSaveState('saving');setSaveError('');try{const response=await fetch('/api/workshop-progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({graph,quiz:{mcp:quizMcp,skill:quizSkill}})});const data=await response.json() as {completedAt:number;error?:string};if(token!==saveToken.current)return;if(!response.ok)throw new Error(data.error||'保存未成功，请重试。');setCompletedAt(data.completedAt);setSaveState('saved');window.dispatchEvent(new CustomEvent('workshop-completed',{detail:data.completedAt}))}catch(error){if(token===saveToken.current){setSaveError(error instanceof Error?error.message:'暂时无法保存，请重试。');setSaveState('error')}}}
 const visibleKinds=nodeKinds.filter(kind=>`${nodeCatalog[kind].label} ${nodeCatalog[kind].description} ${kind}`.toLowerCase().includes(query.toLowerCase()));
 return <section className={`agent-workshop${wide?' is-wide':''}`} id="agent-builder">
  <header className="aw-heading"><div><span className="aw-eyebrow">AGENT WORKSHOP · 互动练习</span><h1>智能体工坊 {completedAt&&<span className="aw-completed"><CheckCircle2 size={15}/>已学完</span>}</h1><p>从一个任务，到一组能协作的智能体。</p></div><div><Button variant="outline" size="sm" onClick={()=>setConcepts(true)}><BookOpen size={15}/>概念速查</Button><Button variant="outline" size="sm" onClick={()=>setWide(v=>!v)} aria-pressed={wide}><Expand size={15}/>{wide?'退出专注':'专注编排'}</Button></div></header>
  {progressError&&<div className="aw-progress-notice" role="status"><span>{progressError}</span><button onClick={()=>void loadProgress()}>重试</button></div>}
  <div className="aw-top-tabs"><Tabs value={tab} onValueChange={v=>{stop();setTab(v)}}><TabsList aria-label="智能体工坊模式"><TabsTrigger value="canvas"><Workflow size={15}/>协同编排</TabsTrigger><TabsTrigger value="challenge"><GraduationCap size={16}/>综合挑战</TabsTrigger><TabsTrigger value="basics">采购审单基础</TabsTrigger></TabsList></Tabs><span className="aw-simulation">教学模拟 · 不连接真实系统</span></div>
  {tab==='basics'?<Suspense fallback={<p>正在打开采购审单练习…</p>}><ProcurementLab/></Suspense>:<>
   {tab==='canvas'&&<div className="aw-guide"><button className="aw-guide-toggle" onClick={()=>setShowGuide(v=>!v)} aria-expanded={showGuide}><BookOpen size={17}/><strong>跟着搭一次</strong><span>{guide+1} / {guides.length}</span><ChevronRight size={16} className={showGuide?'is-open':''}/></button>{showGuide&&<div className="aw-guide-body"><nav aria-label="搭建导览">{guides.map((step,i)=><button key={step.title} className={i===guide?'is-active':''} aria-current={i===guide?'step':undefined} onClick={()=>{setGuide(i);select(step.target,true)}}>{String(i+1).padStart(2,'0')}<span>{['任务分工','系统连接','复用技能','人工复核','综合实践'][i]}</span></button>)}</nav><div><h2>{guides[guide].title}</h2><p>{guides[guide].text}</p><div className="aw-guide-actions"><Button size="sm" variant="outline" onClick={()=>select(guides[guide].target,true)}>定位相关节点</Button><Button size="sm" variant="outline" onClick={()=>run(guide===3?'delay':'normal')} disabled={running}><Play size={14}/>试跑{guide===3?'异常':'正常'}订单</Button><Button size="sm" onClick={()=>{if(guide<4){setGuide(guide+1);select(guides[guide+1].target,true)}else setTab('challenge')}}>{guide<4?'下一步':'进入综合挑战'}<ArrowRight size={14}/></Button></div></div></div>}</div>}
   {tab==='challenge'&&<div className="aw-challenge"><div><span className="aw-eyebrow">综合任务 · 订单履约协调员</span><h2>让三种订单，都走对分支。</h2><p>连接 ERP、MES、TMS，分派三个子 Agent，复用履约检查 Skill。正常订单直接交付；延误与来源缺失必须交给人工。</p><Button size="sm" variant="outline" onClick={()=>setReset('challenge')} disabled={running}>载入待修复流程</Button><small>两个线索：运输连接关闭了，延误阈值过于宽松。预计耗时 8–12 分钟。</small></div><div className="aw-case-list">{Object.entries(scenarios).map(([id,sample])=><button key={id} onClick={()=>run(id as ScenarioId)} disabled={running}><span>{id==='normal'?'01':id==='delay'?'02':'03'}</span><div><strong>{sample.label}</strong><small>{sample.description}</small></div><Play size={15}/></button>)}</div></div>}
   <div className="aw-workbench">
    <div className="aw-toolbar"><div><Button variant="outline" size="sm" onClick={()=>setShowPalette(v=>!v)} aria-pressed={showPalette}><Plus size={15}/>节点库</Button><Choice label="测试订单" value={scenario} onChange={v=>{stop();setScenario(v as ScenarioId);setSteps([]);setStates({});setResult(null)}} options={Object.entries(scenarios).map(([id,s])=>[id,s.label])} disabled={running}/></div><div><Button variant="ghost" size="sm" onClick={()=>setReset('example')} disabled={running} title="恢复示例"><RotateCcw size={15}/><span>示例</span></Button><Button variant="ghost" size="sm" onClick={exportGraph}><Download size={15}/><span>导出</span></Button><Button variant="ghost" size="sm" onClick={()=>fileInput.current?.click()} disabled={running}><Upload size={15}/><span>导入</span></Button><Button variant="outline" size="sm" onClick={()=>setShowInspector(v=>!v)} aria-pressed={showInspector}>参数</Button>{running?<Button size="sm" variant="outline" onClick={stop}><Square size={14}/>停止</Button>:<Button size="sm" onClick={()=>run()}><Play size={15}/>运行</Button>}</div><input ref={fileInput} type="file" accept=".json,application/json" hidden onChange={e=>void importGraph(e.target.files?.[0])}/></div>
    {importError&&<p className="aw-error" role="alert">{importError}</p>}
    <div className={`aw-editor${showPalette?' has-palette':''}${showInspector?' has-inspector':''}`}>
     {showPalette&&<aside className="aw-palette" aria-label="节点库"><div className="aw-palette-search"><Search size={14}/><Input aria-label="搜索节点" placeholder="搜索节点…" value={query} onChange={e=>setQuery(e.target.value)}/></div>{['基础','智能体','逻辑','工具与知识'].map(group=>{const kinds=visibleKinds.filter(kind=>nodeCatalog[kind].group===group);return kinds.length?<div className="aw-node-group" key={group}><h3>{group}</h3>{kinds.map(kind=>{const Icon=nodeIcons[kind];return <button key={kind} onClick={()=>add(kind)} disabled={running||graph.nodes.length>=30} title={nodeCatalog[kind].description}><Icon size={16}/><span>{nodeCatalog[kind].label}</span><Plus size={13}/></button>})}</div>:null})}{!visibleKinds.length&&<p>没有匹配节点</p>}<p className="aw-palette-hint">点击添加，再拖动圆点连线。也可在参数面板中选择连接。</p></aside>}
     <Suspense fallback={<div className="aw-canvas aw-canvas-loading"><LoaderCircle/>正在准备编排画布…</div>}><Canvas graph={graph} onChange={change} selected={selected} onSelect={select} states={states} locked={running} focus={focus}/></Suspense>
     {showInspector&&<aside className="aw-inspector" aria-label="节点参数"><NodeInspector graph={graph} selected={selected} onPatch={patch} onRemove={()=>{change({...graph,nodes:graph.nodes.filter(n=>n.id!==selected),edges:graph.edges.filter(e=>e.source!==selected&&e.target!==selected)});setSelected('')}} onConnect={connect} onRemoveEdge={id=>change({...graph,edges:graph.edges.filter(e=>e.id!==id)})} disabled={running}/></aside>}
    </div>
    <div className="aw-editor-footer"><span>{graph.nodes.length} 个节点 · {graph.edges.length} 条连线</span><span>滚动平移 · Ctrl / ⌘ + 滚轮缩放 · 选中连线后 Delete 删除</span></div>
   </div>
   <div className="aw-run-console" ref={consoleRef}><header><div><span className="aw-console-icon"><Play size={15}/></span><h2>运行与证据</h2><span>{running?(waiting?'等待人工复核':'模拟运行中'):result?.status==='complete'?`运行完成 · ${result.waves} 个执行波次`:'选择订单，运行一次流程'}</span></div></header>
    {errors.length>0&&<div role="alert" className="aw-error"><strong>先调整这些地方</strong><ul>{errors.map(e=><li key={e}>{e}</li>)}</ul></div>}
    {waiting&&<div className="aw-approval"><h3><ShieldCheck size={18}/>现在由你来复核</h3><EvidenceView data={waiting}/><p>{waiting.estimatedDays===undefined?'到货时间仍未知，请先安排人工核实缺失来源。':`预计 ${waiting.estimatedDays} 天到货，延误 ${waiting.lateDays} 天。请核对交期与来源。`}</p><div><Button size="sm" onClick={()=>{setWaiting(null);void pump(runToken.current,true)}}>确认此建议</Button><Button size="sm" variant="outline" onClick={()=>{setWaiting(null);void pump(runToken.current,false)}}>退回补充资料</Button><small>只继续教学流程，不执行外部操作。</small></div></div>}
    <div className="aw-run-columns"><div className="aw-trace" aria-label="运行日志" aria-live="polite">{!steps.length?<div className="aw-empty"><Workflow size={28}/><strong>看看任务是怎样完成的</strong><p>运行后，可展开每个节点查看输入、输出和 MCP 调用记录。</p></div>:steps.map(step=><details key={step.nodeId} data-state={step.state}><summary><span className="aw-trace-wave">{step.wave||'–'}</span><strong>{step.label}</strong><small>{step.state==='waiting'?'待复核':step.state==='skipped'?'未进入':step.state==='warning'?'待核实':step.state==='error'?'失败':'完成'}</small><ChevronRight size={14}/></summary><p>{step.detail}</p>{step.input!==undefined&&<><h4>输入</h4><pre>{JSON.stringify(step.input,null,2)}</pre></>}{step.output!==undefined&&<><h4>输出</h4><pre>{JSON.stringify(step.output,null,2)}</pre></>}{step.protocol&&<><h4>MCP 调用记录 · 简化模拟</h4><pre>{JSON.stringify(step.protocol,null,2)}</pre></>}</details>)}</div><div className="aw-result"><h3>本次交付</h3>{result?.text?<><pre>{result.text}</pre><EvidenceView data={result.data}/><Button size="sm" variant="outline" onClick={()=>{const url=URL.createObjectURL(new Blob([result.text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='订单履约-模拟简报.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}><Download size={14}/>保存简报</Button></>:<p>{waiting?'人工处理完成后，结果会出现在这里。':'运行结果将包含判断依据、待核实项和各系统的来源。'}</p>}</div></div>
   </div>
   {tab==='challenge'&&<section className="aw-assessment"><div className="aw-assessment-heading"><div><span className="aw-eyebrow">通关检查</span><h2>用三种情况验证你的流程</h2><p>自动测试会对异常建议选择「退回」，检查分支与结果是否保留。</p></div><Button onClick={verify} disabled={running}><CheckCircle2 size={17}/>运行通关检查</Button></div>{checks.length>0&&<div className="aw-checks">{checks.map(check=><div key={check.id} data-passed={check.passed}>{check.passed?<CheckCircle2 size={19}/>:<Info size={19}/>}<div><strong>{check.label}</strong><p>{check.detail}</p></div><span>{check.passed?'通过':'待调整'}</span></div>)}</div>}
    <div className="aw-quiz"><Choice label="MCP 在这个流程中负责什么？" value={quizMcp} onChange={setQuizMcp} options={[["protocol","连接应用与系统工具的协议"],["model","替代模型进行业务思考"],["permission","自动取得所有系统权限"]]}/><Choice label="为什么把履约检查做成 Skill？" value={quizSkill} onChange={setQuizSkill} options={[["procedure","复用检查步骤与参考规则"],["database","替代 ERP 保存订单"],["secret","把系统密钥交给模型"]]}/></div>
    <div className="aw-finish"><div>{completedAt?<><strong><CheckCircle2 size={18}/>本章节已学完</strong><span>{new Date(completedAt).toLocaleDateString('zh-CN')} 完成 · 已保存到你的学习记录</span></>:<><strong>{allPassed?'流程已通过检查，再确认两个概念即可通关。':'调整流程并通过全部检查，即可完成本章。'}</strong><span>完成标记会保存在账号下，下次回来仍可继续练习。</span></>}</div><Button disabled={!allPassed||!quizMcp||!quizSkill||saveState==='saving'} onClick={()=>void finish()}>{saveState==='saving'?<LoaderCircle size={16}/>:<GraduationCap size={17}/>}通关并保存</Button></div>{saveError&&<p role="alert" className="aw-error">{saveError}</p>}{saveState==='saved'&&<p role="status" className="aw-save-success"><Check size={16}/>通关记录已保存，章节已标记「已学完」。</p>}
   </section>}
  </>}
  <Dialog open={concepts} onOpenChange={setConcepts}><DialogContent className="aw-concepts"><DialogHeader><DialogTitle>从工作流，到智能体协作</DialogTitle><DialogDescription>先区分它们分别解决什么问题，再组合到自己的流程里。</DialogDescription></DialogHeader>{glossary.map(([title,description])=><div key={title}><h3>{title}</h3><p>{description}</p></div>)}<div className="aw-official-links"><a href="https://docs.dify.ai/en/cloud/use-dify/nodes/agent" target="_blank" rel="noopener noreferrer">Dify Agent 节点 ↗</a><a href="https://agentskills.io/home" target="_blank" rel="noopener noreferrer">Agent Skills ↗</a><a href="https://modelcontextprotocol.io/docs/learn/architecture" target="_blank" rel="noopener noreferrer">MCP 架构 ↗</a></div></DialogContent></Dialog>
  <AlertDialog open={reset!==null} onOpenChange={open=>{if(!open)setReset(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{reset==='challenge'?'载入综合挑战？':'恢复示例流程？'}</AlertDialogTitle><AlertDialogDescription>当前画布会被替换。需要保留时，请先导出流程；已保存的通关记录不受影响。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>保留当前画布</AlertDialogCancel><AlertDialogAction onClick={()=>reset&&loadTemplate(reset)}>载入流程</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </section>
}
