"use client";
import {useState} from 'react';import {Code2,FolderOpen,FileCode2,Bot,Send,Play,Check,GitCompare,RotateCcw,Terminal,AlertCircle,ChevronRight,Eye,Braces,Copy} from 'lucide-react';
import {Button} from '@/components/ui/button';import {Textarea} from '@/components/ui/textarea';import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';import {StudioHeading} from './studio-shared';import {scenarios} from '@/lib/simulation';
import {SyntaxCode,SyntaxEditor} from './syntax-editor';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
type Test={id:string,label:string,input:Record<string,unknown>,expected:unknown,beforeResult:unknown,afterResult:unknown,beforePass:boolean,afterPass:boolean};
type Scenario={id:string,title:string,topic:string,bug:string,targetFile:string,beforeCode:string,afterCode:string,prompts:{weak:string,specific:string,testAware:string},explanation:string,scopeNote:string,tests:Test[],takeaway:string};const cases=scenarios as unknown as Scenario[];
const normalize=(s:string)=>s.replace(/\s+/g,'').trim();
function simulate(s:Scenario,code:string){if(s.id==='quantity-variance'){const op=code.match(/return\s+invoicedQty\s*([+\-*/])\s*receivedQty\s*;/)?.[1];if(!op)return null;return s.tests.map(t=>{const a=Number(t.input.invoicedQty),b=Number(t.input.receivedQty);const actual=op==='-'?a-b:op==='+'?a+b:op==='*'?a*b:a/b;return {test:t,actual,pass:actual===t.expected}})}const kind=normalize(code)===normalize(s.beforeCode)?'before':normalize(code)===normalize(s.afterCode)?'after':null;if(!kind)return null;return s.tests.map(t=>({test:t,actual:kind==='after'?t.afterResult:t.beforeResult,pass:kind==='after'?t.afterPass:t.beforePass}))}
export default function CodeLab(){const[ideTheme,setIdeTheme]=useState('darcula');const[selected,setSelected]=useState(cases[0].id);const[drafts,setDrafts]=useState<Record<string,string>>(Object.fromEntries(cases.map(s=>[s.id,s.beforeCode])));const[prompt,setPrompt]=useState('');const[chat,setChat]=useState<{role:string,text:string}[]>([]);const[proposed,setProposed]=useState(false);const[tab,setTab]=useState('code');const[results,setResults]=useState<ReturnType<typeof simulate>>(null);const[ran,setRan]=useState(false);const[toast,setToast]=useState('');const[sending,setSending]=useState(false);const s=cases.find(c=>c.id===selected)!;const code=drafts[s.id];const currentEval=simulate(s,code);const fixed=normalize(code)===normalize(s.afterCode);
function choose(id:string){setSelected(id);setPrompt('');setChat([]);setProposed(false);setTab('code');setResults(null);setRan(false);setToast('')}
function ask(){const p=prompt.trim();if(!p)return;setChat(c=>[...c,{role:'user',text:p}]);setPrompt('');const detailed=p.length>45&&/函数|tenantId|invoice|数量|币种|发票|getQuantityVariance|postInvoice/.test(p);if(!detailed){setChat(c=>[...c,{role:'assistant',text:'先把问题说具体：哪个文件、正确的业务规则是什么、哪些行为要保留、用什么例子验收？你可以点击“明确业务约束”示例，再比较我的建议。'}]);setProposed(false);return}setProposed(true);setChat(c=>[...c,{role:'assistant',text:`定位：${s.targetFile}\n问题：${s.bug}\n\n建议：${s.explanation}\n\n${/测试|验证|复现/.test(p)?'你的提示包含验证要求。请先运行原始用例，再应用补丁并复查。':'建议补上边界与回归用例，避免只修复顺利路径。'}\n\n已准备一个可审阅的教学补丁，请确认后应用。`}])}
function apply(){setDrafts(d=>({...d,[s.id]:s.afterCode}));setProposed(false);setTab('changes');setResults(null);setRan(false);setToast('补丁已应用到当前模拟工程。现在运行示例回归。')}
function test(){setRan(true);setResults(simulate(s,code));setToast('')}
function reset(){setDrafts(d=>({...d,[s.id]:s.beforeCode}));setProposed(false);setResults(null);setRan(false);setToast('当前文件已恢复到练习起点。')}
return <><StudioHeading eyebrow="AI CODING STUDIO" title="AI 编程实训" desc="在一个供应链 ERP 模拟工程里，练习描述问题、审阅 AI 补丁，以及用业务样例验证修改。" simulation/>
<div className={`ide-shell idea-${ideTheme}`}><div className="ide-titlebar"><span><Code2 size={17}/>scm-erp / learning-workspace</span><span className="ide-environment">TypeScript · IDEA 配色</span><Select value={ideTheme} onValueChange={setIdeTheme}><SelectTrigger aria-label="编辑器配色" className="ide-theme-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="darcula">Darcula 深色</SelectItem><SelectItem value="light">IDEA 浅色</SelectItem></SelectContent></Select><button onClick={reset}><RotateCcw size={15}/>重置当前文件</button></div><div className="ide-grid"><aside className="ide-explorer"><h3><FolderOpen size={15}/>工程与问题</h3><div className="project-tree"><span><ChevronRight size={13}/>src / erp</span>{cases.map((c,i)=><button className={c.id===selected?'active':''} key={c.id} onClick={()=>choose(c.id)}><FileCode2 size={16}/><span>{c.targetFile.split('/').pop()}<small>{c.topic}</small></span>{normalize(drafts[c.id])!==normalize(c.beforeCode)&&<span className="changed-mark">M</span>}</button>)}</div><div className="issue-card"><span>ISSUE / {cases.findIndex(c=>c.id===s.id)+1}</span><h4>{s.title}</h4><p>{s.bug}</p></div><div className="ide-file-count">4 个练习 · 切换文件保留本次草稿</div></aside>
<section className="ide-editor"><div className="editor-tabs"><span><FileCode2 size={16}/>{s.targetFile.split('/').pop()}</span><Tabs value={tab} onValueChange={setTab}><TabsList><TabsTrigger value="code">代码</TabsTrigger><TabsTrigger value="changes">变更</TabsTrigger><TabsTrigger value="preview">业务预览</TabsTrigger></TabsList></Tabs></div>{tab==='code'&&<SyntaxEditor code={code} onChange={value=>{setDrafts(d=>({...d,[s.id]:value}));setRan(false);setResults(null)}}/>}{tab==='changes'&&<div className="code-diff"><h4><GitCompare size={16}/>原始版本 → 当前草稿</h4><pre className="removed"><SyntaxCode code={s.beforeCode.split('\n').map(x=>'- '+x).join('\n')}/></pre><pre className="added"><SyntaxCode code={code.split('\n').map(x=>'+ '+x).join('\n')}/></pre>{fixed&&<p><Check size={16}/>当前草稿与推荐修复一致。</p>}</div>}{tab==='preview'&&<div className="erp-preview"><div><span className="erp-logo">SCM</span><h3>ERP 业务结果预览</h3><span className="small-tag">合成样例</span></div><p>{s.topic}</p>{currentEval?<div className="preview-rows">{currentEval.map(({test,actual,pass})=><section key={test.id}><span className={pass?'passed':'failed'}>{pass?'通过':'异常'}</span><h4>{test.label}</h4><label>当前结果</label><pre>{JSON.stringify(actual,null,2)}</pre><small>预期：{JSON.stringify(test.expected)}</small></section>)}</div>:<div className="unsupported-note">当前自定义代码不在教学模拟器支持的规则内。请使用原始或推荐版本；此处不会执行任意 TypeScript。</div>}</div>}
<div className="editor-status"><span>UTF-8 · TypeScript</span><span>{code.split('\n').length} 行 · {fixed?'已修复':normalize(code)===normalize(s.beforeCode)?'原始版本':'已修改'}</span></div><div className="test-terminal"><div><h3><Terminal size={16}/>示例回归</h3><Button size="sm" onClick={test}><Play size={14}/>运行用例</Button></div>{!ran?<p className="terminal-hint">先运行原始版本，看到失败；再应用补丁，比较同一组业务样例。</p>:results?<>{results.map(r=><div className="terminal-test" key={r.test.id}><span className={r.pass?'passed':'failed'}>{r.pass?'PASS':'FAIL'}</span><span>{r.test.label}</span><code>{JSON.stringify(r.actual)}</code></div>)}<strong className="terminal-summary">{results.filter(r=>r.pass).length} / {results.length} 个示例符合预期</strong></>:<p className="terminal-hint warning">无法识别当前修改。模拟器支持内置前后版本，以及数量差异函数中的 + − × ÷ 运算符。</p>}</div></section>
<aside className="ide-assistant"><h3><Bot size={20}/>工程助手 <span>模拟</span></h3><div className="assistant-thread"><div className="assistant-welcome"><span><SparklesIcon/></span><h4>把业务意图说清楚。</h4><p>我会针对当前练习给出修复建议。比较不同提示词，观察需求边界与验收标准的作用。</p></div>{chat.map((m,i)=><div className={`chat-bubble ${m.role}`} key={i}><small>{m.role==='user'?'你':'教学助手'}</small><p>{m.text}</p></div>)}{proposed&&<div className="patch-proposal"><h4><GitCompare size={17}/>可审阅补丁</h4><pre><SyntaxCode code={s.afterCode}/></pre><Button onClick={apply}><Check size={16}/>应用补丁</Button></div>}{toast&&<p className="ide-toast" role="status">{toast}</p>}</div><div className="assistant-compose"><div className="prompt-presets">{[['weak','模糊描述'],['specific','明确业务约束'],['testAware','补充验收样例']].map(([k,label])=><button key={k} onClick={()=>setPrompt(s.prompts[k as keyof typeof s.prompts])}>{label}</button>)}</div><Textarea aria-label="发给模拟工程助手的提示词" placeholder="描述当前文件的问题、业务规则和验收样例…" value={prompt} onChange={e=>setPrompt(e.target.value)} rows={4}/><div><small>支持当前 4 个练习场景</small><Button onClick={ask} disabled={!prompt.trim()||sending} size="sm"><Send size={15}/>发送</Button></div></div></aside></div></div>
<div className="coding-takeaway"><div><strong>这一课带走什么</strong><p>{s.takeaway}</p></div><div><strong>工程边界</strong><p>{s.scopeNote}</p></div></div><p className="fine-print">这是可编辑的教学工程与预定义修复助手，不调用真实编码模型、不执行任意代码。示例回归由受限规则计算或预定义前后行为对照产生；不能代替真实项目的编译、测试与安全检查。</p></>}
function SparklesIcon(){return <Braces size={22}/>}
