"use client";
import {useState} from 'react';import {useHumanReview,ReviewChecklist} from './human-review';import {Copy,Check,Download,ArrowRight} from 'lucide-react';import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';import {Slider} from '@/components/ui/slider';import {Textarea} from '@/components/ui/textarea';import {Table,TableHeader,TableBody,TableHead,TableRow,TableCell} from '@/components/ui/table';
export function RangeField({label,value,onChange,min=0,max=100,step=1,unit=''}:{label:string,value:number,onChange:(n:number)=>void,min?:number,max?:number,step?:number,unit?:string}){return <label className="v3-range"><span>{label}<strong>{Number(value.toFixed(2))}{unit}</strong></span><Slider aria-label={label} value={[value]} min={min} max={max} step={step} onValueChange={v=>onChange(v[0])}/></label>}
export function NumberField({label,value,onChange,min=0,max=100000000,step=1}:{label:string,value:number,onChange:(n:number)=>void,min?:number,max?:number,step?:number}){return <label className="v3-field">{label}<Input aria-label={label} type="number" min={min} max={max} step={step} value={value} onChange={e=>onChange(Math.max(min,Math.min(max,Number(e.target.value))))}/></label>}
export function ResultBox({title,children,tone='normal'}:{title:string,children:React.ReactNode,tone?:'normal'|'warn'|'good'}){return <div className={`v3-result ${tone}`} role="status"><strong>{title}</strong><div>{children}</div></div>}
export function SmallTable({headers,rows}:{headers:string[],rows:(string|number|React.ReactNode)[][]}){return <div className="v3-table"><Table><TableHeader><TableRow>{headers.map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((r,i)=><TableRow key={i}>{r.map((v,j)=><TableCell key={j}>{v}</TableCell>)}</TableRow>)}</TableBody></Table></div>}
export function CopyText({text,label='复制示例提示词',beforeCopy}:{text:string,label?:string,beforeCopy?:()=>boolean}){const[status,setStatus]=useState('');return <div className="v3-copy"><Button variant="outline" onClick={async()=>{if(beforeCopy&&!beforeCopy())return;try{await navigator.clipboard.writeText(text);setStatus('已复制')}catch{setStatus('请手动选择下方文字复制')}}}>{status==='已复制'?<Check size={15}/>:<Copy size={15}/>} {label}</Button>{status&&<small role="status">{status}</small>}</div>}
export function downloadText(name:string,text:string,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export function MeetingDemo(){const[notes,setNotes]=useState('采购岗 | 完成 40 吨采购草案 | 2026-09-23\n物流岗 | 核实 9 月 25 日能否到货 | 待确认\n质量岗 | 复核供应商样品 | 待确认');const[rows,setRows]=useState<string[][]|null>(null);const[err,setErr]=useState('');const[focus,setFocus]=useState(-1);const review=useHumanReview(JSON.stringify([notes,rows]),['行动与原句逐项核对一致','责任人与日期已核对，未明确的信息保留待确认'],!!rows);function run(){const lines=notes.trim().split('\n').filter(Boolean);if(!notes.trim()||lines.some(l=>l.split('|').length!==3)){setErr('请按“责任岗位 | 任务 | 截止日期或待确认”填写，每行一项。');setRows(null);return}setErr('');setRows(lines.map(l=>l.split('|').map(s=>s.trim()||'待确认')))}return <div className="demo-split"><section><span className="demo-step">01 / 示例转写记录</span><h3>纪要的重点是行动与证据</h3><p>本实验使用结构化示例转写，保留缺失信息。编辑任意一行后重新整理。</p><Textarea aria-label="会议示例记录" value={notes} rows={7} onChange={e=>{setNotes(e.target.value);setRows(null);setErr('')}}/><small>输入格式：责任岗位 | 任务 | 截止日期。竖线分隔，每行一项。</small><Button onClick={run}>整理行动清单 <ArrowRight size={16}/></Button>{err&&<p role="alert" className="v3-error">{err}</p>}</section><section><span className="demo-step">02 / 结果与原句</span>{rows?<><SmallTable headers={['负责人','行动','截止日期','证据']} rows={rows.map((r,i)=>[...r,<button key={i} className="table-link" onClick={()=>setFocus(i)}>第 {i+1} 行</button>])}/>{focus>=0&&rows[focus]&&<ResultBox title="原始记录">{rows[focus].join(' | ')}</ResultBox>}<ResultBox title={`有 ${rows.filter(r=>r.includes('待确认')).length} 项需要补充信息`} tone={rows.some(r=>r.includes('待确认'))?'warn':'good'}>目标到货日期不自动等于核实任务的截止日期，未提及的信息保持“待确认”。</ResultBox><ReviewChecklist review={review}/><Button variant="outline" onClick={()=>review.request()&&downloadText('meeting-actions.csv','\uFEFF负责人,任务,截止日期\n'+rows.map(r=>r.map(x=>'"'+x.replaceAll('"','""')+'"').join(',')).join('\n'),'text/csv;charset=utf-8')}><Download size={16}/>下载行动清单</Button></>:<div className="demo-empty"><Check size={28}/><p>整理后显示负责人、行动项与原句依据。</p></div>}</section></div>}
