"use client";
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,BookOpen,Check,Code2,Compass,Flag,Layers,Pause,Play,Route,ShieldCheck,Sparkles,Target,Workflow} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
export const learningRoles={
 pm:{name:'AI 项目经理',icon:Target,lead:'让每一次交付，都有可验证的依据。',steps:[['定义成功','把采购审单的范围、责任人与验收标准写清楚。','一份有边界的试点任务书','/learn?lesson=pm'],['运行实验','改变审单规则，观察正常、异常与人工确认的分支。','一个可解释的智能体流程','/agents'],['验证结果','用固定样本检查错误、复核时间与成功任务成本。','一组可复现的验收证据','/learn?lesson=evaluation']]},
 product:{name:'AI 产品经理',icon:Layers,lead:'从一个工作任务，走向一款可用的产品。',steps:[['理解任务','选择真实用户，把问题拆成目标、输入和决策。','一张用户任务与价值地图','/learn?lesson=prompt'],['设计体验','组织知识与工具，设计回答、引用和失败时的退路。','一套有来源的产品交互','/learn?lesson=context'],['验证价值','进入供应链业务，比较方案如何影响交付与成本。','一个能够讨论的业务原型','/ontology']]},
 fde:{name:'AI 开发 / FDE',icon:Code2,lead:'把业务语言，翻译成能够运行的系统。',steps:[['读懂工程','从 ERP 缺陷出发，理解接口、数据和问题上下文。','一份可复现的问题说明','/coding'],['接通流程','串起模型、知识检索与业务规则，观察每一步输出。','一个可以运行的业务工作流','/agents'],['检查边界','调整模型参数与异常条件，检查失败路径和运行证据。','一套交付检查与排错记录','/models']]},
};
export type LearningRole=keyof typeof learningRoles;
const icons=[Compass,Workflow,ShieldCheck];
export default function LearningVoyage(){
 const[role,setRole]=useState<LearningRole>('pm'),[step,setStep]=useState(0),[playing,setPlaying]=useState(false),[visible,setVisible]=useState(true),[reduced,setReduced]=useState(false);const host=useRef<HTMLElement>(null);
 const path=learningRoles[role],current=path.steps[step];
 useEffect(()=>{const q=matchMedia('(prefers-reduced-motion: reduce)');const sync=()=>{setReduced(q.matches);setPlaying(!q.matches)};sync();q.addEventListener('change',sync);const observer=new IntersectionObserver(([entry])=>setVisible(entry.isIntersecting),{threshold:.15});if(host.current)observer.observe(host.current);return()=>{q.removeEventListener('change',sync);observer.disconnect()}},[]);
 useEffect(()=>{if(!playing||!visible)return;const timer=setTimeout(()=>{if(step===2)setPlaying(false);else setStep(step+1)},3400);return()=>clearTimeout(timer)},[playing,visible,step,role]);
 return <section className={`voyage-hero ${playing&&!reduced?'voyage-playing':''}`} ref={host} aria-label="学习启航与角色路线"><div className="voyage-glow" aria-hidden="true"/><div className="voyage-intro"><span className="voyage-eyebrow"><Compass size={17}/>YOUR NEXT CHAPTER</span><h1>把 AI，<br/>学进<span>你的工作里。</span></h1><p>从日常提效，到供应链产品与业务交付。选择你的角色，找到今天的第一步。</p><Tabs value={role} onValueChange={v=>{setRole(v as LearningRole);setStep(0);setPlaying(!reduced)}}><TabsList className="voyage-role-tabs" aria-label="选择学习角色">{Object.entries(learningRoles).map(([id,r])=><TabsTrigger key={id} value={id}><r.icon size={16}/>{r.name}</TabsTrigger>)}</TabsList></Tabs><div className="voyage-entry-actions"><a className="voyage-primary" href={current[3]}>开始这一步 <ArrowRight size={17}/></a><a className="voyage-secondary" href="/roadmap">查看 12 周路线 <Route size={16}/></a></div></div>
 <div className="voyage-preview"><div className="voyage-preview-top"><span>你的成长路径</span><button onClick={()=>{if(!playing&&step===2)setStep(0);setPlaying(!playing)}} aria-label={playing?'暂停成长路径演示':'播放成长路径演示'}>{playing?<Pause size={15}/>:<Play size={15}/>} {playing?'暂停':'播放'}</button></div><div className="voyage-route-card"><div className="voyage-route-title"><span className="voyage-role-icon"><path.icon size={23}/></span><div><small>LEARNING PATH</small><strong>{path.name}</strong></div><span className="voyage-step-count">0{step+1} / 03</span></div><h2>{path.lead}</h2><div className="voyage-stages">{path.steps.map((s,i)=>{const Icon=icons[i];return <button key={s[0]} className={step===i?'active':i<step?'passed':''} aria-pressed={step===i} aria-label={`查看成长步骤：${s[0]}`} onClick={()=>{setStep(i);setPlaying(false)}}><span>{i<step?<Check size={19}/>:<Icon size={19}/>}</span><strong>{s[0]}</strong><small>0{i+1}</small></button>})}</div><div className="voyage-step-explainer" key={role+step} aria-live={playing?'off':'polite'}><span>这一站，你会做什么</span><p>{current[1]}</p><a href={current[3]}>进入对应练习 <ArrowRight size={15}/></a></div></div><div className="voyage-deliverable"><span><Flag size={21}/></span><div><small>带着一个成果离开</small><strong>{current[2]}</strong></div><Check size={19}/></div><div className="voyage-footnotes"><span><BookOpen size={15}/>理解概念</span><span><Sparkles size={15}/>动手实验</span><span><ShieldCheck size={15}/>回看证据</span></div></div></section>;
}
