"use client";
import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,ArrowUpRight,BookOpen,Check,CheckCircle2,Clock,Compass,Flag,Layers,Route,Sparkles,Target,Workflow} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import knowledge from '@/lib/knowledge.json';
import {learningRoles,type LearningRole} from './learning-voyage';
const phases=[{name:'理解与设计',range:'01 — 04',icon:Compass,desc:'从工作任务出发，找到 AI 的价值与边界。'},{name:'构建与验证',range:'05 — 08',icon:Workflow,desc:'连接知识与工具，用证据检验可用性。'},{name:'试点与交付',range:'09 — 12',icon:Flag,desc:'走进业务现场，把实验沉淀为作品。'}];
const readings=[[35,33],[56,2],[9,10],[57,58],[25,26],[45,46],[12,43],[41,42],[53,18],[9,10],[52,54],[16,5]];
const practices=[['/learn?lesson=pm','定义项目成功标准'],['/tools?category=writing','制作一份有依据的周报'],['/learn?lesson=prompt','把用户任务写清楚'],['/coding','试做可交互原型'],['/agents#agent-builder','搭建采购审单工作流'],['/coding','检查接口与数据契约'],['/learn?lesson=evaluation','设计评测样例'],['/agents#agent-builder','查看一次完整运行'],['/ontology?case=mes','演练产线异常处置'],['/ontology?case=tms','比较运输计划取舍'],['/tools?category=presentations','制作可审阅的汇报'],['/community','整理并分享实践作品']];
const extras={pm:'写清责任人、依赖条件，以及进入下一阶段需要哪些证据。',product:'访谈一位目标用户，为正常和失败状态各写一个样例。',fde:'检查接口返回与运行日志，让结果能够重现和验证。'};
export default function LearningRoadmap({onResource,onArticle}:{onResource:(id:number)=>void;onArticle:(id:number)=>void}){
 const[role,setRole]=useState<LearningRole>('pm'),[week,setWeek]=useState(0),[done,setDone]=useState<number[]>([]);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('ai-practice-roadmap-v1')||'[]');if(Array.isArray(saved))setDone([...new Set(saved.filter(n=>Number.isInteger(n)&&n>=0&&n<12))])}catch{}},[]);
 const phase=Math.floor(week/4),w=knowledge.weeks[week];
 function toggleDone(){const next=done.includes(week)?done.filter(n=>n!==week):[...done,week];setDone(next);try{localStorage.setItem('ai-practice-roadmap-v1',JSON.stringify(next))}catch{}}
 return <div className="onboarding-roadmap"><header className="journey-page-hero"><div><span className="voyage-eyebrow"><Route size={17}/>ONE PROJECT. TWELVE WEEKS.</span><h1>把一次尝试，<br/>走成你的<span>新能力。</span></h1><p>用一个真实场景贯穿 12 周。理解、构建、验证，每一站都留下一份看得见的成果。</p><div className="roadmap-hero-meta"><span><Clock size={16}/>建议每周 6–8 小时</span><span><Layers size={16}/>3 个成长阶段</span></div></div><div className="roadmap-progress-card"><div><span>你的实践足迹</span><strong>{String(done.length).padStart(2,'0')}<small> / 12 周</small></strong></div><div className="roadmap-progress-dots" aria-label={`已自评完成 ${done.length} 周`}>{knowledge.weeks.map((_,i)=><button key={i} onClick={()=>setWeek(i)} className={`${done.includes(i)?'done':''} ${week===i?'selected':''}`} aria-label={`查看第 ${i+1} 周${done.includes(i)?'，已自评完成':''}`}>{done.includes(i)?<Check size={16}/>:String(i+1).padStart(2,'0')}</button>)}</div><p>进度由你标记，保存在当前浏览器。<br/>点击任一周，就从那里继续。</p></div></header>
 <section className="roadmap-planner" aria-label="十二周学习计划"><div className="roadmap-planner-top"><div><span className="voyage-eyebrow">CHOOSE YOUR PERSPECTIVE</span><h2>同一条路线，不同的关注点。</h2></div><Tabs value={role} onValueChange={v=>setRole(v as LearningRole)}><TabsList className="voyage-role-tabs" aria-label="学习路线角色">{Object.entries(learningRoles).map(([id,r])=><TabsTrigger key={id} value={id}><r.icon size={16}/>{r.name}</TabsTrigger>)}</TabsList></Tabs></div><div className="roadmap-phases">{phases.map((p,i)=><button key={p.name} onClick={()=>setWeek(i*4)} aria-pressed={phase===i} className={phase===i?'active':''}><span className="roadmap-phase-icon"><p.icon size={23}/></span><div><small>WEEK {p.range}</small><strong>{p.name}</strong><p>{p.desc}</p></div><ArrowRight size={18}/></button>)}</div>
 <div className="roadmap-workspace"><nav className="roadmap-weeks" aria-label="选择学习周次">{phases.map((p,i)=><div key={p.name}><h3><span>0{i+1}</span>{p.name}</h3><div>{knowledge.weeks.slice(i*4,i*4+4).map((wk,j)=>{const n=i*4+j;return <button key={n} onClick={()=>setWeek(n)} className={week===n?'active':''} aria-pressed={week===n} aria-label={`第 ${n+1} 周：${wk[1].split('；')[0]}`}><span>W{String(n+1).padStart(2,'0')}</span><strong>{wk[1].split('；')[0].split('、')[0]}</strong>{done.includes(n)?<CheckCircle2 size={15}/>:<ArrowRight size={15}/>}</button>})}</div></div>)}</nav><article className="roadmap-week-detail" key={`${week}-${role}`}><div className="roadmap-detail-top"><span>WEEK {String(week+1).padStart(2,'0')} <i>/</i> {phases[phase].name}</span><span><Clock size={14}/>6–8 小时</span></div><h2>{w[1].split('；')[0]}</h2><p className="roadmap-task">{w[1]}</p><div className="roadmap-output"><Flag size={24}/><div><small>用什么证明你学会了</small><strong>{w[2]}</strong></div></div><div className="roadmap-role-note"><Target size={19}/><div><strong>{learningRoles[role].name} · 本周关注</strong><p>{extras[role]}</p></div></div><h3 className="roadmap-reading-label">把方法读懂</h3><div className="roadmap-reading">{readings[week].map(id=>{const r=knowledge.resources.find(x=>x.id===id)!;return <button key={id} onClick={()=>onResource(id)}><BookOpen size={18}/><span>{r.title}</span><ArrowUpRight size={16}/></button>})}</div><div className="roadmap-week-actions"><a className="voyage-primary" href={practices[week][0]}>{practices[week][1]}<ArrowRight size={16}/></a><button className={`roadmap-mark ${done.includes(week)?'done':''}`} onClick={toggleDone} aria-pressed={done.includes(week)}><CheckCircle2 size={17}/>{done.includes(week)?'已完成 · 点击撤销':'标记本周已完成'}</button></div><div className="roadmap-page-controls"><button disabled={week===0} onClick={()=>setWeek(week-1)}><ArrowLeft size={15}/>上一周</button><span>第 {week+1} / 12 周</span><button disabled={week===11} onClick={()=>setWeek(week+1)}>下一周<ArrowRight size={15}/></button></div></article></div></section>
 <div className="roadmap-fast-track"><span><Sparkles size={25}/></span><div><h2>已经做过 Dify 或智能问数？</h2><p>可以从第 6 周起，重点补齐集成、评测与业务验证。</p></div><button onClick={()=>{setWeek(5);document.querySelector('.roadmap-planner')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'})}}>跳到第 6 周<ArrowRight size={16}/></button><button onClick={()=>onArticle(15)}>选择作品题目<ArrowUpRight size={16}/></button></div></div>;
}
