"use client";
import {useHumanReview,ReviewChecklist,useReviewFeedback,ReviewWarning} from './human-review';
import {useEffect,useRef,useState} from 'react';
import {Mic,Upload,FileVideo,Play,Pause,Square,RotateCcw,Check,Download,FileText,Clock,Users,Languages,Bookmark,ArrowRight,CheckCircle2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Switch} from '@/components/ui/switch';
import {Progress} from '@/components/ui/progress';
import {MeetingDemo,downloadText} from './experience-shared';

const transcript=[
 {time:'00:00',speaker:0,text:'今天评审华东仓采购审单试点。试点范围只包括采购单、收货单和发票的三单匹配。',en:'The pilot covers three-way matching in the East China warehouse.'},
 {time:'00:18',speaker:1,text:'主数据还存在重复供应商编码。我负责清理，截止日期是 9 月 25 日。',en:'I will clean the duplicate supplier records by September 25.'},
 {time:'00:42',speaker:2,text:'我负责接口联调，计划 9 月 29 日完成，前提是主数据先通过检查。',en:'I will complete integration testing by September 29, after master-data validation.'},
 {time:'01:10',speaker:1,text:'欧西啊识别的发票金额仍需要人工复核。数量或金额有差异时，不能自动过账。',en:'OCR invoice amounts require review; mismatches must block automatic posting.'},
 {time:'01:36',speaker:0,text:'预算还没有批准，不能写成已批准。我们暂定 10 月 9 日上线，仍需评审通过。',en:'The budget is not approved. October 9 is a tentative launch date.'},
 {time:'02:04',speaker:2,text:'需要安排一次操作培训，负责人和日期本次还没有确定。',en:'Operator training needs an owner and a date, both to be confirmed.'},
 {time:'02:27',speaker:0,text:'今天确认：先做华东仓试点；异常单据进入人工复核；上线日期是计划，不是承诺。',en:'Confirmed: pilot in East China, manual review for exceptions, tentative launch date.'},
 {time:'02:52',speaker:1,text:'我们按这三项待办推进，下次会议检查主数据、接口联调和培训准备情况。',en:'Next time we will review master data, integration, and training readiness.'}
];
type Task={source:number;owner:string;task:string;date:string;dependency:string;done:boolean};
const taskSeeds:Task[]=[{source:1,owner:'陈晓 · 数据',task:'清理重复供应商编码',date:'2026-09-25',dependency:'待确认',done:false},{source:2,owner:'李舟 · 开发',task:'接口联调',date:'2026-09-29',dependency:'主数据通过检查',done:false},{source:5,owner:'待确认',task:'安排操作培训',date:'待确认',dependency:'待确认',done:false}];
export default function MeetingStudio(){
 const[mode,setMode]=useState('live');const[generation,setGeneration]=useState(0);const[running,setRunning]=useState(false);const[count,setCount]=useState(0);const[ended,setEnded]=useState(false);const[tick,setTick]=useState(0);const[speed,setSpeed]=useState('normal');const[translation,setTranslation]=useState(false);const[glossary,setGlossary]=useState(true);const[marked,setMarked]=useState<number[]>([]);const[speakers,setSpeakers]=useState(['周宁 · 项目','陈晓 · 数据','李舟 · 开发']);const[resultTab,setResultTab]=useState('transcript');const[generated,setGenerated]=useState(false);const[tasks,setTasks]=useState<Task[]>([]);const[highlight,setHighlight]=useState(-1);const[file,setFile]=useState<{name:string;size:number;sample:boolean}|null>(null);const[upload,setUpload]=useState(0);const[processing,setProcessing]=useState(false);const[error,setError]=useState('');const input=useRef<HTMLInputElement>(null);const rowRefs=useRef<(HTMLDivElement|null)[]>([]);
 useEffect(()=>{if(!running)return;const timer=setInterval(()=>{setTick(t=>t+1);setCount(c=>{const n=Math.min(c+1,transcript.length);if(n===transcript.length){setRunning(false);setEnded(true)}return n})},speed==='fast'?650:2000);return()=>clearInterval(timer)},[running,speed]);
 useEffect(()=>{if(!processing)return;const timer=setInterval(()=>setUpload(p=>Math.min(100,p+10)),450);return()=>clearInterval(timer)},[processing]);
 useEffect(()=>{if(upload===100&&processing){setProcessing(false);setCount(transcript.length);setEnded(true)}},[upload,processing]);
 function clear(){setRunning(false);setCount(0);setTick(0);setEnded(false);setGenerated(false);setTasks([]);setMarked([]);setResultTab('transcript');setUpload(0);setProcessing(false);setError('');setHighlight(-1)}
 function switchMode(v:string){clear();setMode(v);setFile(null)}
 function selectFile(f?:File){if(!f)return;clear();setFile(null);if(!/\.(mp4|mov|webm|mp3|wav|m4a)$/i.test(f.name)){setError('请选择 MP4、MOV、WebM、MP3、WAV 或 M4A 文件。');return}if(f.size>200*1024*1024){setError('演练支持选择 200 MB 以内的文件。');return}if(f.size===0){setError('文件为空，请重新选择。');return}setFile({name:f.name,size:f.size,sample:false})}
 function summarize(){setGeneration(n=>n+1);setTasks(taskSeeds.filter(t=>t.source<count).map(t=>({...t,owner:t.source===1?speakers[1]:t.source===2?speakers[2]:t.owner})));setGenerated(true);setResultTab('minutes')}
 function locate(i:number){setResultTab('transcript');setHighlight(i);setTimeout(()=>rowRefs.current[i]?.scrollIntoView({behavior:'smooth',block:'nearest'}),50)}
 const visible=transcript.slice(0,count);const fmt=(text:string)=>glossary?text.replace('欧西啊','OCR'):text;
 const minutes=[count>0?'试点范围：华东仓采购单、收货单、发票三单匹配。':'',count>3?'业务约束：识别金额需复核，差异单据不得自动过账。':'',count>4?'风险：预算尚未批准；10 月 9 日仅为计划上线日。':'',count>5?'待确认：培训负责人和培训日期。':''].filter(Boolean);
 const review=useHumanReview(JSON.stringify([generation,count,glossary,marked,speakers,generated,tasks.map(({done,...t})=>t)]),['逐字稿、说话人和专业词已核对','纪要中的事实、风险与计划已回查原句'],generated);
 const taskReview=useReviewFeedback(tasks.every(t=>t.done),()=>setResultTab('tasks'));
 function allowExport(){if(!review.request())return false;return taskReview.request()}
 const exportText=()=>allowExport()&&downloadText('meeting-notes.md',`# 华东仓采购审单试点评审\n\n教学样例；非上传文件实际识别结果。\n\n## 逐字稿\n${visible.map((t,i)=>`[${t.time}] ${speakers[t.speaker]}：${fmt(t.text)}${marked.includes(i)?' ★重点':''}`).join('\n\n')}\n\n## 纪要\n${minutes.join('\n')}\n\n## 待办\n${tasks.map(t=>`- [${t.done?'x':' '}] ${t.owner}｜${t.task}｜${t.date}｜前置：${t.dependency}｜原文 ${transcript[t.source].time}`).join('\n')}`);
 return <div className="meeting-studio"><div className="meeting-mode-row"><Tabs value={mode} onValueChange={switchMode}><TabsList><TabsTrigger value="live"><Mic size={15}/>实时会议</TabsTrigger><TabsTrigger value="upload"><Upload size={15}/>音视频转写</TabsTrigger><TabsTrigger value="text"><FileText size={15}/>文本整理</TabsTrigger></TabsList></Tabs><span>仿真工作台</span></div>{mode==='text'?<MeetingDemo/>:<>
 <div className="meeting-workspace"><section className="meeting-controls"><div className="meeting-mode-icon">{mode==='live'?<Mic size={27}/>:<FileVideo size={27}/>}</div><h3>{mode==='live'?'让讨论，变成可追踪的行动':'从一份音视频，整理完整会议'}</h3><p>{mode==='live'?'用预置会议逐句演练实时转写，无需打开麦克风。':'体验文件选择、处理进度、逐字稿和纪要复核的完整流程。'}</p>
 {mode==='live'?<><div className={`recording-display ${running?'recording':''}`}><div className="record-bars" aria-hidden="true">{[9,21,13,29,18,35,16,24,10,27,17,31,12,20,8].map((n,i)=><i style={{height:n,animationDelay:`${i*.07}s`}} key={i}/>)}</div><strong>{String(Math.floor(tick*2/60)).padStart(2,'0')}:{String(tick*2%60).padStart(2,'0')}</strong><span>{ended?'样例记录已结束':running?'正在回放样例发言':count?'记录已暂停':'准备开始 · 8 段样例发言'}</span></div><div className="meeting-record-actions"><Button disabled={ended} onClick={()=>{if(!running){setGenerated(false);setResultTab('transcript')}setRunning(v=>!v)}}>{running?<Pause size={16}/>:<Mic size={16}/>} {running?'暂停记录':count?'继续记录':'开始模拟记录'}</Button><Button variant="outline" disabled={!count||ended} onClick={()=>{setRunning(false);setEnded(true)}}><Square size={14}/>结束</Button></div><label className="meeting-setting">回放速度<Select value={speed} onValueChange={setSpeed}><SelectTrigger aria-label="会议样例回放速度"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="normal">标准 · 每 2 秒一句</SelectItem><SelectItem value="fast">快速 · 每 0.65 秒一句</SelectItem></SelectContent></Select></label></>:<><div className="meeting-dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!processing)selectFile(e.dataTransfer.files[0])}}><Upload size={25}/><strong>{file?file.name:'拖入音视频文件，或点击选择'}</strong><p>{file?`${file.sample?'内置样例':(file.size/1024/1024).toFixed(1)+' MB'} · 仅模拟处理`:'MP4 / MOV / WebM / MP3 / WAV / M4A · ≤ 200 MB'}</p><input ref={input} aria-label="选择会议音视频文件" type="file" accept=".mp4,.mov,.webm,.mp3,.wav,.m4a" onChange={e=>{selectFile(e.target.files?.[0]);e.target.value=''}} hidden/><Button variant="outline" disabled={processing} onClick={()=>input.current?.click()}>选择本地文件</Button><button className="meeting-sample-link" disabled={processing} onClick={()=>{clear();setFile({name:'华东仓采购审单评审.mp4',size:18400000,sample:true})}}>使用内置会议样例</button></div>{file&&<><p className="meeting-file-note">{file.sample?'将使用预置样例逐字稿演示。':'仅读取文件名与大小，不上传、播放或识别文件；演示结果仍来自预置会议。'}</p><Button disabled={processing||upload===100} onClick={()=>{setProcessing(true);setUpload(0)}}><Play size={15}/>开始模拟转写</Button>{processing&&<Button variant="ghost" onClick={()=>{setProcessing(false);setUpload(0);setError('已取消模拟处理，可以重新开始。')}}>取消</Button>}</>}{(processing||upload>0)&&<div className="upload-progress"><Progress value={upload}/><span>{upload}% · {upload<25?'模拟上传':upload<50?'模拟分离音轨':upload<80?'模拟转写与说话人分离':upload<100?'整理时间戳':'样例转写完成'}</span></div>}{error&&<p role="alert" className="v3-error">{error}</p>}</>}
 <div className="meeting-options"><label><Languages size={16}/>中英对照<Switch checked={translation} onCheckedChange={setTranslation} aria-label="显示样例英文对照"/></label><label><CheckCircle2 size={16}/>专业词纠正<Switch checked={glossary} onCheckedChange={setGlossary} aria-label="启用 OCR 专业词纠正"/></label><small>教学词表：欧西啊 → OCR。英文为预置译文。</small></div><details className="speaker-settings"><summary><Users size={15}/>校正说话人名称</summary>{speakers.map((s,i)=><Input key={i} aria-label={`说话人 ${i+1} 名称`} value={s} maxLength={24} onChange={e=>{setSpeakers(v=>v.map((x,n)=>n===i?e.target.value:x));setGenerated(false);setResultTab('transcript')}}/>)}</details><button className="meeting-reset" onClick={clear}><RotateCcw size={14}/>重新演练</button></section>
 <section className="meeting-output"><header><div><span className="eyebrow">SCM PILOT REVIEW · 2026.09.20</span><h3>华东仓采购审单试点评审</h3></div><span className="meeting-status">{running?'记录中':processing?'处理中':ended?'待复核':'样例会议'}</span></header><Tabs value={resultTab} onValueChange={setResultTab}><TabsList variant="line"><TabsTrigger value="transcript">逐字稿 <small>{count}/8</small></TabsTrigger><TabsTrigger value="minutes" disabled={!generated}>会议纪要</TabsTrigger><TabsTrigger value="tasks" disabled={!generated}>行动清单 {generated&&tasks.length}</TabsTrigger></TabsList></Tabs>
 {resultTab==='transcript'&&<div className="meeting-transcript">{!count?<div className="meeting-placeholder"><Mic size={30}/><h4>{mode==='live'?'准备记录第一句发言':'等待样例转写完成'}</h4><p>说话人、时间戳和重点标记会显示在这里。</p></div>:visible.map((t,i)=><div ref={el=>{rowRefs.current[i]=el}} className={`transcript-row ${highlight===i?'located':''}`} key={i}><div className={`speaker-avatar speaker-${t.speaker}`}>{speakers[t.speaker].slice(0,1)}</div><div><div className="transcript-meta"><strong>{speakers[t.speaker]||`说话人 ${t.speaker+1}`}</strong><span>{t.time}</span><button title="标记重点" aria-label={`${marked.includes(i)?'取消':'添加'} ${t.time} 重点标记`} aria-pressed={marked.includes(i)} onClick={()=>setMarked(v=>v.includes(i)?v.filter(n=>n!==i):[...v,i])}><Bookmark size={15} fill={marked.includes(i)?'currentColor':'none'}/></button></div><p>{fmt(t.text)}</p>{translation&&<p className="transcript-translation">{t.en}</p>}{i===3&&glossary&&<small className="glossary-hint">术语已校正 · OCR</small>}</div></div>)}</div>}
 {resultTab==='minutes'&&<div className="meeting-minutes"><span className="meeting-result-label">基于已显示的样例片段归纳 · 需人工复核</span><h4>讨论结论与风险</h4>{minutes.map((s,i)=><p key={s}><Check size={16}/>{s}</p>)}{count>4&&<button onClick={()=>locate(4)}>核对“预算未批”的原文 <ArrowRight size={15}/></button>}<div className="minutes-stat"><strong>{tasks.length} 项待办</strong><span>{tasks.filter(t=>t.owner==='待确认'||t.date==='待确认').length} 项负责人/日期待补</span><span>{marked.length} 段重点标记</span></div><p className="meeting-file-note">只根据已记录片段生成教学纪要；提前结束时不会补全未出现的发言。</p></div>}
 {resultTab==='tasks'&&<div ref={taskReview.ref} className={`meeting-task-list ${taskReview.className}`}><h4 data-review-trigger tabIndex={-1}>逐项复核行动清单</h4><ReviewWarning show={taskReview.blocked}/>{tasks.map((t,i)=><article key={t.source} data-review-missing={!t.done}><div><Switch checked={t.done} onCheckedChange={v=>setTasks(a=>a.map((x,n)=>n===i?{...x,done:v}:x))} aria-label={`标记${t.task}已复核`}/><strong>{t.task}</strong><span>{t.done?'已复核':'待复核'}</span></div><div className="task-edit-grid"><label>负责人<Input aria-label={`${t.task}负责人`} value={t.owner} onChange={e=>setTasks(a=>a.map((x,n)=>n===i?{...x,owner:e.target.value,done:false}:x))}/></label><label>截止日期<Input aria-label={`${t.task}截止日期`} value={t.date} onChange={e=>setTasks(a=>a.map((x,n)=>n===i?{...x,date:e.target.value,done:false}:x))}/></label></div><p>前置条件：{t.dependency}</p><button onClick={()=>locate(t.source)}><Clock size={14}/>原文 {transcript[t.source].time}</button></article>)}<p className="meeting-file-note">人工补充的负责人和日期会写入导出稿；逐字稿保留原始证据。</p></div>}
 {generated&&<ReviewChecklist review={review}/>}<footer><span>{count?`${count} 段发言 · ${new Set(visible.map(x=>x.speaker)).size} 位说话人`:'等待输入'}</span><Button disabled={!count||running||processing} onClick={summarize}><FileText size={15}/>{generated?'重新整理纪要':'整理会议纪要'}</Button><Button variant="outline" disabled={!generated} onClick={exportText}><Download size={15}/>导出</Button></footer></section></div></>}
 </div>
}
