"use client";
import {useState,useMemo} from 'react';import {Play,RotateCcw,SlidersHorizontal,Database,Sparkles,Check,Info,ArrowRight} from 'lucide-react';
import {Slider} from '@/components/ui/slider';import {Switch} from '@/components/ui/switch';import {Button} from '@/components/ui/button';import {Textarea} from '@/components/ui/textarea';import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';import {StudioHeading} from './studio-shared';import {candidateDistribution,invoices,money} from '@/lib/simulation';
const models={light:{label:'轻量模型 · 模拟',factor:1},balanced:{label:'均衡模型 · 模拟',factor:2},reasoning:{label:'推理模型 · 模拟',factor:4}};
const docs=[{id:'metric',title:'采购金额口径',size:120,desc:'6 张未税 CNY 发票，按开票金额汇总。',relevant:true},{id:'invoice',title:'2026-09 示例发票明细',size:480,desc:'金额与单据编号，供只读聚合。',relevant:true},{id:'acl',title:'演示权限：法人 A',size:80,desc:'仅允许访问此演示数据集。',relevant:true},{id:'manual',title:'ERP 界面操作手册',size:800,desc:'当前问题不需要的 UI 操作说明。',relevant:false},{id:'old',title:'2024 年历史会议记录',size:500,desc:'过期材料，不作为本期数值依据。',relevant:false},{id:'vendor',title:'供应商介绍',size:300,desc:'背景信息，不参与金额计算。',relevant:false}];
export default function ModelLab(){const[model,setModel]=useState<keyof typeof models>('balanced');const[temp,setTemp]=useState(.7);const[topP,setTopP]=useState(.9);const[maxTokens,setMaxTokens]=useState(256);const[topK,setTopK]=useState(3);const[budget,setBudget]=useState(1200);const[retrieval,setRetrieval]=useState(true);const[prompt,setPrompt]=useState('请汇总本月示例采购发票金额，说明统计范围并引用单据。');const[seed,setSeed]=useState(1);const[output,setOutput]=useState('');const[selectedCandidate,setCandidate]=useState<number|null>(null);const[stamp,setStamp]=useState('');
const included=useMemo(()=>{let used=0;return retrieval?docs.slice(0,topK).filter(d=>{if(used+d.size>budget)return false;used+=d.size;return true}):[]},[retrieval,topK,budget]);const used=included.reduce((s,d)=>s+d.size,0);const grounded=included.some(d=>d.id==='invoice')&&included.some(d=>d.id==='metric')&&included.some(d=>d.id==='acl');const probs=candidateDistribution(temp,topP,grounded);const total=invoices.reduce((sum,r)=>sum+r.invoiceAmount,0);
const candidates=grounded?['结构化、附明细范围','简短、先结论后引用','面向业务的解释','建议先检查异常单据']:['请求补充指标与权限','指出缺少可靠金额依据','建议接入授权发票数据','给出查询前的检查清单'];
function run(){let val=(((seed*1664525+1013904223)>>>0)%100000)/100000;let index=0,c=0;for(let i=0;i<probs.length;i++){c+=probs[i];if(val<c){index=i;break}}const questionSupported=/金额|采购|发票|应付/.test(prompt);let answer='';if(!questionSupported)answer='此教学场景支持采购发票汇总。请围绕示例发票金额、口径或引用提问；真实模型需要单独评测其他任务。';else if(!grounded)answer=['需要补充：统计口径、当期授权发票明细和访问权限。当前上下文不足，我不能给出可靠金额。','当前上下文不能同时证明金额口径、当期数据和权限。请增加 Top K 或上下文预算，先补齐依据。','请接入授权发票数据，并确认金额为未税 CNY。没有完整依据时，我会请求澄清。','查询前检查：① 法人权限 ② 开票金额口径 ③ 本期发票明细。当前仍有缺失，暂不返回数值。'][index];else answer=[`本月示例采购发票合计 ${money(total)}。\n范围：法人 A，2026-09，6 张发票，CNY，未税。\n依据：INV-260901 至 INV-260906；金额来自示例明细的确定性求和。\n提醒：这里统计开票金额，不等于已审批付款金额。`,`合计 ${money(total)}，共 6 张 CNY 未税发票。\n来源：INV-260901—INV-260906。\n口径：开票金额；异常和审批状态需另查。`,`从经营视角看，本期示例开票金额为 ${money(total)}。其中工业控制器发票为 ${money(150000)}。\n这些金额包含待核对和待审批单据，不能直接当作可付款余额。\n来源：6 张授权示例发票。`,`6 张示例发票共计 ${money(total)}。建议先核对数量与单价差异，并完成大额审批，再进入后续财务处理。\n数据范围：法人 A / 2026-09 / CNY 未税。来源：INV-260901—INV-260906。`][index];const cap=Math.floor(maxTokens*1.5);if(answer.length>cap)answer=answer.slice(0,cap)+'\n[达到模拟输出预算，内容截断]';setOutput(answer);setCandidate(index);setStamp(`种子 ${seed} · T=${temp.toFixed(1)} · Top P=${topP.toFixed(2)} · ${included.length} 段上下文`);setSeed(seed+1)}
function reset(){setModel('balanced');setTemp(.7);setTopP(.9);setMaxTokens(256);setTopK(3);setBudget(1200);setRetrieval(true);setOutput('');setCandidate(null);setSeed(1)}
return <><StudioHeading eyebrow="MODEL PLAYGROUND" title="模型实验室" desc="参数改变了什么？用可解释的教学模型，观察采样分布、上下文组成与回答变化。" simulation/>
<div className="model-workspace"><aside className="model-controls"><div className="panel-heading"><SlidersHorizontal size={19}/><h3>模型与参数</h3><button aria-label="重置模型参数" onClick={reset}><RotateCcw size={17}/></button></div><Select value={model} onValueChange={v=>setModel(v as keyof typeof models)}><SelectTrigger aria-label="模拟模型类型"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(models).map(([k,m])=><SelectItem value={k} key={k}>{m.label}</SelectItem>)}</SelectContent></Select>
<Range title="Temperature" value={temp} min={0} max={2} step={.1} display={temp.toFixed(1)} desc="重新分配候选概率；数值低时更集中，并不保证事实正确。" onChange={setTemp}/><Range title="Top P" value={topP} min={.1} max={1} step={.05} display={topP.toFixed(2)} desc="按累计概率保留候选，再重新归一化。" onChange={setTopP}/><Range title="输出预算" value={maxTokens} min={64} max={512} step={32} display={`${maxTokens} 模拟 token`} desc="本演示按字符估算长度，未使用真实模型分词器。" onChange={setMaxTokens}/><div className="switch-row"><label htmlFor="retrieval-toggle">启用检索上下文</label><Switch id="retrieval-toggle" checked={retrieval} onCheckedChange={setRetrieval}/></div><Range title="Top K 检索段数" value={topK} min={1} max={6} step={1} display={`${topK} 段`} desc="增加段数可能引入无关内容，不是越多越好。" onChange={setTopK}/><Range title="上下文预算" value={budget} min={200} max={2400} step={100} display={`${budget} 模拟 token`} desc="按相关性顺序装入；超出预算的资料跳过。" onChange={setBudget}/></aside>
<div className="model-main"><section className="prompt-console"><div className="panel-heading"><Sparkles size={19}/><h3>对话与结果</h3><span className="small-tag">规则生成 · 无 API 调用</span></div><label htmlFor="model-prompt">用户提示词</label><Textarea id="model-prompt" value={prompt} onChange={e=>setPrompt(e.target.value)} rows={3}/><div className="prompt-action"><button onClick={()=>setPrompt('请汇总本月示例采购发票金额，说明统计范围并引用单据。')}>载入示例问题</button><Button onClick={run}><Play size={16}/>生成模拟回答</Button></div><div className="model-answer" aria-live="polite"><span className="answer-label"><span className="bot-avatar"><Sparkles size={17}/></span>实验助手 {stamp&&<small>{stamp}</small>}</span><p>{output||'点击生成，然后关闭检索或把 Top K 改为 2。观察信息不足时，系统为什么应当先请求澄清。'}</p></div></section>
<section className="distribution-panel"><div className="panel-heading"><h3>候选回答的采样概率</h3><span className="small-tag">教学分布</span></div><div className="probability-bars">{probs.map((p,i)=><div key={i} className={selectedCandidate===i?'sampled':''}><span>{candidates[i]}{selectedCandidate===i&&<Check size={14}/>}</span><div><i style={{width:`${p*100}%`}}/></div><b>{(p*100).toFixed(1)}%</b></div>)}</div><p className="fine-print">用固定教学分数经过温度缩放和 Top P 截断计算，并非真实模型的 token 概率。同样参数下，重复运行会用新的模拟种子采样。</p></section>
<div className="simulation-metrics"><div><span>已装入上下文</span><strong>{used}<small> / {budget}</small></strong></div><div><span>依据完整性</span><strong className={grounded?'text-success':'text-warning'}>{grounded?'可回答':'需补充'}</strong></div><div><span>相对计算预算</span><strong>{((used+maxTokens)/1000*models[model].factor).toFixed(2)}<small> 单位</small></strong></div></div><p className="micro-note">预算为输入与输出长度乘教学倍率，仅帮助理解取舍，不代表真实费用、延迟或模型能力。</p></div>
<aside className="context-inspector"><div className="panel-heading"><Database size={19}/><h3>上下文清单</h3></div><div className="budget-track"><i style={{width:`${Math.min(100,used/budget*100)}%`}}/></div><p className="context-usage">{used} / {budget} 模拟 token</p>{docs.map((d,i)=>{const active=included.some(x=>x.id===d.id);return <div className={`context-document ${active?'included':''}`} key={d.id}><span>{active?<Check size={14}/>:i+1}</span><div><h4>{d.title}</h4><p>{d.desc}</p><small>{d.size} token · {active?'已装入':!retrieval?'检索关闭':i>=topK?'超出 Top K':'超出预算'}</small></div></div>})}<div className="learning-note"><Info size={18}/><p>“上下文工程”决定给模型什么信息；“采样参数”决定如何从候选中选择。两者解决不同问题。</p></div></aside></div><a className="bottom-next" href="/learn?lesson=context">回到课堂：理解上下文工程 <ArrowRight size={17}/></a></>}
export function Range({title,value,min,max,step,display,desc,onChange}:{title:string,value:number,min:number,max:number,step:number,display:string,desc?:string,onChange:(n:number)=>void}){return <div className="parameter-range"><label>{title}<strong>{display}</strong></label><Slider aria-label={title} value={[value]} min={min} max={max} step={step} onValueChange={v=>onChange(v[0])}/>{desc&&<p>{desc}</p>}</div>}
