"use client";
import {useLearningLocation,replaceLearningUrl} from '@/lib/learning-location';
import {lazy,Suspense,useState,useEffect} from 'react';
import {Network,Factory,Truck,Warehouse,Layers,ChartNoAxesCombined,ArrowRight,ShieldCheck,RotateCcw,BookOpen,Check,ExternalLink,GitBranch} from 'lucide-react';
import {Button} from '@/components/ui/button';import {Slider} from '@/components/ui/slider';import {Input} from '@/components/ui/input';import {Select,SelectTrigger,SelectContent,SelectItem,SelectValue} from '@/components/ui/select';import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import reading from '@/lib/ontology-reading.json';
import {SmallTable} from './experience-shared';
import {spatialNodes,spatialEdges,delayScenario} from '@/lib/spatial-data';
import {Switch} from '@/components/ui/switch';
import type {RelationScope} from '@/lib/spatial-layout';
const SpatialRelationshipMap=lazy(()=>import('./spatial-relationship-map'));
const OperationsLab=lazy(()=>import('./operations-lab'));
const SpatialScene=lazy(()=>import('./spatial-scene'));
const concepts=[['对象 Object','同一个业务实体有稳定身份','供应商 SUP-01、采购单 PO-1001 与卷材 M-01 是不同对象。换了显示名称，主键身份仍应保持一致。'],['属性 Property','先统一数值的业务含义','库存 60 吨属于物料 M-01、原料仓 WH-01 与同一快照时点。“60”如果没有单位、位置与时间就无法参与可靠计算。'],['关系 Link','沿着关联找到受影响对象','供应商 → 采购单 → 物料 → 库存 → 产线 → 客户订单。关系提供追踪路径；是否造成延误还要运行业务规则。'],['行动 Action','把建议变成受约束的业务操作','“追加采购”需要合格供应商、预算和审批。可执行动作不是聊天文本，必须明确输入校验、权限、审计与回退。'],['证据与版本','让每个结论有可追溯依据','记录库存快照、承诺日期、耗用量、规则版本。规则改变后，重新计算并保留旧结果，避免把不同口径混在一起。'],['本体与知识图谱','一个约定语义，一个组织关联','本体约定对象类型、属性与关系含义；知识图谱承载具体对象及关系。3D 是展示方式，企业 Ontology 还可结合权限和动作，不能把连线图当成完整系统。']];
function ErpOntologyLab(){const[mode,setMode]=useState<'graph'|'factory'|'chart'>('graph');const[selected,setSelected]=useState('material');const[graphView,setGraphView]=useState('flat');const[scope,setScope]=useState<RelationScope>('related');const[delay,setDelay]=useState(0);const[role,setRole]=useState('planner');const[budget,setBudget]=useState(50000);const[applied,setApplied]=useState(false);const[proposal,setProposal]=useState(false);const[tab,setTab]=useState('objects');const[layer,setLayer]=useState(2);const[hasEvidence,setEvidence]=useState(false);const[log,setLog]=useState('');const result=delayScenario(delay,applied);const node=spatialNodes.find(n=>n.id===selected)!;const related=spatialEdges.filter(e=>e[0]===selected||e[1]===selected);const canApprove=role==='manager'&&budget>=18000&&result.shortage>0;function resetAction(){setApplied(false);setProposal(false);setLog('')}return <>
<div className="ops-erp-intro"><span className="ops-eyebrow">ERP / ONTOLOGY</span><h2>一张采购单，怎样影响最终交付？</h2><p>先沿关系看懂业务，再进入 3D 现场；调整供货延迟，验证库存能缓冲多久。</p></div>
<div className="spatial-modebar"><Tabs value={mode} onValueChange={v=>setMode(v as typeof mode)}><TabsList><TabsTrigger value="graph"><Network size={17}/>对象关系</TabsTrigger><TabsTrigger value="factory"><Factory size={17}/>3D 工厂现场</TabsTrigger><TabsTrigger value="chart"><ChartNoAxesCombined size={17}/>3D 情景图表</TabsTrigger></TabsList></Tabs><span>{mode==='chart'?'蓝色：基线 · 橙色：当前情景 · 单位：天':'10 个业务对象 · 12 条有向关系'}</span></div>
{mode==='graph'&&<div className="relationship-toolbar"><Tabs value={graphView} onValueChange={setGraphView}><TabsList><TabsTrigger value="flat">清晰关系图</TabsTrigger><TabsTrigger value="spatial">3D 探索</TabsTrigger></TabsList></Tabs><label><Switch checked={scope==='related'} onCheckedChange={v=>setScope(v?'related':'all')} aria-label="聚焦当前对象的关系"/>聚焦当前对象</label><span>{scope==='related'?'点击对象追踪关联，详情区可切换对象':'展示全部关系'}</span></div>}
<div className="spatial-layout spatial-readable"><Suspense fallback={<div className="spatial-fallback">正在加载 3D 实验…</div>}>{mode==='graph'&&graphView==='flat'?<SpatialRelationshipMap selected={selected} onSelect={setSelected} scope={scope} delay={delay} expedite={applied}/>:<SpatialScene mode={mode} selected={selected} onSelect={setSelected} delay={delay} expedite={applied} scope={scope}/>}</Suspense><aside className="object-inspector"><span className="eyebrow">对象与关系</span><label>点选对象或从列表选择</label><Select value={selected} onValueChange={setSelected}><SelectTrigger aria-label="选择业务对象"><SelectValue/></SelectTrigger><SelectContent>{spatialNodes.map(n=><SelectItem value={n.id} key={n.id}>{n.name}</SelectItem>)}</SelectContent></Select><span className="small-tag" style={{color:node.color,background:'#153344'}}>{node.type}</span><h2>{node.name}</h2><dl>{node.properties.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className="object-evidence"><ShieldCheck size={17}/><p>{node.evidence}</p></div><h3>关联对象</h3>{related.map(([a,b,label])=>{const id=a===selected?b:a;return <button className="relation-link" key={a+b} onClick={()=>setSelected(id)}><span>{a===selected?'→':'←'} {label}</span><strong>{spatialNodes.find(n=>n.id===id)!.name}</strong></button>})}</aside></div>
<div className="scenario-console"><div className="scenario-controls"><div><span className="eyebrow">WHAT IF / 供货延迟实验</span><h2>供应商晚到，客户就一定晚收吗？</h2><p>先看库存缓冲，再计算缺料影响。连线负责找到对象，业务规则负责推算结果。</p></div><label>供货额外延迟 <strong>{delay} 天</strong><Slider aria-label="供货额外延迟天数" min={0} max={8} step={1} value={[delay]} onValueChange={v=>{setDelay(v[0]);resetAction()}}/></label><Button variant="outline" onClick={()=>{setDelay(0);resetAction()}}><RotateCcw size={16}/>重置情景</Button></div><div className="scenario-metrics"><div><span>原料覆盖</span><strong>3<small>天</small></strong><p>60 吨 ÷ 20 吨/天</p></div><div><span>预计到货</span><strong>第 {result.arrival}<small>天</small></strong><p>原第 2 天 + 延迟 {delay} 天</p></div><div className={result.netShortage>0?'at-risk':''}><span>缺料停工</span><strong>{result.netShortage}<small>天</small></strong><p>{applied?'加急方案恢复最多 2 天':'max(0, 到货日 − 3)'}</p></div><div><span>客户预计送达</span><strong>第 {result.delivery}<small>天</small></strong><p>基线第 10 天 + 停工天数</p></div></div><div className="scenario-message" role="status"><GitBranch size={21}/><p>{result.shortage===0?'库存缓冲覆盖本次延迟，客户送达日期不变。供应风险不等于必然履约延误。':`影响路径：采购单 → 原料库存 → 精加工产线 → 客户订单 → 出货物流。${applied?'已模拟加急补料，停工影响降低。':'可以生成处置方案，等待有权限的角色审批。'}`}</p></div></div>
<Tabs value={tab} onValueChange={setTab} className="explorer-tabs"><TabsList variant="line"><TabsTrigger value="objects">理论与具象例子</TabsTrigger><TabsTrigger value="architecture">工程落地</TabsTrigger><TabsTrigger value="actions">动作与审批</TabsTrigger><TabsTrigger value="evidence">关系与计算证据</TabsTrigger></TabsList></Tabs>
{tab==='objects'&&<div className="ontology-concepts">{concepts.map(([title,lead,text],i)=><article key={title}><span className="concept-index">0{i+1}</span><h3>{title}</h3><strong>{lead}</strong><p>{text}</p></article>)}</div>}
{tab==='architecture'&&<><div className="v3-panel semantic-layout"><div className="semantic-layers">{reading.productionArchitecture.planes.map((p,i)=><button className={layer===i?'active':''} key={p.name} onClick={()=>setLayer(i)}>{String(i+1).padStart(2,'0')} / {p.name}</button>)}</div><div className="semantic-text"><span className="eyebrow">从业务含义到规模计算</span><h3>{reading.productionArchitecture.planes[layer].name}</h3><p>{reading.productionArchitecture.planes[layer].components}</p><p>{reading.productionArchitecture.narrative}</p><div className="semantic-quote">{reading.implementationNuances[layer]}</div><small className="case-citation">用户方案 PDF · 第 7–10、16–17、20、22 页；Palantir / W3C 原文见下方。</small></div></div><div className="v3-panel" style={{marginTop:20}}><h3>缺少资质记录，意味着“没有资质”吗？</h3><p>开放世界语义下，没有记录只能说明未知。业务执行规则可以要求必须先取得有效资质证据。</p><div className="inline-options"><Button variant={hasEvidence?'outline':'default'} onClick={()=>setEvidence(false)}>未提供资质证据</Button><Button variant={hasEvidence?'default':'outline'} onClick={()=>setEvidence(true)}>已提供有效资质证据</Button></div><div className="semantic-quote">{hasEvidence?'知识结论：有有效证据支持。执行检查：资质这一条件满足，但预算、库存、版本与审批仍需分别校验。':'知识结论：资质状态未知，不能断言供应商无资质。执行检查：证据不足，禁止自动向该供应商下单。'}</div><small className="case-citation">W3C OWL 2 Primer 的开放世界假设；“缺证不执行”是本实验的运营控制规则。</small></div><SmallTable headers={['层次','主要回答','业务例子']} rows={reading.comparison.map(c=>[c.name,c.answers,c.example])}/></>}
{tab==='actions'&&<div className="ontology-action-panel"><section><span className="eyebrow">ACTION / 提交加急补料</span><h2>同一条建议，不同角色有不同权限</h2><p>演示方案：向合格备选供应商加急补料，额外成本 18,000 元，最多恢复 2 天生产。此处仅改变实验状态。</p><label>当前角色<Select value={role} onValueChange={v=>{setRole(v);setProposal(false);setLog('')}}><SelectTrigger aria-label="操作角色"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="viewer">只读观察员</SelectItem><SelectItem value="planner">计划员 · 可提案</SelectItem><SelectItem value="manager">采购经理 · 可审批</SelectItem></SelectContent></Select></label><label>可用演示预算（元）<Input aria-label="可用演示预算" type="number" min={0} value={budget} onChange={e=>{setBudget(Math.max(0,Number(e.target.value)));setProposal(false);setLog('')}}/></label><Button disabled={applied||role==='viewer'||result.shortage===0} onClick={()=>{setProposal(true);setLog('方案已生成，尚未执行。切换采购经理后可重新生成并审批。')}}>生成处置方案 <ArrowRight size={16}/></Button></section><section className="action-receipt"><h3>执行前置条件</h3>{[['存在缺料影响',result.shortage>0],['具备采购经理权限',role==='manager'],['预算覆盖 18,000 元',budget>=18000],['备选供应商已核准（假设）',true]].map(([t,v])=><div className={`precondition ${v?'met':''}`} key={String(t)}><Check size={16}/><span>{t}</span><strong>{v?'满足':'未满足'}</strong></div>)}{proposal&&<><div className="pending-action"><strong>待审方案 / EXPEDITE-01</strong><p>补充交付证据、记录操作角色和规则版本，批准后才更新模拟计划。</p></div><Button disabled={!canApprove||applied} onClick={()=>{setApplied(true);setLog('已由采购经理批准模拟方案；生成审计记录 DEMO-A01。没有向业务系统写入。')}}>批准并应用到本次实验</Button></>}{applied&&<p className="action-applied"><Check size={18}/>已应用 · 额外成本 ¥18,000 · 版本 v2</p>}{log&&<p className="action-log" role="status">{log}</p>}</section></div>}
{tab==='evidence'&&<div className="evidence-grid"><section className="v3-panel"><h3>同一组对象，不同情景</h3><Table><TableHeader><TableRow><TableHead>指标 / 单位：天</TableHead><TableHead>基线</TableHead><TableHead>当前情景</TableHead></TableRow></TableHeader><TableBody>{[['到货日',2,result.arrival],['缺料天数',0,result.netShortage],['完工日',8,result.completion],['送达日',10,result.delivery]].map(([n,a,b])=><TableRow key={n}><TableCell>{n}</TableCell><TableCell>{a}</TableCell><TableCell>{b}</TableCell></TableRow>)}</TableBody></Table><p>到货立即可用；每天均匀耗用；缺料使计划等量顺延；运输 2 天；未考虑其他瓶颈。上述均为教学模型假设。</p></section><section className="v3-panel"><h3>当前对象的关系证据</h3>{related.map(([a,b,t])=><p className="edge-evidence" key={a+b}>{spatialNodes.find(n=>n.id===a)!.name}<strong>{t} →</strong>{spatialNodes.find(n=>n.id===b)!.name}</p>)}<p>图上可达只意味着存在关联；影响方向、时间和程度必须由规则、数据和验证共同决定。</p></section></div>}
<div className="v3-source-note"><BookOpen size={20}/><div><strong>研究依据与阅读路径</strong><p>依据用户提供的《Ontology 驱动的可信智能问数与工业供应链 AI 方案》第 7–12、16–18、22–23 页归纳。本站实现为业务语义与规则演示，未接入完整 OWL/RDF 推理平台；3D 场景使用独立合成数据。</p><div className="source-inline"><a href="https://www.palantir.com/docs/foundry/ontology/overview/" target="_blank" rel="noopener noreferrer">Palantir Ontology 概览 <ExternalLink size={14}/></a><a href="https://www.w3.org/TR/owl2-overview/" target="_blank" rel="noopener noreferrer">W3C OWL 2 <ExternalLink size={14}/></a><a href="https://www.w3.org/TR/owl2-primer/" target="_blank" rel="noopener noreferrer">OWL 2 开放世界语义 <ExternalLink size={14}/></a><a href="https://www.w3.org/TR/shacl/" target="_blank" rel="noopener noreferrer">SHACL 数据校验 <ExternalLink size={14}/></a><a href="/projects">项目与产品案例 <ArrowRight size={14}/></a></div></div></div>
</>}

const spatialCases=[
 {id:'erp',icon:Network,code:'ERP',name:'供货与履约',description:'库存缓冲 · 本体关联',color:'blue'},
 {id:'mes',icon:Factory,code:'MES',name:'生产与改派',description:'产线停机 · 质量交付',color:'purple'},
 {id:'tms',icon:Truck,code:'TMS',name:'运输与调度',description:'拥堵绕行 · 运力检查',color:'orange'},
 {id:'wms',icon:Warehouse,code:'WMS',name:'仓储与拣选',description:'合并波次 · 库位优化',color:'green'},
] as const;
export default function OntologyLab(){
 const[current,setCurrent]=useState<'erp'|'mes'|'tms'|'wms'>('erp');
 useLearningLocation('/ontology',params=>{const id=params.get('case');setCurrent(spatialCases.some(c=>c.id===id)?id as typeof current:'erp')});
 function choose(id:typeof current){setCurrent(id);replaceLearningUrl(`/ontology?case=${id}`)}
 return <div className="supplychain-worlds"><header className="worlds-heading"><div><span className="ops-eyebrow"><Layers size={16}/>FOUR SYSTEMS. ONE SUPPLY CHAIN.</span><h1>让业务决策，<span>在 3D 里发生。</span></h1><p>从订单、车间到仓库与运输。换一个条件，看看哪些对象受影响，哪种方案值得采用。</p></div><span className="worlds-simulation"><span/>交互模拟 · 合成数据</span></header><nav className="worlds-cases" aria-label="选择供应链三维案例">{spatialCases.map(c=><button key={c.id} onClick={()=>choose(c.id)} aria-pressed={current===c.id} className={`${c.color} ${current===c.id?'active':''}`}><span className="worlds-case-icon"><c.icon size={25}/></span><span><small>{c.code}</small><strong>{c.name}</strong><span>{c.description}</span></span><ArrowRight size={16}/></button>)}</nav><div className="worlds-case-content" key={current}>{current==='erp'?<ErpOntologyLab/>:<Suspense fallback={<div className="v3-loading">正在准备业务场景…</div>}><OperationsLab kind={current}/></Suspense>}</div></div>
}
