"use client";
import {lazy,Suspense,useEffect,useMemo,useRef,useState} from 'react';
import {ArrowRight,ArrowUpRight,BookOpen,Check,ChevronDown,Factory,GitBranch,Info,PackageCheck,Pause,Play,RotateCcw,ShieldCheck,Sparkles,Truck,Warehouse} from 'lucide-react';
import {simulateMes,simulateTms,simulateWms,mesDefault,tmsDefault,wmsDefault,skuNames,operationSources,type OperationKind,type MesInput,type TmsInput,type WmsInput} from '@/lib/operations-simulation';
const Scene=lazy(()=>import('./operations-scene'));
const caseInfo={mes:{icon:Factory,eyebrow:'MANUFACTURING EXECUTION',title:'产线停了，工单能否如期交付？',desc:'在卷材加工车间，调整停机时间和订单量，比较等待恢复与备用产线改派。'},tms:{icon:Truck,eyebrow:'TRANSPORTATION MANAGEMENT',title:'绕远一点，能不能准时送达？',desc:'在配送中心与客户工厂之间，比较主路与绕行路线，再检查车辆是否真的装得下。'},wms:{icon:Warehouse,eyebrow:'WAREHOUSE MANAGEMENT',title:'同一批订单，能少走多少路？',desc:'把逐单拣货改成合并波次，再将高频物料前置，观察路线和作业时间的变化。'}};
const fmt=(n:number,d=1)=>Number(n.toFixed(d)).toLocaleString('zh-CN');const hours=(n:number)=>`${Math.floor((8*60+Math.round(n*60))/60).toString().padStart(2,'0')}:${((8*60+Math.round(n*60))%60).toString().padStart(2,'0')}`;
function Range({label,value,min,max,step=1,unit,onChange}:{label:string;value:number;min:number;max:number;step?:number;unit:string;onChange:(n:number)=>void}){return <label className="ops-range"><span>{label}<strong>{value} {unit}</strong></span><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/><small><span>{min} {unit}</span><span>{max} {unit}</span></small></label>}
export default function OperationsLab({kind}:{kind:OperationKind}){
 const[mes,setMes]=useState<MesInput>(mesDefault),[tms,setTms]=useState<TmsInput>(tmsDefault),[wms,setWms]=useState<WmsInput>(wmsDefault),[progress,setProgress]=useState(0),[playing,setPlaying]=useState(false),[selected,setSelected]=useState(kind==='mes'?'line-a':kind==='tms'?'fleet':'A');
 const area=useRef<HTMLElement>(null),visible=useRef(true);
 const m=useMemo(()=>simulateMes(mes),[mes]),t=useMemo(()=>simulateTms(tms),[tms]),w=useMemo(()=>simulateWms(wms),[wms]);
 const mb=useMemo(()=>simulateMes({...mes,strategy:'wait'}),[mes]),tb=useMemo(()=>simulateTms({...tms,strategy:'direct'}),[tms]),wb=useMemo(()=>simulateWms({...wms,strategy:'single',forward:false}),[wms]);
 const ma=useMemo(()=>simulateMes({...mes,strategy:'reroute'}),[mes]),ta=useMemo(()=>simulateTms({...tms,strategy:'detour'}),[tms]);
 const horizon=kind==='mes'?Math.max(8,m.finish):kind==='tms'?t.eta:w.seconds,elapsed=progress/100*horizon;
 useEffect(()=>{const observer=new IntersectionObserver(([e])=>{visible.current=e.isIntersecting});if(area.current)observer.observe(area.current);return()=>observer.disconnect()},[]);
 useEffect(()=>{if(!playing)return;let last=performance.now();const timer=setInterval(()=>{const now=performance.now();if(visible.current&&!document.hidden)setProgress(p=>Math.min(100,p+(now-last)/200));last=now},80);return()=>clearInterval(timer)},[playing]);
 useEffect(()=>{if(progress>=100)setPlaying(false)},[progress]);
 function change(){setPlaying(false);setProgress(0)}
 function updateMes(v:Partial<MesInput>){setMes({...mes,...v});change()}function updateTms(v:Partial<TmsInput>){setTms({...tms,...v});change()}function updateWms(v:Partial<WmsInput>){setWms({...wms,...v});change()}
 function reset(){setMes(mesDefault);setTms(tmsDefault);setWms(wmsDefault);change()}
 const production=m.productionAt(Math.max(0,elapsed-.5));
 const mesStatus=elapsed>=m.finish?'工单完成 · 已通过模拟质检':elapsed>=Math.max(m.aFinish,m.bFinish)?'最后一批质检中':elapsed>=2&&elapsed<2+m.down&&m.aQty>50?`A 线停机${m.bQty?' · B 线承接部分工单':' · 等待恢复'}`:'生产执行中';
 const status=kind==='mes'?mesStatus:kind==='tms'?t.statusAt(elapsed):w.stateAt(elapsed).status;
 const objects=kind==='mes'?[
  {id:'order',name:'生产工单',code:'MES-WO-180',facts:[['需求量',`${m.demand} 吨`],['班次','08:00 — 16:00'],['上游对象','ERP 销售订单 SO-180']],note:'订单量映射到生产工单。这里不拆分交期，也不考虑多规格换型。'},
  {id:'line-a',name:'加工 A 线',code:'MES-LINE-A',facts:[['加工能力','25 吨 / 小时'],['分配数量',`${fmt(m.aQty)} 吨`],['停机窗口',`${hours(2)} — ${hours(2+m.down)}`]],note:'10:00 发生设备事件；停机占用生产时间。恢复后继续未完成的数量。'},
  {id:'line-b',name:'备用 B 线',code:'MES-LINE-B',facts:[['加工能力','15 吨 / 小时'],['改派数量',`${fmt(m.bQty)} 吨`],['开工时间',m.bQty?'10:30（含准备）':'未启用']],note:'假设 B 线空闲、工艺与资质均匹配；改派需要 30 分钟准备，并产生额外费用。'},
  {id:'quality',name:'质量检验',code:'MES-QC-01',facts:[['每批检验','固定 30 分钟'],['质量假设','全部通过（未模拟不良品）'],['回放已检数量',`${fmt(production.a+production.b)} 吨`]],note:'按批次加工后进入检验。这里的可交付数量已扣除检验所需时间。'},
  {id:'finished',name:'成品暂存',code:'WMS-FG-01',facts:[['班末可交付',`${fmt(m.readyTons)} 吨`],['未按班末交付',`${fmt(m.shortfall)} 吨`],['全部完工',hours(m.finish)]],note:'MES 将合格产出移交 WMS。全部完工时间与班末可交付数量是两个不同指标。'}
 ]:kind==='tms'?[
  {id:'depot',name:'配送中心',code:'WMS-DOCK-01',facts:[['待运重量',`${t.demand} 吨`],['装车耗时','30 分钟'],['出发时点','08:30（运力满足时）']],note:'WMS 提供已备货数量，TMS 校验运力后生成运输计划。本例为同一目的地的一次发运。'},
  {id:'fleet',name:'运输车辆',code:'TMS-FLEET-01',facts:[['车辆数量',`${t.trucks} 辆`],['单车载重','10 吨'],['尚缺运力',`${fmt(t.unallocated)} 吨`]],note:t.feasible?'按重量校验通过；演示忽略体积、驾驶时长和车型限制。':'运力不足时，整批计划不发车。先补足车辆，再比较路线。'},
  {id:'junction',name:'主路拥堵点',code:'TMS-EVENT-01',facts:[['主路距离','180 km'],['附加等待',`${tms.congestion} 分钟`],['备用距离','240 km']],note:'拥堵发生在主路中段。备用道路在此情景中不受影响；路网是示意图，里程取业务字段。'},
  {id:'customer',name:'客户工厂',code:'ERP-CUSTOMER-01',facts:[['交付截止','13:00'],['预计完成',t.feasible?hours(t.eta):'待补足运力'],['卸货耗时','15 分钟']],note:'以完成卸货作为交付节点。ETA 包含装车、行驶、拥堵等待与卸货。'}
 ]:[
  ...Object.keys(skuNames).map(id=>({id,name:`${id} · ${skuNames[id]}`,code:`WMS-SKU-${id}`,facts:[['本波次需求',`${w.quantities[id]} 箱`],['库位坐标',`(${w.locations[id].join(', ')})`],['当前布局',wms.forward&&['A','C'].includes(id)?'高频物料前置':'标准库位']],note:'同一 SKU 的订单可合并拣取；拣货后仍须按订单分拣和复核。每箱是本例的需求单位。'})),
  {id:'inventory',name:'存储货架',code:'WMS-LOCATIONS',facts:[['通行规则','纵向巷道 + 前后横向通道'],['场景比例','1 坐标单位 = 2 米'],['行走速度','1 米 / 秒']],note:'路线必须沿通道行走，不能穿越货架。小样本枚举访问顺序，不代表工业规模最优调度器。'},
  {id:'packing',name:'集货与复核',code:'WMS-WAVE-01',facts:[['本波次订单',`${w.count} 单 / ${w.count} 箱`],['打包复核',`${w.count*30} 秒`],['拣货访问',`${w.visits} 次`]],note:'每单复核打包 30 秒，波次合并不会省略该步骤。高频库位调整忽略一次性搬迁成本。'}
 ];
 const object=objects.find(o=>o.id===selected)||objects[0];const info=caseInfo[kind],source=operationSources[kind];
 const metrics=kind==='mes'?[
  {label:'全部完工',value:hours(m.finish),sub:`等待方案 ${hours(mb.finish)}`,risk:m.late>0},
  {label:'班末可交付',value:`${fmt(m.readyTons)} 吨`,sub:`需求 ${m.demand} 吨`,risk:m.shortfall>0},
  {label:'超过班末',value:`${fmt(m.late*60,0)} 分钟`,sub:'班次截止 16:00',risk:m.late>0},
  {label:'改派附加费用',value:`¥${fmt(m.cost,0)}`,sub:'教学费用，不含原加工费',risk:false}
 ]:kind==='tms'?[
  {label:'预计交付完成',value:t.feasible?hours(t.eta):'待补车',sub:'交付截止 13:00',risk:!t.feasible||t.late>0},
  {label:'计划里程 / 车',value:`${t.distance} km`,sub:`平均行驶速度 60 km/h`,risk:false},
  {label:'载重占用',value:`${fmt(t.loadRate,0)}%`,sub:t.feasible?`${t.demand} / ${t.capacity} 吨`:`缺少 ${fmt(t.unallocated)} 吨运力`,risk:!t.feasible},
  {label:'计划运输费用',value:`¥${fmt(t.cost,0)}`,sub:'未执行 · 仅方案估算',risk:false}
 ]:[
  {label:'预计行走距离',value:`${fmt(w.meters,0)} 米`,sub:`逐单标准库位 ${fmt(wb.meters,0)} 米`,risk:false},
  {label:'作业总时长',value:`${fmt(w.seconds/60)} 分钟`,sub:'包括拣取、复核和打包',risk:false},
  {label:'货位访问次数',value:`${w.visits} 次`,sub:`${w.count} 单 / ${w.count} 箱`,risk:false},
  {label:'较基线节省行走',value:`${fmt(wb.meters-w.meters,0)} 米`,sub:`时间节省 ${fmt((wb.seconds-w.seconds)/60)} 分钟`,risk:false}
 ];
 const comparison=kind==='mes'?[['全部完工',hours(mb.finish),hours(m.finish)],['班末合格数量',`${fmt(mb.readyTons)} 吨`,`${fmt(m.readyTons)} 吨`],['分配到 B 线','0 吨',`${fmt(m.bQty)} 吨`],['改派附加费用','¥0',`¥${fmt(m.cost,0)}`]]:kind==='tms'?[['计划距离 / 车',`${tb.distance} km`,`${t.distance} km`],['预计交付',t.feasible?hours(tb.eta):'运力不足',t.feasible?hours(t.eta):'运力不足'],['运输费用',`¥${fmt(tb.cost,0)}`,`¥${fmt(t.cost,0)}`],['车辆数',`${t.trucks} 辆`,`${t.trucks} 辆`]]:[['行走距离',`${fmt(wb.meters,0)} 米`,`${fmt(w.meters,0)} 米`],['货位访问',`${wb.visits} 次`,`${w.visits} 次`],['拣选 + 回库',`${fmt(wb.pickingSeconds/60)} 分钟`,`${fmt(w.pickingSeconds/60)} 分钟`],['作业总时长',`${fmt(wb.seconds/60)} 分钟`,`${fmt(w.seconds/60)} 分钟`]];
 return <section className={`operations-lab ops-${kind}`} ref={area}><div className="ops-intro"><div><span className="ops-eyebrow">{info.eyebrow}</span><h2>{info.title}</h2><p>{info.desc}</p></div><button className="ops-reset" onClick={reset}><RotateCcw size={15}/>重置案例</button></div>
 <div className="ops-workspace"><div className="ops-world"><Suspense fallback={<div className="ops-viewport"><div className="ops-loading">正在加载场景…</div></div>}><Scene kind={kind} mes={mes} tms={tms} wms={wms} progress={progress} selected={object.id} onSelect={setSelected}/></Suspense><div className="ops-playback"><div className="ops-playback-top"><button disabled={kind==='tms'&&!t.feasible} onClick={()=>{if(progress>=100)setProgress(0);setPlaying(!playing)}} aria-label={playing?'暂停业务回放':'播放业务回放'}>{playing?<Pause size={15}/>:<Play size={15}/>} {playing?'暂停':'播放过程'}</button><strong>{kind==='wms'?`${fmt(elapsed/60)} 分钟`:hours(elapsed)}</strong><span>{status}</span></div><input type="range" aria-label="业务回放进度" min={0} max={100} step={.5} value={progress} disabled={kind==='tms'&&!t.feasible} onChange={e=>{setProgress(Number(e.target.value));setPlaying(false)}}/><div className="ops-playback-bottom"><span>{kind==='wms'?'开始拣货':'08:00 开始'}</span><span>拖动进度查看任意时点</span><span>{kind==='wms'?`${fmt(w.seconds/60)} 分钟`:hours(horizon)}</span></div></div><div className="ops-legend"><span><i className="teal"/>作业 / 可通行</span><span><i className="orange"/>异常 / 等待</span><span><i className="purple"/>备用 / 被选对象</span><span>下方指标为整个方案的计算结果</span></div></div>
 <aside className="ops-controls"><div className="ops-panel-title"><span>01</span><h3>调整业务条件</h3></div>{kind==='mes'?<><Range label="工单需求量" min={80} max={240} step={20} value={mes.demand} unit="吨" onChange={demand=>updateMes({demand})}/><Range label="A 线停机时间" min={0} max={240} step={30} value={mes.downtime} unit="分钟" onChange={downtime=>updateMes({downtime})}/><div className="ops-choice" aria-label="生产处置策略"><button className={mes.strategy==='wait'?'active':''} aria-pressed={mes.strategy==='wait'} onClick={()=>updateMes({strategy:'wait'})}>等待恢复<small>A 线完成全部工单</small></button><button className={mes.strategy==='reroute'?'active':''} aria-pressed={mes.strategy==='reroute'} onClick={()=>updateMes({strategy:'reroute'})}>改派 B 线<small>两条产线并行加工</small></button></div></>:kind==='tms'?<><Range label="发运重量" min={8} max={30} step={2} value={tms.demand} unit="吨" onChange={demand=>updateTms({demand})}/><Range label="主路拥堵等待" min={0} max={180} step={30} value={tms.congestion} unit="分钟" onChange={congestion=>updateTms({congestion})}/><label className="ops-truck-count">车辆数量 · 10 吨 / 辆<div>{[1,2,3].map(n=><button key={n} className={tms.trucks===n?'active':''} aria-pressed={tms.trucks===n} onClick={()=>updateTms({trucks:n})}>{n} 辆</button>)}</div></label><div className="ops-choice" aria-label="运输路线"><button className={tms.strategy==='direct'?'active':''} aria-pressed={tms.strategy==='direct'} onClick={()=>updateTms({strategy:'direct'})}>主路<small>180 km / 车</small></button><button className={tms.strategy==='detour'?'active':''} aria-pressed={tms.strategy==='detour'} onClick={()=>updateTms({strategy:'detour'})}>绕行路线<small>240 km / 车</small></button></div></>:<><Range label="本波次订单数" min={2} max={6} value={wms.orders} unit="单" onChange={orders=>updateWms({orders})}/><div className="ops-choice" aria-label="拣货方式"><button className={wms.strategy==='single'?'active':''} aria-pressed={wms.strategy==='single'} onClick={()=>updateWms({strategy:'single'})}>逐单往返<small>每单回到集货台</small></button><button className={wms.strategy==='wave'?'active':''} aria-pressed={wms.strategy==='wave'} onClick={()=>updateWms({strategy:'wave'})}>合并波次<small>同类物料集中拣取</small></button></div><button className={`ops-slotting ${wms.forward?'active':''}`} aria-pressed={wms.forward} onClick={()=>updateWms({forward:!wms.forward})}><span><PackageCheck size={18}/><strong>高频 A / C 库位前置</strong></span><span>{wms.forward?<Check size={16}/>:<ArrowRight size={16}/>}</span></button><p className="ops-tiny">前置后，A / C 更靠近集货台。可以叠加比较波次与库位策略。</p></>}
 <div className="ops-object-panel"><div className="ops-panel-title"><span>02</span><h3>点选并理解对象</h3></div><div className="ops-object-buttons">{objects.map(o=><button key={o.id} aria-pressed={o.id===object.id} className={o.id===object.id?'active':''} onClick={()=>setSelected(o.id)}>{o.name}</button>)}</div><div className="ops-object-detail"><small>{object.code}</small><h4>{object.name}</h4><dl>{object.facts.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><p>{object.note}</p></div></div></aside></div>
 <div className="ops-metrics" aria-label="方案计算结果">{metrics.map(metric=><div key={metric.label} className={metric.risk?'risk':''}><span>{metric.label}</span><strong>{metric.value}</strong><small>{metric.sub}</small></div>)}</div>
 <div className="ops-decision"><span className="ops-decision-icon"><Sparkles size={23}/></span><div><span className="ops-eyebrow">处置建议 · 规则模拟</span><h3>{kind==='mes'?ma.finish<mb.finish?'启用备用线，可以缩短这次延误。':'这次改派未必更快，先比较再决策。':kind==='tms'?!t.feasible?'先补足运力，路线才有执行意义。':ta.eta<tb.eta?'拥堵时间超过绕行代价，可以考虑备用路线。':'主路更快也更省，无需为了绕行而绕行。':w.meters<wb.meters?'路线已经缩短，复核步骤仍然保留。':'先把相同 SKU 的订单放进同一个波次。'}</h3><p>{kind==='mes'?`相同需求与停机条件下：等待 ${hours(mb.finish)} 完工，改派 ${hours(ma.finish)} 完工；B 线承接 ${fmt(ma.bQty)} 吨，附加费用 ¥${fmt(ma.cost,0)}。备用线的产能与准备时间也可能成为新瓶颈。`:kind==='tms'?!t.feasible?`当前 ${t.trucks} 辆车只能运 ${t.capacity} 吨，发运需求 ${t.demand} 吨，至少需要 ${Math.ceil(t.demand/10)} 辆车。`:`主路交付 ${hours(tb.eta)}，绕行交付 ${hours(ta.eta)}；绕行每车多 60 km，计划费用增加 ¥${fmt(ta.cost-tb.cost,0)}。改变拥堵程度后，较优选择也可能改变。`:`当前 ${w.count} 单需要访问 ${w.visits} 次货位；相对标准库位逐单拣货，少走 ${fmt(wb.meters-w.meters,0)} 米。合并拣取后，仍安排 ${w.count*30} 秒逐单复核与打包。`}</p></div><button onClick={()=>{if(kind==='mes')updateMes({strategy:mes.strategy==='wait'?'reroute':'wait'});if(kind==='tms')updateTms(!t.feasible?{trucks:Math.ceil(t.demand/10)}:{strategy:tms.strategy==='direct'?'detour':'direct'});if(kind==='wms')updateWms({strategy:wms.strategy==='single'?'wave':'single'})}}>{kind==='mes'?mes.strategy==='wait'?'试用改派方案':'对比等待方案':kind==='tms'?!t.feasible?'补足车辆':tms.strategy==='direct'?'试用绕行方案':'对比主路方案':wms.strategy==='single'?'试用合并波次':'对比逐单拣货'}<ArrowRight size={16}/></button></div>
 <div className="ops-evidence-grid"><section className="ops-evidence"><h3><GitBranch size={19}/>同一输入，比较不同决策</h3><div className="ops-table-wrap"><table><thead><tr><th>业务指标</th><th>{kind==='mes'?'等待恢复':kind==='tms'?'主路方案':'标准库位 · 逐单'}</th><th>当前方案</th></tr></thead><tbody>{comparison.map(row=><tr key={row[0]}>{row.map((v,i)=>i===0?<th key={i} scope="row">{v}</th>:<td key={i}>{v}</td>)}</tr>)}</tbody></table></div><p className="ops-tiny">{kind==='wms'?'基线保留当前订单数，采用标准库位和逐单拣货。':'基线保留你设置的需求量和异常条件，只改变处置策略。'}</p></section><section className="ops-evidence ops-system-links"><h3><ShieldCheck size={19}/>把一次操作连回业务系统</h3>{(kind==='mes'?[['ERP','销售订单 → 生产需求','工单需求量来自订单承诺。'],['MES','设备事件 → 改派与质量记录','同一工单绑定资源、产出和检验。'],['WMS','合格产出 → 成品入库','按实际合格数量接收库存。']]:kind==='tms'?[['ERP','客户订单 → 交付期限','明确“到达”还是“卸货完成”。'],['WMS','备货结果 → 待运重量','计划重量必须与实际装车一致。'],['TMS','车辆与路线 → 运单里程碑','记录装车、在途事件和签收。']]:[['ERP','客户订单 → 出库需求','每单对应 SKU 与需求数量。'],['WMS','库存与波次 → 拣选任务','库位调整改变位置，不改变物料身份。'],['TMS','复核完成 → 待装车运单','集货结果作为后续发运输入。']]).map(([system,title,desc])=><div className="ops-system-row" key={system}><b>{system}</b><div><strong>{title}</strong><p>{desc}</p></div></div>)}</section></div>
 <details className="ops-assumptions"><summary><Info size={17}/>展开计算规则与实验边界 <ChevronDown size={16}/></summary>{kind==='mes'?<ul><li>班次从 08:00 开始、16:00 结束；A 线 25 吨/小时，10:00 停机。恢复后继续加工，工单允许跨班完成。</li><li>B 线假设空闲且已通过工艺认证；10:00 决策后准备 30 分钟。改派量 = min(需求 × 40%，60 吨，10:00 后未加工数量)。</li><li>改派费用 = 1,200 元准备费 + 改派吨数 × 12 元。每批固定检验 30 分钟，假设全部合格，未计其他订单竞争与换型。</li><li>完工时刻取两条线最后完工时间加检验时间；班末可交付量取 15:30 之前加工完成的量。</li></ul>:kind==='tms'?<ul><li>08:00 开始装车，装车 30 分钟，卸货 15 分钟；行驶速度 60 km/h。13:00 前完成卸货视为准时。</li><li>主路 180 km，中段增加所选拥堵时间；备用路 240 km，本例中不拥堵。路网为示意，图上比例不代表真实地理距离。</li><li>每车载重 10 吨；假设货物可分车装载、装卸并行。运力不足时整批不发车，报价仍显示方案估算。</li><li>费用 = 车辆数 ×（每车里程 × 3.2 元/km + 160 元）。未计体积、路桥费、司机工时与交通动态。</li></ul>:<ul><li>订单依次需求 A、C、B、A、D、C，每单 1 箱，滑块截取前 N 单。所有物料均有足够库存。</li><li>1 坐标单位 = 2 米；只能沿纵向巷道和前后横向通道行走，速度 1 米/秒。</li><li>每次货位访问固定 20 秒；每单最终复核打包 30 秒。合并波次枚举最多 4 个不同 SKU 的访问顺序，选择总路线最短者。</li><li>高频前置只改变 A / C 库位；忽略一次性搬迁成本、小车容量与人员相遇，适合比较策略原理。</li></ul>}<p>全部数据与费用为合成教学参数，处置建议由上述规则生成；此处不连接生产系统或调用大模型。</p></details>
 <div className="ops-reading"><BookOpen size={22}/><div><strong>从可操作的案例，回到系统的核心能力</strong><p>{source.summary}</p><a href={source.url} target="_blank" rel="noopener noreferrer">{source.title}<ArrowUpRight size={15}/></a><a href="/glossary?term=ontology">为什么这些对象需要统一业务含义？<ArrowRight size={15}/></a></div></div></section>;
}
