"use client";
import {useState,useRef,useEffect} from 'react';
import {Play,RotateCcw,Plus,Trash2,ArrowUp,ArrowDown,GripVertical,Database,GitBranch,Bot,ShieldCheck,FileInput,Check,Download,AlertCircle,Pause,Terminal} from 'lucide-react';
import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';import {Textarea} from '@/components/ui/textarea';import {Slider} from '@/components/ui/slider';import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import AgentShowcase from './agent-showcase';
import {StudioHeading} from './studio-shared';import {invoices,matchInvoice,money} from '@/lib/simulation';
type Kind='input'|'knowledge'|'model'|'condition'|'approval'|'output';
const definitions:Record<Kind,{label:string,icon:typeof Bot,desc:string,color:string}>={input:{label:'用户输入',icon:FileInput,desc:'载入单据字段',color:'blue'},knowledge:{label:'知识检索',icon:Database,desc:'采购制度 · 版本 1.0',color:'cyan'},model:{label:'LLM 解释',icon:Bot,desc:'生成差异说明',color:'violet'},condition:{label:'条件分支',icon:GitBranch,desc:'校验容差与金额',color:'amber'},approval:{label:'人工确认',icon:ShieldCheck,desc:'异常与大额审批',color:'mint'},output:{label:'结果输出',icon:Terminal,desc:'证据与下一步建议',color:'blue'}};
const initial:Kind[]=['input','knowledge','model','condition','approval','output'];
type Trace={node:Kind,status:string,detail:string};
export default function AgentLab(){const[nodes,setNodes]=useState<Kind[]>(initial);const[selected,setSelected]=useState<Kind>('condition');const[invoiceId,setInvoice]=useState(invoices[1].id);const[tolerance,setTolerance]=useState(1);const[threshold,setThreshold]=useState(100000);const[prompt,setPrompt]=useState('你是采购审单助手。引用单据字段，解释数量和单价差异，给出简短处理建议。');const[trace,setTrace]=useState<Trace[]>([]);const[running,setRunning]=useState(false);const[pending,setPending]=useState(false);const[result,setResult]=useState('');const[error,setError]=useState('');const[dragged,setDragged]=useState<Kind|null>(null);const runId=useRef(0);const current=invoices.find(r=>r.id===invoiceId)!;const match=matchInvoice(current,tolerance,threshold);
useEffect(()=>()=>{runId.current++},[]);
function clearRun(){runId.current++;setTrace([]);setResult('');setPending(false);setRunning(false);setError('')}
function move(k:Kind,offset:number){clearRun();const copy=[...nodes],i=copy.indexOf(k),j=i+offset;if(i<1||j<1||i>=copy.length-1||j>=copy.length-1)return;[copy[i],copy[j]]=[copy[j],copy[i]];setNodes(copy)}
function insert(k:Kind){clearRun();setNodes(p=>[...p.slice(0,-1),k,'output']);setSelected(k)}
function outcome(approved:boolean){const context=nodes.includes('knowledge')?'依据采购制度 v1.0；数量与单价分别校验。':'未检索制度；仅展示单据计算，合规结论待复核。';if(/json/i.test(prompt))return JSON.stringify({invoice:current.id,quantity_delta:current.invoicedQty-current.receivedQty,amount_delta:match.difference,tolerance_percent:tolerance,decision:approved?'人工确认完成（演示）':match.status,source:current.purchaseOrderId},null,2);return `${current.id} · ${current.itemName}\n\n${approved?'人工已确认此模拟处理建议':match.status}。${match.exception?`发票与收货/采购存在超过 ${tolerance}% 容差的差异。建议核对收货或更正发票。`:'数量与单价均在所设容差范围内。'}\n${current.invoiceAmount>=threshold?`发票金额 ${money(current.invoiceAmount)}，触发 ${money(threshold)} 大额阈值。`:''}\n证据：收货 ${current.receivedQty}；开票 ${current.invoicedQty}；采购单价 ${money(current.poUnitPrice)}；发票单价 ${money(current.invoiceUnitPrice)}。\n${context}\n\n本次运行没有过账、付款或回写 ERP。`}
async function run(){clearRun();if(nodes[0]!=='input'||nodes[nodes.length-1]!=='output'){setError('工作流需要从用户输入开始，以结果输出结束。');return}if(!nodes.includes('condition')){setError('缺少条件分支：请添加校验节点，避免未经规则检查就给出审单结论。');return}if(nodes.includes('approval')&&nodes.indexOf('approval')<nodes.indexOf('condition')){setError('人工确认需要放在条件分支之后，才能读取检查结果。');return}if(nodes.includes('knowledge')&&nodes.indexOf('knowledge')>nodes.indexOf('condition')){setError('知识检索需要在条件分支之前，为校验提供规则依据。');return}if(nodes.includes('model')&&nodes.indexOf('model')>nodes.indexOf('condition')){setError('请将 LLM 解释放在条件分支之前，人工确认后直接输出结果。');return}if(nodes.includes('knowledge')&&nodes.includes('model')&&nodes.indexOf('knowledge')>nodes.indexOf('model')){setError('LLM 解释需要放在知识检索之后，才能引用检索结果。');return}const id=++runId.current;setRunning(true);for(const k of nodes){await new Promise(r=>setTimeout(r,420));if(id!==runId.current)return;let detail='';if(k==='input')detail=`载入 ${current.id}，6 个核对字段，金额 ${money(current.invoiceAmount)}`;if(k==='knowledge')detail='检索到采购制度 v1.0：按收货量和合同单价核对；异常转人工。';if(k==='model')detail=`根据已载入字段生成${/json/i.test(prompt)?' JSON ':'文字'}解释；模型不负责金额计算。`;if(k==='condition')detail=`数量差异 ${(match.qtyRate*100).toFixed(2)}%，单价差异 ${(match.priceRate*100).toFixed(2)}%；分支 → ${match.exception||match.approval?'人工处理':'正常输出'}`;if(k==='approval'&&(match.exception||match.approval)){setTrace(p=>[...p,{node:k,status:'等待确认',detail:'运行在此暂停，请确认或退回这条模拟建议。'}]);setPending(true);setRunning(false);return}if(k==='approval')detail='当前单据无需人工复核，跳过此节点。';if(k==='output'){if((match.exception||match.approval)&&!nodes.includes('approval')){setError('命中异常或大额条件，但没有人工确认节点。流程已阻止输出通过结论。');setRunning(false);return}setResult(outcome(false));detail='输出可追溯建议，完成本次模拟。'}setTrace(p=>[...p,{node:k,status:'完成',detail}])}setRunning(false)}
function resolve(approved:boolean){setPending(false);setTrace(p=>p.map(t=>t.node==='approval'?{...t,status:approved?'已确认':'已退回',detail:approved?'演示审核已确认；未写入业务系统。':'演示审核退回，请补充单据后重跑。'}:t));setResult(approved?outcome(true):`${current.id} 已退回。请核对单据后重新运行。`);setTrace(p=>[...p,{node:'output',status:'完成',detail:approved?'输出经人工确认的建议。':'输出退回原因。'}])}
function download(){const blob=new Blob([JSON.stringify({format:'ai-practice-teaching-flow',version:1,nodes,tolerancePercent:tolerance,approvalThreshold:threshold,prompt,sampleInvoice:invoiceId},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='procurement-teaching-flow.json';a.click();URL.revokeObjectURL(url)}
return <><AgentShowcase onTry={id=>{clearRun();setInvoice(id);setSelected('input')}}/><div className="agent-builder-anchor" id="procurement-builder" tabIndex={-1}><span className="eyebrow">NOW, MAKE IT YOURS</span><h2>现在，轮到你来搭建。</h2><p>点击节点配置规则，运行同一张单据，观察分支、证据与人工确认。</p></div>
<div className="workspace-toolbar"><div className="toolbar-title"><span className="live-dot"/>采购审单助手 <span className="small-tag">节点式教学沙盒</span></div><div><Button variant="outline" onClick={download}><Download size={16}/>导出配置</Button><Button variant="outline" disabled={running} onClick={()=>{clearRun();setNodes(initial);setTolerance(1);setThreshold(100000);setSelected('condition')}}><RotateCcw size={16}/>重置</Button><Button onClick={run} disabled={running||pending}><Play size={16}/>{running?'运行中…':'运行工作流'}</Button></div></div>
<div className="agent-workspace"><aside className="node-palette"><h3>添加节点</h3><p>输入与输出为固定边界，其他节点可增减。</p>{(['knowledge','model','condition','approval'] as Kind[]).map(k=>{const d=definitions[k];return <button disabled={nodes.includes(k)||running||pending} key={k} onClick={()=>insert(k)}><d.icon size={19}/><span>{d.label}<small>{d.desc}</small></span>{nodes.includes(k)?<Check size={15}/>:<Plus size={16}/>}</button>})}<div className="palette-tip"><strong>试一试</strong><p>将容差从 1% 改为 3%，再运行轴承发票，观察条件分支。</p><a href="/learn?lesson=dify">理解 Dify 节点概念 →</a></div></aside>
<div className="flow-canvas"><div className="canvas-label">PURCHASE REVIEW / {nodes.length} NODES</div>{nodes.map((k,i)=>{const d=definitions[k],t=trace.find(t=>t.node===k);return <div key={k} className="flow-node-wrap" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!dragged||dragged===k||k==='input'||k==='output')return;clearRun();const a=nodes.filter(n=>n!==dragged);a.splice(a.indexOf(k),0,dragged);setNodes(a);setDragged(null)}}><div className={`flow-node ${selected===k?'selected':''} ${t?'executed':''}`} draggable={k!=='input'&&k!=='output'&&!running&&!pending} onDragStart={()=>setDragged(k)}><button className="node-main" disabled={running||pending} onClick={()=>setSelected(k)}><span className={`node-symbol ${d.color}`}><d.icon size={20}/></span><span><strong>{d.label}</strong><small>{k==='condition'?`容差 ${tolerance}% · 审批 ≥ ${money(threshold)}`:d.desc}</small></span>{t?<span className="node-status">{t.status}</span>:<GripVertical size={16}/>}</button>{selected===k&&k!=='input'&&k!=='output'&&<div className="node-actions"><button disabled={i===1||running||pending} aria-label={`上移${d.label}`} onClick={()=>move(k,-1)}><ArrowUp size={14}/></button><button disabled={i===nodes.length-2||running||pending} aria-label={`下移${d.label}`} onClick={()=>move(k,1)}><ArrowDown size={14}/></button><button disabled={running||pending} aria-label={`移除${d.label}`} onClick={()=>{clearRun();setNodes(nodes.filter(n=>n!==k));setSelected('input')}}><Trash2 size={14}/></button></div>}</div>{i<nodes.length-1&&<span className="node-connector"/>}</div>})}<div className="canvas-caption">节点与运行轨迹可操作 · 逻辑在站内模拟执行</div></div>
<aside className="node-inspector"><h3>{definitions[selected].label}<span>节点配置</span></h3><div className="inspector-content">{selected==='input'&&<><label>示例发票</label><InvoiceSelect value={invoiceId} onChange={v=>{clearRun();setInvoice(v)}}/><div className="mini-keyvalues"><span>供应商<strong>{current.supplier}</strong></span><span>收货 / 开票<strong>{current.receivedQty} / {current.invoicedQty}</strong></span><span>发票金额<strong>{money(current.invoiceAmount)}</strong></span></div></>}{selected==='condition'&&<><label>数量 / 单价容差 <b>{tolerance}%</b></label><Slider aria-label="审单容差" value={[tolerance]} min={0} max={10} step={.5} disabled={running||pending} onValueChange={v=>{clearRun();setTolerance(v[0])}}/><p>分别计算数量与单价的相对差异，超过容差即转人工。</p><label htmlFor="approval-threshold">大额审批阈值（元）</label><Input id="approval-threshold" type="number" min={1} value={threshold} disabled={running||pending} onChange={e=>{clearRun();setThreshold(Math.max(1,Number(e.target.value)))}}/><code>IF 差异超限 OR 金额 ≥ 阈值<br/>→ 人工确认<br/>ELSE → 结果输出</code></>}{selected==='model'&&<><label htmlFor="node-prompt">系统提示词</label><Textarea id="node-prompt" rows={7} value={prompt} onChange={e=>{clearRun();setPrompt(e.target.value)}}/><p>教学引擎支持文字说明或 JSON 输出；在提示词中加入“JSON”可切换格式。金额由规则计算。</p></>}{selected==='knowledge'&&<><span className="document-chip"><Database size={17}/>采购制度 v1.0</span><p>匹配依据：采购单价、实际收货数量、发票数量与金额。</p><p>检索结果用于说明引用来源。移除此节点后，结果会提示缺少制度依据。</p></>}{selected==='approval'&&<><p>遇到差异超限或大额单据，运行暂停，等待“确认建议”或“退回”。</p><div className="inspector-rule"><ShieldCheck/>人工确认 ≠ 自动付款</div></>}{selected==='output'&&<><p>输出单据编号、差异证据、制度版本、处理建议和人工确认状态。</p><p>导出的 JSON 是本教学工坊格式，不是 Dify 可直接导入的 DSL。</p></>}</div></aside></div>
<section className="run-console"><div className="console-toolbar"><h3><Terminal size={19}/>运行与调试</h3><InvoiceSelect value={invoiceId} onChange={v=>{clearRun();setInvoice(v)}} disabled={running||pending}/></div>{error&&<div className="inline-error" role="alert"><AlertCircle size={18}/>{error}</div>}<div className="console-columns"><div className="trace-list">{!trace.length&&<p className="empty-inline">点击“运行工作流”，这里会逐步显示每个节点的输入与处理结果。</p>}{trace.map((t,i)=><div className="trace-row" key={i}><span className={t.status==='等待确认'?'pending':'done'}>{t.status==='等待确认'?<Pause size={13}/>:<Check size={13}/>}</span><div><strong>{definitions[t.node].label}<small>{t.status}</small></strong><p>{t.detail}</p></div></div>)}</div><div className="run-output"><span className="eyebrow">OUTPUT</span>{pending?<div className="approval-request"><ShieldCheck size={32}/><h3>需要你确认</h3><p>{match.status}，请审阅单据和检查结果。</p><div><Button onClick={()=>resolve(true)}>确认建议</Button><Button variant="outline" onClick={()=>resolve(false)}>退回</Button></div></div>:<pre>{result||'运行结果将在这里出现。\n\n可以从正常、数量差异、单价差异和大额单据中选择测试样本。'}</pre>}</div></div></section><p className="fine-print">这是借鉴节点式编排理念的独立教学模拟器，未嵌入 Dify 服务，也不会调用真实大模型。<a href="https://docs.dify.ai/en/learn/key-concepts" target="_blank" rel="noopener noreferrer">Dify 官方文档 ↗</a></p>
</>}
function InvoiceSelect({value,onChange,disabled=false}:{value:string,onChange:(v:string)=>void,disabled?:boolean}){return <Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger aria-label="选择示例发票"><SelectValue/></SelectTrigger><SelectContent>{invoices.map(r=><SelectItem value={r.id} key={r.id}>{r.id.slice(-3)} · {r.itemName} · {r.statusLabel}</SelectItem>)}</SelectContent></Select>}
