"use client";
import {useLearningLocation,replaceLearningUrl} from '@/lib/learning-location';
import {useState,useEffect} from 'react';import {ArrowUpRight,BookOpen,Layers,FileText,FlaskConical,ArrowRight,Search} from 'lucide-react';import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';import {Input} from '@/components/ui/input';import {StudioHeading} from './studio-shared';import ProjectDemo from './project-demos';import data from '@/lib/project-cases.json';
type Citation={filename:string;locator_type:string;page:number};type Case={id:string;title:string;subtitle:string;maturity:string;public_summary:string;facts:{text:string;citation:Citation}[];planned:{text:string;citation:Citation}[];capabilities:{title:string;description:string;citation:Citation}[];demo:{title:string;teaching_point:string;edge_cases:string[]}};
const cases=data.cases as Case[];const groups=[['全部','all'],['问数与知识','knowledge'],['单据与业务','business'],['平台与决策','platform']] as const;const grouping:Record<string,string>={'financial-query':'knowledge','policy-rag':'knowledge','document-writing':'knowledge','invoice-ocr':'business','supply-documents':'business','erp-overseas':'business','price-rebate':'business','agent-workbench':'platform','master-data':'platform','supplychain-planning':'platform','industrial-vision':'platform'};
function Cite({c}:{c:Citation}){return <small className="case-citation">{c.filename} · {c.locator_type==='slide'?'幻灯片':'第'} {c.page} {c.locator_type==='slide'?'':'页'}</small>}
export default function ProjectGallery({embedded=false}:{embedded?:boolean}){const[selected,setSelected]=useState(cases[0].id);const[group,setGroup]=useState('all');const[query,setQuery]=useState('');const[tab,setTab]=useState('demo');useLearningLocation('/projects',params=>{const key=params.get('case');setSelected(cases.some(c=>c.id===key)?key!:cases[0].id)});const item=cases.find(c=>c.id===selected)!;const visible=cases.filter(c=>(group==='all'||grouping[c.id]===group)&&`${c.title}${c.subtitle}${c.public_summary}`.includes(query));function choose(id:string){setSelected(id);setTab('demo');replaceLearningUrl(`/projects?case=${id}`)}return <>
{!embedded&&<StudioHeading eyebrow="BAOSIGHT / PROJECTS & PRODUCTS" title="供应链 AI 产品专栏" desc="把项目材料中的能力变成可理解、可试用的场景。每个案例都保留材料依据与当前阶段。"/>}
<div className="project-filter"><Tabs value={group} onValueChange={v=>{setGroup(v);const first=cases.find(c=>v==='all'||grouping[c.id]===v);if(first)choose(first.id)}}><TabsList>{groups.map(([name,id])=><TabsTrigger value={id} key={id}>{name}</TabsTrigger>)}</TabsList></Tabs><div className="v3-search"><Search size={17}/><Input aria-label="搜索产品案例" placeholder="搜索：问数、发票、返利…" value={query} onChange={e=>setQuery(e.target.value)}/></div></div>
<div className="case-layout"><aside className="case-rail"><span className="eyebrow">{visible.length} 个产品场景</span>{visible.map((c,i)=><button key={c.id} className={selected===c.id?'active':''} onClick={()=>choose(c.id)}><span>{String(cases.indexOf(c)+1).padStart(2,'0')}</span><div><strong>{c.title}</strong><small>{c.subtitle}</small></div><ArrowUpRight size={15}/></button>)}{!visible.length&&<p>没有匹配案例，试试其他关键词。</p>}<a className="rail-explore" href="/ontology"><Layers size={19}/>在 3D 中探索业务关系 <ArrowRight size={16}/></a></aside><div className="case-content" key={selected}><div className="case-heading"><span className="eyebrow">PRODUCT CASE / {String(cases.indexOf(item)+1).padStart(2,'0')}</span><h2>{item.title}</h2><p>{item.public_summary}</p><span className="case-stage"><FileText size={15}/>{item.maturity}</span></div><Tabs value={tab} onValueChange={setTab}><TabsList variant="line"><TabsTrigger value="demo"><FlaskConical size={16}/>体验场景</TabsTrigger><TabsTrigger value="capabilities">产品能力</TabsTrigger><TabsTrigger value="sources"><BookOpen size={16}/>材料与阶段</TabsTrigger></TabsList></Tabs>
{tab==='demo'&&<div className="case-demo"><div className="demo-banner"><span>{item.demo.title}</span><small>合成数据 · 本地规则 / 预置回放</small></div><ProjectDemo id={item.id}/><div className="demo-takeaway"><BookOpen size={18}/><p>{item.demo.teaching_point}</p></div><div className="case-boundaries"><span>上线需覆盖的验证项</span>{item.demo.edge_cases.slice(0,3).map(e=><span key={e}>{e}</span>)}</div></div>}
{tab==='capabilities'&&<div className="case-capabilities">{item.capabilities.map((c,i)=><article key={c.title}><span>0{i+1}</span><h3>{c.title}</h3><p>{c.description}</p><Cite c={c.citation}/></article>)}</div>}
{tab==='sources'&&<div className="case-facts"><h3>材料描述</h3>{item.facts.map((f,i)=><article key={i}><p>{f.text}</p><Cite c={f.citation}/></article>)}<h3>规划与待验证内容</h3>{item.planned.map((f,i)=><article key={i}><p>{f.text}</p><Cite c={f.citation}/></article>)}<p className="v3-neutral-note">这里按所提供材料的当时状态归纳；计划日期已过不表示自动完成。教学场景不代表客户生产环境或个人项目业绩。</p></div>}
</div></div><div className="v3-bottom-pair"><a href="/ontology"><Layers size={24}/><div><h3>从产品进入业务对象</h3><p>用 Ontology 解释数据、关系、规则与动作。</p></div><ArrowUpRight size={20}/></a><a href="/products"><FlaskConical size={24}/><div><h3>继续原有供应链实验</h3><p>采购三单匹配、库存补货与经营问数。</p></div><ArrowUpRight size={20}/></a></div>
</>}
