"use client";
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {SpatialSoftwareRenderer} from '@/lib/spatial-software-renderer';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RotateCcw,Plus,Minus,Move3D,Pause,Play} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {spatialNodes,spatialEdges,delayScenario} from '@/lib/spatial-data';
import {placeSpatialLabels,relatedNodeIds,type RelationScope} from '@/lib/spatial-layout';
type Props={mode:'graph'|'factory'|'chart';selected:string;onSelect:(id:string)=>void;delay:number;expedite:boolean;scope?:RelationScope};
export default function SpatialScene({mode,selected,onSelect,delay,expedite,scope='related'}:Props){const host=useRef<HTMLDivElement>(null);const actions=useRef<{reset:()=>void;zoom:(n:number)=>void}|null>(null);const live=useRef({selected,onSelect,delay,expedite,scope,rotate:false});live.current={...live.current,selected,onSelect,delay,expedite,scope};const[error,setError]=useState(false);const[compat,setCompat]=useState(false);const[rotate,setRotate]=useState(false);const[ready,setReady]=useState(false);
useEffect(()=>{if(!host.current)return;setError(false);setReady(false);const root=host.current;let renderer:THREE.WebGLRenderer|SpatialSoftwareRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'low-power'});setCompat(false);}catch{renderer=new SpatialSoftwareRenderer();setCompat(true);}renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.6));renderer.setClearColor('#102533');renderer.outputColorSpace=THREE.SRGBColorSpace;root.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label',mode==='graph'?'可旋转的供应链对象关系图':mode==='factory'?'可点选的供应链工厂场景':'供货延迟情景的三维对比图');renderer.domElement.setAttribute('role','img');
const scene=new THREE.Scene();scene.fog=new THREE.Fog('#102533',45,90);const camera=new THREE.PerspectiveCamera(43,1,.1,160);const initial=mode==='graph'?new THREE.Vector3(9,25,32):mode==='factory'?new THREE.Vector3(23,22,29):new THREE.Vector3(17,17,23);camera.position.copy(initial);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,mode==='graph'?2:0,0);controls.enableDamping=true;controls.dampingFactor=.07;controls.minDistance=12;controls.maxDistance=60;controls.maxPolarAngle=Math.PI*.48;controls.autoRotateSpeed=.45;controls.update();const target=controls.target.clone();actions.current={reset:()=>{camera.position.copy(initial);controls.target.copy(target);controls.update()},zoom:(n)=>{camera.position.sub(controls.target).multiplyScalar(n).add(controls.target);controls.update()}};
scene.add(new THREE.HemisphereLight(0xd9f4ff,0x536170,2.1));const light=new THREE.DirectionalLight(0xffffff,2.5);light.position.set(6,20,10);scene.add(light);const warm=new THREE.DirectionalLight(0xffbd83,1.1);warm.position.set(-14,6,-4);scene.add(warm);const grid=new THREE.GridHelper(40,40,0x31515f,0x203d4b);grid.position.y=-.15;scene.add(grid);
const targets:THREE.Object3D[]=[];const highlights:{mesh:THREE.Mesh,id:string,base:string}[]=[];const textures:THREE.Texture[]=[];const labels:THREE.Sprite[]=[];
function label(text:string,pos:THREE.Vector3,color='#e2f3f8',size=3.5){const canvas=document.createElement('canvas');canvas.width=640;canvas.height=90;const ctx=canvas.getContext('2d')!;ctx.font='500 48px system-ui, sans-serif';canvas.width=Math.ceil(ctx.measureText(text||'20 天').width+44);ctx.fillStyle='rgba(12,31,43,.9)';ctx.fillRect(0,0,canvas.width,90);ctx.font='500 48px system-ui, sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle=color;ctx.fillText(text,canvas.width/2,45);const t=new THREE.CanvasTexture(canvas);t.colorSpace=THREE.SRGBColorSpace;textures.push(t);const mat=new THREE.SpriteMaterial({map:t,depthTest:false,transparent:true});const sp=new THREE.Sprite(mat);sp.position.copy(pos);const worldWidth=Math.max(size,text.length*.65);sp.scale.set(worldWidth,worldWidth*90/canvas.width,1);scene.add(sp);labels.push(sp);return sp}
function box(x:number,y:number,z:number,w:number,h:number,d:number,color:string,id?:string){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,roughness:.55,metalness:.2}));mesh.position.set(x,y+h/2,z);scene.add(mesh);if(id){mesh.userData.nodeId=id;targets.push(mesh);highlights.push({mesh,id,base:color})}return mesh}
function cylinder(x:number,y:number,z:number,r:number,h:number,color:string){const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,24),new THREE.MeshStandardMaterial({color,roughness:.45,metalness:.5}));m.position.set(x,y+h/2,z);scene.add(m);return m}
const lines:{line:THREE.Line,id1:string,id2:string}[]=[];
const graphLabels:{id:string;mesh:THREE.Mesh;button:HTMLButtonElement;leader:SVGLineElement}[]=[];
const labelLayer=document.createElement('div');labelLayer.className='spatial-object-labels';root.appendChild(labelLayer);const leaderLayer=document.createElementNS('http://www.w3.org/2000/svg','svg');leaderLayer.setAttribute('class','spatial-label-leaders');labelLayer.appendChild(leaderLayer);

if(mode==='graph'){spatialNodes.forEach(n=>{const m=new THREE.Mesh(new THREE.IcosahedronGeometry(n.type==='规则'?.66:.85,2),new THREE.MeshStandardMaterial({color:n.color,metalness:.3,roughness:.25}));m.position.set(...n.position);m.userData.nodeId=n.id;scene.add(m);targets.push(m);highlights.push({mesh:m,id:n.id,base:n.color});const ring=new THREE.Mesh(new THREE.TorusGeometry(1.07,.025,8,40),new THREE.MeshBasicMaterial({color:n.color,transparent:true,opacity:.5}));ring.position.copy(m.position);ring.rotation.x=Math.PI/2;scene.add(ring);const button=document.createElement('button');button.className='spatial-object-label';button.textContent=n.name;button.setAttribute('aria-label',`查看${n.name}`);button.onclick=()=>live.current.onSelect(n.id);labelLayer.appendChild(button);const leader=document.createElementNS('http://www.w3.org/2000/svg','line');leaderLayer.appendChild(leader);graphLabels.push({id:n.id,mesh:m,button,leader})});spatialEdges.forEach(([a,b,title])=>{const p=new THREE.Vector3(...spatialNodes.find(n=>n.id===a)!.position),q=new THREE.Vector3(...spatialNodes.find(n=>n.id===b)!.position);const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([p,q]),new THREE.LineBasicMaterial({color:'#53758a',transparent:true,opacity:.65}));scene.add(line);lines.push({line,id1:a,id2:b});const dir=q.clone().sub(p).normalize();const arrow=new THREE.ArrowHelper(dir,p.clone().lerp(q,.65),1.2,0x8ccbdc,.6,.32);scene.add(arrow);line.userData.arrow=arrow;const tube=new THREE.Mesh(new THREE.TubeGeometry(new THREE.LineCurve3(p,q),1,.045,7,false),new THREE.MeshBasicMaterial({color:'#8ccbdc',transparent:true}));scene.add(tube);line.userData.tube=tube;line.visible=false})}
let truck:THREE.Group|undefined;let warning:THREE.Mesh|undefined;
if(mode==='factory'){
box(0,-.35,0,28,.2,21,'#1e3a48');box(0,-.12,6.8,26,.06,2.4,'#48606a');box(-8,-.12,0,2.2,.06,18,'#48606a');for(let x=-12;x<13;x+=2)box(x,-.05,6.8,.9,.025,.09,'#b6c8cd');
box(-10,0,-4,4,2.1,4,'#58a2ab','supplier');box(-10,2.1,-4,4.3,.24,4.3,'#99d5d7','supplier');label('供应商 / 采购单',new THREE.Vector3(-10,3.8,-4));
box(-2.5,0,-5,7,2.5,5,'#779da9','stock');box(-2.5,2.5,-5,7.4,.35,5.4,'#b3ccd2','stock');for(let x=-5;x<1;x+=1.25)box(x,.7,-2.44,.75,1.6,.1,'#263f4e','stock');label('原料仓 · 60 吨',new THREE.Vector3(-2.5,4.3,-5));
box(7,0,-3.8,8,1.6,7,'#45667a','line');for(let x=4;x<11;x+=2){box(x,1.6,-3.8,1.65,.4,7.3,'#bdd5dc','line');box(x,1.05,-.24,1.1,.45,.1,'#8ac4d4','line')}for(let x=4;x<10;x+=2){cylinder(x,2,-6,.43,3,'#b6c8ce');cylinder(x,5,-6,.5,.18,'#e58b58')}label('精加工产线 · 20 吨/天',new THREE.Vector3(7,6.6,-3.8),undefined,5);
box(8,0,3,6,.35,3,'#78919b','logistics');for(let i=0;i<3;i++){box(6+i*1.7,.35,3,1.5,1.1,2.6,i%2?'#db975f':'#71adb4','logistics');for(let j=0;j<4;j++)box(6+i*1.7-.55+j*.35,.4,4.33,.035,1,.035,'#bbd0d4')}label('成品仓 / 出货',new THREE.Vector3(8,2.8,3));
for(let i=0;i<3;i++){cylinder(-3+i*1.5,.1,2.8,.6,1.6,'#b9c7cb');}label('卷材 M-01',new THREE.Vector3(-1.5,2.7,2.8));
const lane=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(-8,.05,6.8),new THREE.Vector3(-8,.05,1.7),new THREE.Vector3(7,.05,1.7)]),new THREE.LineDashedMaterial({color:'#76d2d8',dashSize:.55,gapSize:.3}));lane.computeLineDistances();scene.add(lane);
truck=new THREE.Group();const cargo=new THREE.Mesh(new THREE.BoxGeometry(2,.8,.9),new THREE.MeshStandardMaterial({color:'#eaa066'}));cargo.position.y=.75;truck.add(cargo);const cab=new THREE.Mesh(new THREE.BoxGeometry(.7,.7,.9),new THREE.MeshStandardMaterial({color:'#dde9e9'}));cab.position.set(1.3,.68,0);truck.add(cab);for(const x of [-.6,.8])for(const z of [-.47,.47]){const wheel=new THREE.Mesh(new THREE.CylinderGeometry(.24,.24,.15,12),new THREE.MeshStandardMaterial({color:'#152b37'}));wheel.rotation.x=Math.PI/2;wheel.position.set(x,.26,z);truck.add(wheel)}truck.position.set(-11,0,6.8);scene.add(truck);warning=new THREE.Mesh(new THREE.TorusGeometry(2.2,.04,8,50),new THREE.MeshBasicMaterial({color:'#f58b68'}));warning.position.set(7,.15,-3.8);warning.rotation.x=Math.PI/2;scene.add(warning);
}
const bars:THREE.Mesh[]=[];const chartLabels:THREE.Sprite[]=[];
if(mode==='chart'){label('时间 / 天 · 柱高为数量值',new THREE.Vector3(0,8,-5),'#d9e9ef',6);const names=['到货','缺料','完工','送达'];for(let i=0;i<4;i++){const x=-7.5+i*5;label(names[i],new THREE.Vector3(x,.1,3.5),undefined,2);const base=[2,0,8,10][i];box(x-.7,0,0,.95,Math.max(.06,base*.43),1.1,'#4a8096');const b=box(x+.7,0,0,.95,1,1.1,'#eaa06b');bars.push(b);chartLabels.push(label('',new THREE.Vector3(x+.7,2,0),'#ffcd9d',2.2))}for(let value=0;value<=20;value+=5){label(`${value} 天`,new THREE.Vector3(-11,value*.43,0),'#9ab4c2',1.7);const l=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(-10,value*.43,-1),new THREE.Vector3(10,value*.43,-1)]),new THREE.LineBasicMaterial({color:'#2a4858'}));scene.add(l)}}
let pointerStart={x:0,y:0};const down=(e:PointerEvent)=>{pointerStart={x:e.clientX,y:e.clientY}};const up=(e:PointerEvent)=>{if(Math.hypot(e.clientX-pointerStart.x,e.clientY-pointerStart.y)>6)return;const r=renderer.domElement.getBoundingClientRect();const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=ray.intersectObjects(targets,false)[0];if(hit)live.current.onSelect(hit.object.userData.nodeId)};renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointerup',up);
const resize=new ResizeObserver(()=>{const w=root.clientWidth,h=root.clientHeight;if(!w||!h)return;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()});resize.observe(root);let frame=0,last=0,lastSignature='';let visible=true;const intersection=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting});intersection.observe(root);let disposed=false;
function draw(t:number){if(disposed)return;frame=requestAnimationFrame(draw);if(!visible||document.hidden||t-last<(renderer instanceof SpatialSoftwareRenderer?65:32))return;last=t;controls.autoRotate=live.current.rotate;controls.update();const current=live.current;const result=delayScenario(current.delay,current.expedite);const affected=result.netShortage>0?['po','material','stock','line','order','logistics']:[];highlights.forEach(({mesh,id,base})=>{const m=mesh.material as THREE.MeshStandardMaterial;m.color.set(affected.includes(id)?'#ed956d':base);m.emissive.set(id===current.selected?'#64afbe':'#000000');m.emissiveIntensity=id===current.selected ? .45 : 0;if(mode==='graph')mesh.scale.setScalar(id===current.selected?1.24:1)});lines.forEach(({line,id1,id2})=>{const m=line.material as THREE.LineBasicMaterial;const active=id1===current.selected||id2===current.selected;const color=active?'#ffd398':'#6ca9be';m.color.set(color);m.opacity=active?1:current.scope==='all'?.7:.13;const tube=line.userData.tube as THREE.Mesh;if(tube){const tm=tube.material as THREE.MeshBasicMaterial;tm.color.set(color);tm.opacity=m.opacity;}const arrow=line.userData.arrow as THREE.ArrowHelper;if(arrow){arrow.setColor(color);arrow.visible=active||current.scope==='all'}});if(mode==='graph'){
 const neighbours=relatedNodeIds(current.selected);const w=root.clientWidth,h=root.clientHeight;
 const anchors=graphLabels.filter(n=>current.scope==='all'||neighbours.has(n.id)).flatMap(n=>{const p=n.mesh.position.clone().project(camera);return p.z<-1||p.z>1?[]:[{id:n.id,x:(p.x+1)*w/2,y:(1-p.y)*h/2,width:174,height:40,priority:n.id===current.selected?10:neighbours.has(n.id)?5:1}]});
 const positions=placeSpatialLabels(anchors,w,h);
 for(const n of graphLabels){const p=positions.find(p=>p.id===n.id);n.button.hidden=!p;n.leader.style.display=p?'':'none';if(p){n.leader.setAttribute('x1',String(p.x));n.leader.setAttribute('y1',String(p.y));n.leader.setAttribute('x2',String(Math.max(p.left,Math.min(p.left+p.width,p.x))));n.leader.setAttribute('y2',String(Math.max(p.top,Math.min(p.top+p.height,p.y))));n.leader.setAttribute('stroke',n.id===current.selected?'#ffd398':'#8cbdce');n.button.style.transform=`translate(${p.left}px,${p.top}px)`;n.button.style.width=`${p.width}px`;n.button.classList.toggle('is-selected',n.id===current.selected);n.button.setAttribute('aria-pressed',String(n.id===current.selected));}}
}if(truck)truck.position.x=result.netShortage>0?-8:((t*.0015)%21)-11;if(warning)warning.visible=result.netShortage>0;const sig=`${current.delay}/${current.expedite}`;if(mode==='chart'&&lastSignature!==sig){lastSignature=sig;const values=[result.arrival,result.netShortage,result.completion,result.delivery];bars.forEach((b,i)=>{const h=Math.max(.06,values[i]*.43);b.scale.y=h;b.position.y=h/2;const sp=chartLabels[i];sp.position.y=h+.65;const map=(sp.material as THREE.SpriteMaterial).map!;const c=map.image as HTMLCanvasElement;const ctx=c.getContext('2d')!;ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#ffcd9d';ctx.font='500 48px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(`${values[i]} 天`,c.width/2,c.height/2);map.needsUpdate=true})}renderer.render(scene,camera)}frame=requestAnimationFrame(draw);setReady(true);
const contextLost=(e:Event)=>{e.preventDefault();setError(true)};renderer.domElement.addEventListener('webglcontextlost',contextLost);
return()=>{disposed=true;cancelAnimationFrame(frame);resize.disconnect();intersection.disconnect();controls.dispose();renderer.domElement.removeEventListener('pointerdown',down);renderer.domElement.removeEventListener('pointerup',up);renderer.domElement.removeEventListener('webglcontextlost',contextLost);scene.traverse(o=>{const m=o as THREE.Mesh;if(m.geometry)m.geometry.dispose();if(m.material)(Array.isArray(m.material)?m.material:[m.material]).forEach(x=>x.dispose())});textures.forEach(t=>t.dispose());renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove();labelLayer.remove();actions.current=null};
},[mode]);
return <div className="spatial-viewport"><div ref={host} className="spatial-canvas"/>{!ready&&!error&&<div className="spatial-loading">正在构建 3D 场景…</div>}{error&&<div className="spatial-loading"><Move3D size={32}/><strong>当前设备无法显示 3D</strong><p>右侧对象和下方关系表仍可操作，计算结果保持可见。</p></div>}<div className="spatial-hint"><Move3D size={15}/>{mode==='graph'?'拖动旋转 · 点击球体查看 · 名称自动避让':'拖动旋转 · 滚轮缩放 · 点击对象'}{compat&&<span> · 兼容渲染</span>}</div><div className="spatial-controls"><Button variant="outline" size="icon" aria-label="放大三维场景" onClick={()=>actions.current?.zoom(.85)}><Plus size={16}/></Button><Button variant="outline" size="icon" aria-label="缩小三维场景" onClick={()=>actions.current?.zoom(1.15)}><Minus size={16}/></Button><Button variant="outline" size="icon" aria-label="重置三维视角" onClick={()=>actions.current?.reset()}><RotateCcw size={16}/></Button><Button variant="outline" size="icon" aria-label={rotate?'停止自动旋转':'自动旋转场景'} onClick={()=>{live.current.rotate=!rotate;setRotate(!rotate)}}>{rotate?<Pause size={16}/>:<Play size={16}/>}</Button></div><span className="spatial-label">{mode==='graph'?'ONTOLOGY / OBJECT GRAPH':mode==='factory'?'SUPPLY CHAIN / 3D SCENE':'SCENARIO / 3D COMPARISON'}</span></div>
}
