"use client";
import {useHumanReview,ReviewChecklist} from './human-review';
import {useState,useEffect} from 'react';import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';import {Textarea} from '@/components/ui/textarea';import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';import {Switch} from '@/components/ui/switch';import {ArrowRight,Download,Play,Pause,ChevronLeft,ChevronRight,Smartphone,FileSpreadsheet,Check,Image as ImageIcon,Film,Send} from 'lucide-react';import {ResponsiveContainer,BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,Legend} from 'recharts';import {MeetingDemo,SmallTable,NumberField,RangeField,ResultBox,CopyText,downloadText} from './experience-shared';
import MeetingStudio from './meeting-studio';
import SheetStudio from './sheet-studio';
import PptStudio from './ppt-studio';
import WritingStudio from './writing-studio';
import VisualStudio from './visual-studio';
import VideoStudio from './video-studio';
import ResearchStudio from './research-studio';
export function MobileDemo(){const[task,setTask]=useState('检查采购主数据并记录缺失字段');const[owner,setOwner]=useState('采购岗');const[due,setDue]=useState('2026-09-25');const[confirmed,setConfirmed]=useState(false);return <div className="demo-split"><section><h3>移动办公：口述之后，确认再分发</h3><p>这里用文字模拟语音转写。修改任务，检查责任人与截止日期。</p><label className="v3-field">口述任务<Input aria-label="口述任务" value={task} onChange={e=>{setTask(e.target.value);setConfirmed(false)}}/></label><label className="v3-field">责任岗位<Input aria-label="口述责任岗位" value={owner} onChange={e=>{setOwner(e.target.value);setConfirmed(false)}}/></label><label className="v3-field">截止日期<Input aria-label="口述截止日期" type="date" value={due} onChange={e=>{setDue(e.target.value);setConfirmed(false)}}/></label><Button disabled={!task.trim()} onClick={()=>setConfirmed(true)}>确认任务卡 <Check size={16}/></Button></section><section><div className="mobile-preview"><div className="phone-notch"/><span>09:41 <Smartphone size={14}/></span><h3>工作随手记</h3><div className="voice-bubble">请{owner||'（负责人待确认）'}在{due||'（日期待确认）'}前，{task||'补充任务'}。</div><div className="phone-task"><small>任务预览</small><h4>{task||'待补充任务'}</h4><p>负责人：{owner||'待确认'}</p><p>截止：{due||'待确认'}</p><span>{confirmed?'已确认 · 仅本次演示':'待人工确认'}</span></div><p>没有发送消息或创建实际待办</p></div></section></div>}
export function WritingDemo(){return <WritingStudio/>}
export function ImageDemo(){return <VisualStudio/>}
export function VideoDemo(){return <VideoStudio/>}
export function ResearchDemo(){return <ResearchStudio/>}
export function DesktopDemo(){const[tolerance,setTolerance]=useState(0);const[step,setStep]=useState(0);const[price,setPrice]=useState(110);const[ran,setRan]=useState(false);const rows=[['MAT-01',100,100],['MAT-02',105,price],['MAT-03',80,75]] as [string,number,number][];const steps=['选择示例文件','按物料编码匹配','比较价格与容差','导出核对结果'];const review=useHumanReview(JSON.stringify([price,tolerance,ran]),['物料对应关系、销售价与建议价已核对','偏差计算、容差和超差记录已逐项复核'],ran);return <><div className="desktop-files"><span><FileSpreadsheet/>销售价_示例.csv</span><ArrowRight size={18}/><span><FileSpreadsheet/>建议价_示例.csv</span><small>演示内置数据，不访问本机文件</small></div><div className="demo-split"><section><h3>WorkBuddy 类任务：把核价流程说清楚</h3><RangeField label="允许价格偏差" value={tolerance} onChange={v=>{setTolerance(v);setRan(false)}} max={10} step={.5} unit="%"/><NumberField label="MAT-02 销售价" value={price} onChange={v=>{setPrice(v);setRan(false)}}/><div className="route-steps">{steps.map((s,i)=><button key={s} className={step===i?'active':''} onClick={()=>setStep(i)}><span>0{i+1}</span>{s}<ArrowRight size={15}/></button>)}</div><p>{['仅选择两份演示 CSV，确认列名与单位。','用物料编码精确关联，名称只作显示。','偏差 = (销售价 − 建议价) / 建议价，超过容差标记。','保留原文件，导出新核对表，供业务复核。'][step]}</p><Button onClick={()=>{setRan(true);setStep(3)}}>运行演示核价</Button></section><section>{ran?<><SmallTable headers={['物料','建议 / 销售','偏差','状态']} rows={rows.map(([id,suggested,actual])=>[id,`${suggested} / ${actual}`,`${((actual-suggested)/suggested*100).toFixed(2)}%`,Math.abs((actual-suggested)/suggested*100)>tolerance?'需复核':'容差内'])}/><ResultBox title="核价完成">金额比较由规则计算。重复编码、缺失单价与单位不一致应在正式流程中另设异常分支。</ResultBox><ReviewChecklist review={review}/><Button variant="outline" onClick={()=>review.request()&&downloadText('price-check.csv','\uFEFF物料,建议价,销售价,偏差百分比\n'+rows.map(([id,a,b])=>`${id},${a},${b},${((b-a)/a*100).toFixed(2)}`).join('\n'),'text/csv;charset=utf-8')}><Download size={16}/>下载核价结果</Button></>:<div className="demo-empty"><FileSpreadsheet size={28}/><p>指定匹配字段、容差和交付文件，再运行核价。</p></div>}</section></div></>}
export default function ToolDemo({category}:{category:string}){const[sub,setSub]=useState('meeting');if(category==='meetings')return <><Tabs value={sub} onValueChange={setSub}><TabsList><TabsTrigger value="meeting">会议工作台</TabsTrigger><TabsTrigger value="mobile">移动办公</TabsTrigger></TabsList></Tabs>{sub==='meeting'?<MeetingStudio/>:<MobileDemo/>}</>;if(category==='spreadsheets')return <SheetStudio/>;if(category==='presentations')return <PptStudio/>;if(category==='writing')return <WritingDemo/>;if(category==='images')return <ImageDemo/>;if(category==='video')return <VideoDemo/>;if(category==='research')return <ResearchDemo/>;return <DesktopDemo/>}
