"use client";
import {useState,useRef,useEffect,useCallback} from 'react';
import {Film,Play,Pause,Upload,Plus,Scissors,ArrowLeft,ArrowRight,Download,Volume2,VolumeX,Type,Music2,Mic,Subtitles,Trash2,ChevronLeft,ChevronRight,GripVertical,Check,ExternalLink,Sparkles,Copy,Maximize2,LoaderCircle,Undo2,Info} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Progress} from '@/components/ui/progress';
import {videoAssets,videoSteps,videoLessons,initialVideoProject,duration,clipStart,locateClip,timecode,uid,moveClip,splitClip,captionsFromClips,toSrt,parseSrt,saveVideoFile,videoPrompt,type VideoAsset,type VideoProject,type VideoClip} from '@/lib/video-workbench';
import {drawVideoFrame,loadMedia,seekMedia,exportVideo} from '@/lib/video-render';

type PreviewProps={project:VideoProject;assets:VideoAsset[];time:number;playing:boolean;onTime:(time:number)=>void;onEnd:()=>void;onError:(message:string)=>void};
function VideoPreview({project,assets,time,playing,onTime,onEnd,onError}:PreviewProps){
 const canvas=useRef<HTMLCanvasElement>(null),video=useRef<HTMLVideoElement>(null),projectRef=useRef(project),timeRef=useRef(time),sounds=useRef<HTMLAudioElement[]>([]);
 projectRef.current=project;timeRef.current=time;
 const callbacks=useRef({onTime,onEnd,onError});callbacks.current={onTime,onEnd,onError};
 useEffect(()=>{sounds.current=project.sounds.map(s=>{const a=new Audio(s.src);a.preload='metadata';a.volume=s.volume;return a});return()=>{sounds.current.forEach(a=>{a.pause();a.removeAttribute('src');a.load()});sounds.current=[]}},[project.sounds]);
 useEffect(()=>{if(video.current)video.current.volume=project.originalVolume;},[project.originalVolume]);
 useEffect(()=>{if(playing)return;const abort=new AbortController();const v=video.current;const c=canvas.current;if(!v||!c)return;v.pause();sounds.current.forEach(a=>a.pause());const found=locateClip(project.clips,time);if(!found){drawVideoFrame(c,null,project,time);return}const asset=assets.find(a=>a.id===found.clip.assetId);if(!asset)return;void (async()=>{try{await loadMedia(v,asset.src,abort.signal);await seekMedia(v,found.clip.in+found.offset,abort.signal);if(!abort.signal.aborted)drawVideoFrame(c,v,project,time)}catch(error){if(!abort.signal.aborted)callbacks.current.onError(error instanceof Error?error.message:'视频暂时无法播放')}})();return()=>abort.abort()},[playing,time,project,assets]);
 useEffect(()=>{if(!playing)return;const abort=new AbortController();let raf=0;const v=video.current,c=canvas.current;if(!v||!c)return;const found=locateClip(projectRef.current.clips,timeRef.current);if(!found)return;void(async()=>{try{for(let index=found.index;index<projectRef.current.clips.length;index++){
  if(abort.signal.aborted)return;const clip=projectRef.current.clips[index],asset=assets.find(a=>a.id===clip.assetId);if(!asset)throw new Error('缺少视频素材，请重新载入。');const start=clipStart(projectRef.current.clips,index);
  await loadMedia(v,asset.src,abort.signal);await seekMedia(v,clip.in+(index===found.index?found.offset:0),abort.signal);if(abort.signal.aborted)return;await v.play();
  await new Promise<void>((resolve,reject)=>{const cancel=()=>{cancelAnimationFrame(raf);reject(new DOMException('停止','AbortError'))};abort.signal.addEventListener('abort',cancel,{once:true});let last=0;const frame=()=>{if(abort.signal.aborted)return;const now=start+Math.max(0,Math.min(v.currentTime-clip.in,clip.out-clip.in));drawVideoFrame(c,v,projectRef.current,now);if(performance.now()-last>70){callbacks.current.onTime(now);last=performance.now()}projectRef.current.sounds.forEach((s,i)=>{const a=sounds.current[i],target=now-s.start;if(!a)return;if(target>=0&&target<s.duration){if(Math.abs(a.currentTime-target)>.3)a.currentTime=target;if(a.paused)void a.play().catch(()=>{})}else a.pause()});if(v.currentTime>=clip.out-.025||v.ended){abort.signal.removeEventListener('abort',cancel);resolve();return}raf=requestAnimationFrame(frame)};raf=requestAnimationFrame(frame)});
  v.pause();sounds.current.forEach(a=>a.pause());
 }if(!abort.signal.aborted){callbacks.current.onTime(duration(projectRef.current.clips));callbacks.current.onEnd()}}catch(error){if(!abort.signal.aborted){callbacks.current.onError(error instanceof Error?error.message:'播放失败');callbacks.current.onEnd()}}})();return()=>{abort.abort();cancelAnimationFrame(raf);v.pause();sounds.current.forEach(a=>a.pause())}},[playing,project.clips,assets]);
 return <><video ref={video} className="video-decoder" playsInline preload="metadata" crossOrigin="anonymous" aria-hidden="true"/><canvas ref={canvas} width={1280} height={720} aria-label="当前视频剪辑预览，包含文字与字幕轨道"/></>;
}

function NumberInput({label,value,onChange,min=0,max=120}:{label:string;value:number;onChange:(n:number)=>void;min?:number;max?:number}){return <label className="video-field"><span>{label}</span><Input type="number" aria-label={label} step="0.1" min={min} max={max} value={Math.round(value*10)/10} onChange={e=>{const n=Number(e.target.value);if(Number.isFinite(n))onChange(Math.max(min,Math.min(max,n)))}}/></label>}

export default function VideoStudio(){
 const[projects,setProjects]=useState<Record<string,VideoProject>>(()=>({product:initialVideoProject(),warehouse:initialVideoProject('warehouse')}));
 const[caseId,setCaseId]=useState('product'),[step,setStep]=useState(0),[assets,setAssets]=useState(videoAssets),[selected,setSelected]=useState('p1'),[time,setTime]=useState(0),[playing,setPlaying]=useState(false),[notice,setNotice]=useState(''),[preview,setPreview]=useState<VideoAsset|null>(null),[exporting,setExporting]=useState(false),[percent,setPercent]=useState(0),[exported,setExported]=useState<{url:string;name:string}|null>(null),[aiBusy,setAiBusy]=useState(false),[aiDraft,setAiDraft]=useState<{title:string;narration:string}[]|null>(null),[aiEngine,setAiEngine]=useState(''),[history,setHistory]=useState<VideoProject[]>([]),[checked,setChecked]=useState<boolean[]>([false,false,false]);
 const fileInput=useRef<HTMLInputElement>(null),subtitleInput=useRef<HTMLInputElement>(null),soundInput=useRef<HTMLInputElement>(null),stage=useRef<HTMLDivElement>(null),root=useRef<HTMLElement>(null),dragging=useRef<number|null>(null),abortExport=useRef<AbortController|null>(null),abortAI=useRef<AbortController|null>(null),objectUrls=useRef<string[]>([]),resultUrl=useRef<string|null>(null);
 const project=projects[caseId],total=duration(project.clips),selectedIndex=project.clips.findIndex(c=>c.id===selected),clip=project.clips[selectedIndex],asset=clip?assets.find(a=>a.id===clip.assetId):undefined,lesson=videoLessons[step],locked=exporting||aiBusy;
 useEffect(()=>()=>{abortExport.current?.abort();abortAI.current?.abort();objectUrls.current.forEach(u=>URL.revokeObjectURL(u));if(resultUrl.current)URL.revokeObjectURL(resultUrl.current);if(typeof speechSynthesis!=='undefined')speechSynthesis.cancel()},[]);
 const update=(patch:Partial<VideoProject>,record=true)=>{setPlaying(false);if(record)setHistory(h=>[...h.slice(-19),structuredClone(project)]);setProjects(p=>({...p,[caseId]:{...p[caseId],...patch}}));setChecked([false,false,false]);if(exported){URL.revokeObjectURL(exported.url);resultUrl.current=null;setExported(null)}};
 const updateClip=(patch:Partial<VideoClip>)=>{if(!clip)return;update({clips:project.clips.map(c=>c.id===clip.id?{...c,...patch}:c)});};
 const seek=(t:number)=>{setPlaying(false);setTime(Math.max(0,Math.min(total,t)))};
 const selectClip=(index:number)=>{setSelected(project.clips[index].id);seek(clipStart(project.clips,index))};
 const changeStep=(next:number)=>{setPlaying(false);setStep(next);setNotice('');};
 const onError=useCallback((text:string)=>setNotice(text),[]),onEnd=useCallback(()=>setPlaying(false),[]);
 const switchCase=(id:string)=>{setPlaying(false);setCaseId(id);setTime(0);setSelected(projects[id].clips[0]?.id||'');setHistory([]);setAiDraft(null);setChecked([false,false,false]);setNotice('两条练习独立编辑，可随时切回。');setExported(null)};
 const activeAssets=assets.filter(a=>a.local||(caseId==='product'?a.id==='service':a.id.startsWith('warehouse')));
 const captionWarnings=project.captions.filter(c=>c.end<=c.start||c.start<0||c.end>total+.01||c.text.replace(/\s/g,'').length/Math.max(.1,c.end-c.start)>8);
 function addClip(a:VideoAsset){if(project.clips.length>=16||total>=115){setNotice('这次练习最多 16 段、总长 120 秒。先删减一些片段。');return}const c={id:uid(),assetId:a.id,in:0,out:Math.min(a.duration,6,120-total),title:a.name,narration:''};update({clips:[...project.clips,c]});setSelected(c.id);setTime(total);setNotice('已添加到主视频轨，可在第 3 步调整取用范围。')}
 async function uploadVideo(file?:File){if(!file)return;if(file.size>200*1024*1024){setNotice('请选择 200 MB 以内的视频，较长素材可以先截取。');return}const url=URL.createObjectURL(file),v=document.createElement('video');try{await loadMedia(v,url);if(!Number.isFinite(v.duration)||v.duration<=0)throw new Error('没有读到视频时长。');objectUrls.current.push(url);const a:VideoAsset={id:uid(),name:file.name,src:url,duration:v.duration,origin:file.name,sourceStart:0,hasAudio:true,local:true};setAssets(old=>[...old,a]);setNotice('已载入本地视频，点击“加入剪辑”。文件仅在本页使用，刷新后需重新选择。')}catch(error){URL.revokeObjectURL(url);setNotice(error instanceof Error?error.message:'请使用浏览器可播放的 MP4 / WebM。')}finally{v.removeAttribute('src');v.load();if(fileInput.current)fileInput.current.value=''}}
 async function uploadSound(file?:File){if(!file)return;if(file.size>50*1024*1024){setNotice('请选择 50 MB 以内的音频。');return}if(project.sounds.length>=4){setNotice('最多可添加 4 条声音轨道。');return}const url=URL.createObjectURL(file),a=document.createElement('audio');try{await loadMedia(a,url);if(!Number.isFinite(a.duration))throw new Error('无法读取音轨时长。');objectUrls.current.push(url);update({sounds:[...project.sounds,{id:uid(),name:file.name,src:url,duration:a.duration,start:0,volume:.8}]});setNotice('音轨已加入，可播放试听并调整起点、音量。')}catch(error){URL.revokeObjectURL(url);setNotice(error instanceof Error?error.message:'音频无法读取。')}finally{a.removeAttribute('src');a.load();if(soundInput.current)soundInput.current.value=''}}
 async function importSubtitles(file?:File){if(!file)return;try{if(file.size>500000)throw new Error('字幕文件过大，请选择本次短片的 SRT。');const captions=parseSrt(await file.text());update({captions,showCaptions:true});setNotice(`已导入 ${captions.length} 条字幕，请按当前成片时间校对。`)}catch(error){setNotice(error instanceof Error?error.message:'字幕读取失败')}finally{if(subtitleInput.current)subtitleInput.current.value=''}}
 async function copy(text:string){try{await navigator.clipboard.writeText(text);setNotice('已复制。')}catch{setNotice('复制失败，请从文本框手动复制。')}}
 async function improveScript(){const question=videoPrompt(project);if(question.length>600){setNotice('镜头描述过长，请缩短标题或先处理少量镜头。');return}setPlaying(false);setAiBusy(true);setAiDraft(null);const controller=new AbortController();abortAI.current=controller;setNotice('正在请 AI 根据镜头描述改写旁白…');try{const response=await fetch('/api/video-script',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question}),signal:controller.signal});const data=await response.json() as {text:string;error?:string;engine:string};if(!response.ok)throw new Error(data.error||'AI 暂时不可用，可以继续手动写脚本。');const cleaned=data.text.replace(/^```(?:json)?\s*/,'').replace(/\s*```$/,'');const parsed=JSON.parse(cleaned);if(!Array.isArray(parsed.shots)||parsed.shots.length!==project.clips.length||parsed.shots.some((s:unknown)=>!s||typeof s!=='object'||typeof (s as {title:unknown}).title!=='string'||typeof (s as {narration:unknown}).narration!=='string'))throw new Error('AI 返回的格式不适合直接应用，请重试或手动填写。');setAiDraft(parsed.shots.map((s:{title:string;narration:string})=>({title:s.title.slice(0,40),narration:s.narration.slice(0,200)})));setAiEngine(data.engine);setNotice('旁白建议已生成，确认后再应用。')}catch(error){setNotice(controller.signal.aborted?'已停止生成。':error instanceof Error?error.message:'AI 暂时不可用。')}finally{setAiBusy(false);abortAI.current=null}}
 async function render(){setPlaying(false);setNotice('');setPercent(0);setExporting(true);const controller=new AbortController();abortExport.current=controller;try{const result=await exportVideo(structuredClone(project),assets,setPercent,controller.signal);if(resultUrl.current)URL.revokeObjectURL(resultUrl.current);const url=URL.createObjectURL(result.blob);resultUrl.current=url;const name=`${project.name}.${result.extension}`;setExported({url,name});setNotice('视频已生成，可以下载并播放检查。')}catch(error){setNotice(controller.signal.aborted?'已取消导出，剪辑内容保留。':error instanceof Error?error.message:'导出失败，请重试。')}finally{setExporting(false);abortExport.current=null}}
 function downloadPlan(){const data={format:'ai-practice-video-plan-v1',name:project.name,goal:project.goal,audience:project.audience,totalSeconds:total,formatNotes:'剪辑清单，不是剪映工程；本地媒体需另行保存。',clips:project.clips.map((c,i)=>{const a=assets.find(x=>x.id===c.assetId)!;return {order:i+1,source:a.origin,sourceIn:a.sourceStart+c.in,sourceOut:a.sourceStart+c.out,timelineIn:clipStart(project.clips,i),title:c.title,narration:c.narration}}),captions:project.captions,sounds:project.sounds.map(({src,...s})=>s)};saveVideoFile(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),`${project.name}-剪辑清单.json`)}
 return <section className="video-studio" ref={root} aria-label="视频剪辑工作台">
  <div className="video-studio-top"><div><span className="video-kicker"><Film size={15}/> VIDEO WORKSHOP</span><h3>把素材，剪成一段好故事。</h3><p>跟着 6 步完成短片，也可以直接进入需要调整的步骤。</p></div><Tabs value={caseId} onValueChange={id=>{if(!locked)switchCase(id)}}><TabsList><TabsTrigger disabled={locked} value="product">01 产品介绍</TabsTrigger><TabsTrigger disabled={locked} value="warehouse">02 场景短片</TabsTrigger></TabsList></Tabs></div>
  <nav className="video-stepper" aria-label="视频制作步骤">{videoSteps.map((s,i)=><button key={s} disabled={locked} aria-current={step===i?'step':undefined} className={step===i?'active':''} onClick={()=>changeStep(i)}><span>{String(i+1).padStart(2,'0')}</span>{s}</button>)}</nav>
  <div className="video-workspace">
   <aside className="video-inspector"><div className="video-guide-heading"><small>STEP 0{step+1}</small><h4>{videoSteps[step]}</h4></div>
    <fieldset disabled={locked} className="video-controls">
    {step===0&&<><p className="video-lead">{caseId==='product'?'从热线咨询到机器人问答，讲清产品的一次使用过程。':'用四个实拍片段，剪出有起承转合的仓储场景短片。'}</p><label className="video-field"><span>这段片子讲什么</span><Textarea aria-label="视频目的" value={project.goal} maxLength={200} onChange={e=>update({goal:e.target.value},false)} rows={2}/></label><label className="video-field"><span>给谁看</span><Input aria-label="视频观众" value={project.audience} maxLength={80} onChange={e=>update({audience:e.target.value},false)}/></label><div className="video-spec"><span>16:9 横屏</span><span>720p 练习</span><span>当前 {total.toFixed(1)} 秒</span></div><h5>素材箱</h5><div className="video-assets">{activeAssets.map(a=><article key={a.id}><button className="video-asset-preview" onClick={()=>{setPlaying(false);setPreview(a)}} aria-label={`预览素材：${a.name}`}>{a.poster?<img src={a.poster} alt="" loading="lazy"/>:<Film size={24}/>}<Play size={16}/></button><div><strong>{a.name}</strong><small>{timecode(a.duration)} · {a.local?'本地素材':a.hasAudio?'用户素材 · 有原声':'用户素材 · 无音轨'}</small><button onClick={()=>addClip(a)}><Plus size={13}/>加入剪辑</button></div></article>)}</div><Button variant="outline" onClick={()=>fileInput.current?.click()}><Upload size={15}/>添加自己的 / AI 生成片段</Button><p className="video-note">示例均截取自你提供的视频；点缩略图可预览。也可导入 MP4 / WebM，直接开始剪。</p></>}
    {step===1&&<><p className="video-lead">逐镜头写画面作用和旁白。选中右侧片段后，在这里修改。</p><div className="video-mini-shots">{project.clips.map((c,i)=><button key={c.id} className={selected===c.id?'active':''} onClick={()=>selectClip(i)}>{i+1}<span>{c.title}</span><small>{(c.out-c.in).toFixed(1)}s</small></button>)}</div>{clip&&<><label className="video-field"><span>镜头作用</span><Input aria-label="镜头作用" maxLength={40} value={clip.title} onChange={e=>updateClip({title:e.target.value})}/></label><label className="video-field"><span>旁白草稿</span><Textarea aria-label="旁白草稿" maxLength={200} rows={3} value={clip.narration} onChange={e=>updateClip({narration:e.target.value})}/></label><p className="video-note">{clip.narration.length} 字 / {(clip.out-clip.in).toFixed(1)} 秒 · 先试听，再决定是否缩句。</p></>}<Button onClick={improveScript} disabled={!project.clips.length}><Sparkles size={15}/>AI 帮我改写旁白</Button><p className="video-note">按上面的文字和镜头描述改写，不会上传视频。建议确认后再应用。</p><details className="video-help"><summary>缺少一个镜头？用 AI 补镜</summary><p>为过渡或氛围补 3–5 秒，保持主体和画幅一致；产品操作继续用真实录屏。</p><Textarea aria-label="AI补镜提示词" readOnly rows={5} value={`为“${project.goal}”补一个 4 秒过渡镜头。16:9，主体为整洁的工业仓储空间，缓慢向前推进，动作自然，光线与现有素材一致。保留稳定结构，不生成文字、标识或未经确认的产品界面。作为概念补镜，不代表真实项目。`}/><div className="video-link-row"><a href="https://jimeng.jianying.com/" target="_blank" rel="noopener noreferrer">去即梦补镜 <ExternalLink size={13}/></a><button onClick={()=>{setStep(0);fileInput.current?.click()}}>导入生成的片段</button></div></details></>}
    {step===2&&<><p className="video-lead">选片段，去掉等待，再把镜头接起来。视频轨支持拖动排序。</p>{clip&&asset?<><div className="video-selected-label">片段 {selectedIndex+1}<strong>{clip.title}</strong></div><div className="video-pair"><NumberInput label="素材入点（秒）" value={clip.in} max={clip.out-.25} onChange={v=>{updateClip({in:v});setTime(clipStart(project.clips,selectedIndex))}}/><NumberInput label="素材出点（秒）" value={clip.out} min={clip.in+.25} max={Math.min(asset.duration,clip.in+120-(total-(clip.out-clip.in)))} onChange={v=>updateClip({out:v})}/></div><p className="video-note">原始文件 {timecode(asset.sourceStart+clip.in,true)}–{timecode(asset.sourceStart+clip.out,true)}，保留 {(clip.out-clip.in).toFixed(1)} 秒。</p><div className="video-button-grid"><Button variant="outline" onClick={()=>{const next=splitClip(project.clips,time);if(!next){setNotice('把播放头移到片段内部，离两端至少 0.25 秒，再剪开。');return}if(next.length>16){setNotice('最多 16 个片段。');return}update({clips:next});setNotice('已在播放头处分成两段，可分别裁短、移动或删除。')}}><Scissors size={15}/>在播放头剪开</Button><Button variant="outline" disabled={project.clips.length<2} onClick={()=>{const next=project.clips.filter(c=>c.id!==selected);update({clips:next});setSelected(next[0]?.id||'');setTime(0);setNotice('已删除片段，后续镜头自动衔接。')}}><Trash2 size={15}/>删除选中段</Button><Button variant="outline" disabled={selectedIndex<=0} onClick={()=>{update({clips:moveClip(project.clips,selectedIndex,selectedIndex-1)});setTime(0)}}><ChevronLeft size={15}/>前移</Button><Button variant="outline" disabled={selectedIndex===project.clips.length-1} onClick={()=>{update({clips:moveClip(project.clips,selectedIndex,selectedIndex+1)});setTime(0)}}>后移<ChevronRight size={15}/></Button></div><div className="video-divider"/><label className="video-field"><span><Type size={14}/>文字轨 · 开场标题</span><Input aria-label="开场标题" value={project.title} maxLength={60} onChange={e=>update({title:e.target.value})} placeholder="留空即关闭标题"/></label><NumberInput label="标题展示至（秒）" value={project.titleEnd} min={0} max={Math.min(total,20)} onChange={v=>update({titleEnd:v})}/><p className="video-note">添加文字后，可在预览中看位置。调整镜头长度后，记得到下一步重新核对字幕时间。</p></>:<p>先在素材箱中添加一个片段。</p>}</>}
    {step===3&&<><p className="video-lead">新增字幕可改字、校时、导出 SRT；原片中已有的字幕会保留。</p><div className="video-button-grid"><Button variant="outline" onClick={()=>{update({captions:captionsFromClips(project.clips),showCaptions:true});setNotice('已按镜头文案建立字幕草稿；不是语音识别结果，请逐条校对。')}}><Subtitles size={15}/>按文案建立字幕</Button><Button variant="outline" onClick={()=>subtitleInput.current?.click()}><Upload size={15}/>导入 SRT</Button></div><label className="video-switch">显示新增字幕<Switch aria-label="显示新增字幕" checked={project.showCaptions} onCheckedChange={v=>update({showCaptions:v})}/></label><label className="video-field"><span>字幕位置</span><Select value={project.captionPosition} onValueChange={v=>update({captionPosition:v as 'top'|'bottom'})}><SelectTrigger aria-label="字幕位置"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="top">上方 · 避开原片字幕</SelectItem><SelectItem value="bottom">下方</SelectItem></SelectContent></Select></label><p className="video-note">在右侧逐条编辑。超过片长或每秒超过 8 个字会提示校对，不会偷偷截掉文字。</p><details className="video-help"><summary>怎样用 AI 识别字幕？</summary><ol><li>在剪映导入含人声的原视频。</li><li>使用智能字幕 / 识别字幕，核对专有名词与数字。</li><li>导出 SRT，在这里导入；如果剪辑已变，重新对齐成片时间。</li></ol><a href="https://www.capcut.cn/learning" target="_blank" rel="noopener noreferrer">剪映创作课堂 <ExternalLink size={13}/></a></details></>}
    {step===4&&<><p className="video-lead">原声、配音、音乐分开控制。替换旁白时，先调低或关闭原声。</p><label className="video-range"><span><Volume2 size={15}/>原视频音量 <output>{Math.round(project.originalVolume*100)}%</output></span><Slider aria-label="原视频音量" min={0} max={1} step={.05} value={[project.originalVolume]} onValueChange={v=>update({originalVolume:v[0]},false)}/></label>{caseId==='warehouse'&&<p className="video-note">这份仓储素材没有音轨，添加配音或音乐后再导出就会有声音。</p>}<label className="video-field"><span>配音稿</span><Textarea readOnly aria-label="完整配音稿" rows={5} value={project.clips.map(c=>c.narration).filter(Boolean).join('\n')}/></label><div className="video-button-grid"><Button variant="outline" onClick={()=>copy(project.clips.map(c=>c.narration).filter(Boolean).join('\n'))}><Copy size={15}/>复制配音稿</Button><Button variant="outline" onClick={()=>{if(!('speechSynthesis' in window)){setNotice('浏览器不支持系统朗读，请在剪映试听。');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(project.clips.map(c=>c.narration).join('。'));u.lang='zh-CN';u.rate=.95;speechSynthesis.speak(u);setNotice('正在用系统语音试听文字；正式导出请添加配音音频。')}}><Play size={15}/>试听文案</Button><Button variant="outline" onClick={()=>{if('speechSynthesis' in window)speechSynthesis.cancel()}}>停止试听</Button><Button onClick={()=>soundInput.current?.click()}><Plus size={15}/>添加声音轨道</Button></div><p className="video-note">系统试听不随视频导出。把剪映 AI 配音或自己的录音导出为 MP3 / WAV 后添加，声音就会进入成片。</p>{project.sounds.map(s=><div className="video-sound-card" key={s.id}><div><Music2 size={14}/><strong>{s.name}</strong><button aria-label={`删除音轨：${s.name}`} onClick={()=>update({sounds:project.sounds.filter(x=>x.id!==s.id)})}><Trash2 size={14}/></button></div><NumberInput label={`音轨起点：${s.name}`} value={s.start} max={total-.1} onChange={v=>update({sounds:project.sounds.map(x=>x.id===s.id?{...x,start:v}:x)},false)}/><label className="video-range"><span>音量 <output>{Math.round(s.volume*100)}%</output></span><Slider aria-label={`音量：${s.name}`} min={0} max={1} step={.05} value={[s.volume]} onValueChange={v=>update({sounds:project.sounds.map(x=>x.id===s.id?{...x,volume:v[0]}:x)},false)}/></label><small>{timecode(s.duration)} · 超出成片的部分不导出</small></div>)}<a className="video-tool-link" href="https://www.capcut.cn/" target="_blank" rel="noopener noreferrer">去剪映制作 AI 配音 <ExternalLink size={14}/></a></>}
    {step===5&&<><p className="video-lead">完整播放一次，确认画面、文字和声音，再生成文件。</p><div className="video-review">{['镜头衔接自然，开头和结尾完整','字幕、产品名、数字已校对','声音清楚，音乐不盖住人声'].map((text,i)=><label key={text}><Switch aria-label={text} checked={checked[i]} onCheckedChange={v=>setChecked(c=>c.map((x,j)=>i===j?v:x))}/>{text}</label>)}</div><div className="video-export-summary"><strong>{total.toFixed(1)} 秒</strong><span>{project.clips.length} 个片段 · {project.captions.length} 条字幕</span><span>1280 × 720 · 30 fps 导出</span></div>{captionWarnings.length>0&&<p className="video-warning">有 {captionWarnings.length} 条字幕需检查时长或阅读速度，可返回第 4 步调整。</p>}<Button className="video-export-button" onClick={render} disabled={!project.clips.length||total>120}><Download size={16}/>生成当前剪辑视频</Button><p className="video-note">生成约需 {Math.ceil(total)} 秒，请保持页面在前台。格式按浏览器支持输出 MP4 或 WebM，文字和导入音轨会合成进去。</p><div className="video-button-grid"><Button variant="outline" disabled={!project.captions.length} onClick={()=>saveVideoFile(new Blob([toSrt(project.captions,total)],{type:'text/plain;charset=utf-8'}),`${project.name}.srt`)}>下载字幕 SRT</Button><Button variant="outline" onClick={downloadPlan}>下载剪辑清单</Button></div><p className="video-note">剪辑清单记录原文件、入出点与旁白，方便迁移到剪映；它不是剪映工程文件。正式交付可用原素材导出 1080p MP4。</p></>}
    </fieldset>
    {aiBusy&&<div className="video-working"><LoaderCircle size={16} className="video-spin"/><span>正在改写旁白…</span><Button size="sm" variant="ghost" onClick={()=>abortAI.current?.abort()}>停止</Button></div>}
   </aside>
   <div className="video-edit-column"><div className="video-monitor-toolbar"><span><span className={playing?'video-live-dot':''}/>{project.name}</span><div><Button disabled={locked||!history.length} size="sm" variant="ghost" onClick={()=>{const previous=history.at(-1)!;setProjects(p=>({...p,[caseId]:previous}));setHistory(h=>h.slice(0,-1));setPlaying(false);setTime(0);setSelected(previous.clips[0]?.id||'');setChecked([false,false,false]);setExported(null)}} aria-label="撤销上次编辑"><Undo2 size={16}/></Button><Button size="sm" variant="ghost" aria-label="放大视频预览" onClick={()=>stage.current?.requestFullscreen().catch(()=>setNotice('当前浏览器不支持全屏预览。'))}><Maximize2 size={16}/></Button></div></div>
    <div className="video-monitor" ref={stage}><VideoPreview project={project} assets={assets} time={time} playing={playing} onTime={setTime} onEnd={onEnd} onError={onError}/>{!project.clips.length&&<div className="video-no-clips">从素材箱添加第一个片段</div>}</div>
    <div className="video-transport"><Button disabled={locked||!project.clips.length} size="sm" variant="ghost" aria-label={playing?'暂停预览':'播放当前剪辑'} onClick={()=>{if(!playing&&time>=total-.05)setTime(0);setPlaying(v=>!v)}}>{playing?<Pause size={18}/>:<Play size={18}/>}</Button><span>{timecode(time,true)} <small>/ {timecode(total,true)}</small></span><Slider disabled={locked} aria-label="成片播放位置" value={[Math.min(time,total)]} min={0} max={Math.max(.1,total)} step={.1} onValueChange={v=>seek(v[0])}/><Button disabled={locked} size="sm" variant="ghost" aria-label={project.originalVolume?'关闭原声':'打开原声'} onClick={()=>update({originalVolume:project.originalVolume?0:.8},false)}>{project.originalVolume?<Volume2 size={17}/>:<VolumeX size={17}/>}</Button></div>
    <div className="video-timeline"><div className="video-timeline-heading"><strong><Scissors size={15}/>剪辑时间线</strong><span>{project.clips.length} 段 · 拖动换序</span><Button disabled={locked} size="sm" variant="ghost" onClick={()=>{setStep(4);soundInput.current?.click()}}><Plus size={14}/>音轨</Button><Button disabled={locked} size="sm" variant="ghost" onClick={()=>{setStep(2);if(!project.title)update({title:'输入开场标题',titleEnd:3})}}><Plus size={14}/>文字</Button></div>
     <div className="video-timeline-scroll"><div className="video-timeline-inner"><div className="video-ruler"><span/>{[0,.25,.5,.75,1].map(n=><span key={n}>{timecode(total*n)}</span>)}</div><div className="video-lane"><span className="video-lane-label"><Film size={14}/>主视频</span><div className="video-clips" style={{position:'relative'}}>{project.clips.map((c,i)=>{const a=assets.find(a=>a.id===c.assetId);return <button disabled={locked} key={c.id} className={`video-clip ${selected===c.id?'selected':''}`} style={{flex:`${c.out-c.in} 0 0`}} draggable={!locked} onDragStart={()=>{dragging.current=i}} onDragEnd={()=>{dragging.current=null}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(dragging.current!==null){update({clips:moveClip(project.clips,dragging.current,i)});setTime(0);dragging.current=null}}} onClick={()=>selectClip(i)} aria-label={`选择片段 ${i+1}：${c.title}`}><div className="video-clip-picture" style={(c.poster||a?.poster)?{backgroundImage:`url(${c.poster||a?.poster})`}:undefined}/><span><GripVertical size={12}/>{i+1} · {c.title}</span><small>{(c.out-c.in).toFixed(1)}s</small></button>})}<i className="video-playhead" style={{left:`${Math.min(100,time/Math.max(.1,total)*100)}%`}} aria-hidden="true"/></div></div>
     <div className="video-lane"><span className="video-lane-label"><Type size={14}/>文字</span><div className="video-track-strip">{project.title&&<button disabled={locked} style={{left:0,width:`${Math.min(100,project.titleEnd/Math.max(.1,total)*100)}%`}} onClick={()=>{setStep(2);seek(0)}}>{project.title}</button>}</div></div><div className="video-lane"><span className="video-lane-label"><Subtitles size={14}/>字幕</span><div className="video-track-strip captions">{project.captions.map(c=><button disabled={locked} key={c.id} style={{left:`${Math.min(100,c.start/Math.max(.1,total)*100)}%`,width:`${Math.max(0,Math.min(c.end,total)-c.start)/Math.max(.1,total)*100}%`}} onClick={()=>{setStep(3);seek(c.start)}}>{c.text}</button>)}{!project.captions.length&&<button disabled={locked} className="video-empty-track" onClick={()=>setStep(3)}>＋ 创建或导入字幕</button>}</div></div>{project.sounds.map(s=><div className="video-lane" key={s.id}><span className="video-lane-label"><Music2 size={14}/>声音</span><div className="video-track-strip sound"><button disabled={locked} style={{left:`${s.start/Math.max(.1,total)*100}%`,width:`${Math.max(0,Math.min(s.duration,total-s.start))/Math.max(.1,total)*100}%`}} onClick={()=>setStep(4)}>{s.name}</button></div></div>)}</div></div>
    </div>
    {step===1&&aiDraft&&<div className="video-ai-draft"><div><h5><Sparkles size={16}/>旁白建议</h5><small>{aiEngine}</small></div>{aiDraft.map((s,i)=><p key={i}><strong>{i+1}. {s.title}</strong>{s.narration}</p>)}<Button onClick={()=>{update({clips:project.clips.map((c,i)=>({...c,...aiDraft[i]}))});setAiDraft(null);setNotice('已应用旁白；字幕仍保留原版本，需要时在第 4 步重新建立。')}}><Check size={15}/>应用到分镜</Button><Button variant="ghost" onClick={()=>setAiDraft(null)}>保留原稿</Button></div>}
    {step===3&&<div className="video-caption-editor"><div><h5><Subtitles size={16}/>字幕校对 · {project.captions.length} 条</h5><Button disabled={locked} size="sm" variant="outline" onClick={()=>update({captions:[...project.captions,{id:uid(),start:Math.min(time,Math.max(0,total-1)),end:Math.min(total,time+3),text:'填写字幕'}]})}><Plus size={14}/>添加一条</Button></div>{project.captions.length===0?<p>按镜头文案建立草稿，或者导入 AI 识别后导出的 SRT。</p>:project.captions.map((c,i)=><div className="video-caption-row" key={c.id}><button onClick={()=>seek(c.start)} aria-label={`播放第 ${i+1} 条字幕`}>{String(i+1).padStart(2,'0')}<Play size={12}/></button><div className="video-caption-times"><NumberInput label={`字幕${i+1}开始`} value={c.start} max={Math.max(total,c.end)} onChange={v=>update({captions:project.captions.map(x=>x.id===c.id?{...x,start:v}:x)},false)}/><NumberInput label={`字幕${i+1}结束`} value={c.end} max={Math.max(total,c.end)} onChange={v=>update({captions:project.captions.map(x=>x.id===c.id?{...x,end:v}:x)},false)}/></div><div><Textarea aria-label={`字幕${i+1}内容`} value={c.text} maxLength={300} rows={2} onChange={e=>update({captions:project.captions.map(x=>x.id===c.id?{...x,text:e.target.value}:x)},false)}/>{captionWarnings.some(x=>x.id===c.id)&&<small className="video-warning">检查时间或缩短文案</small>}</div><button onClick={()=>update({captions:project.captions.filter(x=>x.id!==c.id)})} aria-label={`删除字幕${i+1}`}><Trash2 size={15}/></button></div>)}</div>}
    {step===5&&(exporting||exported)&&<div className="video-export-result" aria-live="polite">{exporting?<><h5><LoaderCircle className="video-spin" size={16}/>正在生成视频 · {Math.round(percent)}%</h5><Progress value={percent}/><p>请保持本页在前台，逐帧合成画面和声音。</p><Button variant="outline" onClick={()=>abortExport.current?.abort()}>取消导出</Button></>:exported&&<><h5><Check size={17}/>你的剪辑已生成</h5><video src={exported.url} controls preload="metadata" aria-label="已导出视频检查"/><a className="video-download" href={exported.url} download={exported.name}><Download size={16}/>下载 {exported.name}</a></>}</div>}
    <details className="video-lesson" open={step===0}><summary><Info size={16}/>{lesson.title}</summary><p>{lesson.body}</p><strong>试一下</strong><p>{lesson.try}</p></details>
   </div>
  </div>
  <div className="video-status" role="status">{notice}</div><div className="video-footer"><Button disabled={step===0||locked} variant="outline" onClick={()=>changeStep(step-1)}><ArrowLeft size={15}/>上一步</Button><span>0{step+1} / 06 · {videoSteps[step]}</span><Button disabled={locked||step===5} onClick={()=>changeStep(step+1)}>{step===5?'已到导出步骤':videoSteps[step+1]}<ArrowRight size={15}/></Button></div>
  <details className="video-tools-guide"><summary>AI 能帮到哪一步？选工具时怎么分工</summary><div><article><h5>剪映 · 从粗剪到成片</h5><p>素材检索、解说粗剪、文本朗读和多轨道编辑可以减少重复操作，最后仍需检查信息与节奏。</p><a href="https://www.capcut.cn/" target="_blank" rel="noopener noreferrer">官方功能说明 <ExternalLink size={13}/></a></article><article><h5>Premiere · 按转写文本剪辑</h5><p>适合较长口播、访谈与精细后期；先转写，再用文字定位内容并制作字幕。</p><a href="https://helpx.adobe.com/premiere/desktop.html" target="_blank" rel="noopener noreferrer">官方使用指南 <ExternalLink size={13}/></a></article><article><h5>即梦 / Runway · 补生成镜头</h5><p>按分镜生成短片段，再放回主时间线。已有实拍、产品操作、字幕和声音需要一起编排。</p><a href="https://help.runwayml.com/hc/en-us/articles/46974685288467-Creating-with-Gen-4-5" target="_blank" rel="noopener noreferrer">Runway 生成指南 <ExternalLink size={13}/></a></article></div><p>工具能力核查于 2026.09.21。自动成片适合起草，产品事实、术语与最终交付仍需人工确认。</p></details>
  <input ref={fileInput} type="file" accept="video/mp4,video/webm,video/quicktime" hidden onChange={e=>void uploadVideo(e.target.files?.[0])}/><input ref={subtitleInput} type="file" accept=".srt" hidden onChange={e=>void importSubtitles(e.target.files?.[0])}/><input ref={soundInput} type="file" accept="audio/*" hidden onChange={e=>void uploadSound(e.target.files?.[0])}/>
  <Dialog open={!!preview} onOpenChange={v=>{if(!v)setPreview(null)}}><DialogContent className="video-source-dialog"><DialogHeader><DialogTitle>{preview?.name}</DialogTitle><DialogDescription>{preview?.origin} · 原始位置 {timecode(preview?.sourceStart||0)} 起</DialogDescription></DialogHeader>{preview&&<video key={preview.id} src={preview.src} controls preload="metadata" poster={preview.poster} aria-label="源视频预览"/>}<p>源素材预览保留原字幕。关闭后可以设置入出点，只使用需要的片段。</p></DialogContent></Dialog>
 </section>;
}
