"use client";
import {useReviewFeedback,useHumanReview,ReviewChecklist,ReviewWarning} from './human-review';
import {useEffect,useMemo,useRef,useState} from 'react';
import {BookOpen,Files,FileText,Upload,Plus,Search,Sparkles,ArrowRight,ArrowUpRight,Check,CheckCheck,Quote,Network,PenLine,FolderOpen,History,Undo2,Trash2,Download,ChevronRight,AlertTriangle,GitCompareArrows,Link2,Bookmark,LoaderCircle,ListChecks,Send,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Progress} from '@/components/ui/progress';
import {CopyText,downloadText,SmallTable} from './experience-shared';
import {WritingRefineToolbar,WritingVisualEditor,WritingVisualPreview} from './writing-visual-editor';
import {extractWritingVisual} from '@/lib/writing-visuals';
import {writingScenarios,writingReferences,topicLabels,formatNames,audienceNames,allEvidence,findEvidence,sourceSignature,createWritingDocument,rewriteParagraph,blockIssues,buildWritingPrompt,documentMarkdown,importTextSource,type Scenario,type KnowledgeSource,type Evidence,type WritingSettings,type WritingDocument,type WritingBlock,type KnowledgeCard,type Topic} from '@/lib/writing-workbench';

const steps=[['sources','资料与问答',Files],['write','起草与精修',PenLine],['knowledge','知识沉淀',Network],['review','审核与导出',CheckCheck]] as const;
const questions=['目前完成了哪些工作？','哪些风险还没有关闭？','下一步由谁负责？','可以承诺正式上线时间吗？'];
const initialSettings:WritingSettings={format:'weekly',audience:'leader',tone:'formal',length:'standard'};
type Version={id:number;label:string;time:string;doc:WritingDocument};
const clone=<T,>(v:T):T=>JSON.parse(JSON.stringify(v));

function Choice({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:Record<string,string>}){return <label className="wk-field"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{Object.entries(options).map(([v,s])=><SelectItem value={v} key={v}>{s}</SelectItem>)}</SelectContent></Select></label>}

export default function WritingStudio(){
 const [scenario,setScenario]=useState('procurement');
 return <div className="writing-studio"><header className="wk-header"><div className="wk-header-icon"><BookOpen size={28}/></div><div><span className="wk-eyebrow">WRITING & KNOWLEDGE STUDIO</span><h3>让材料成为可交付的文稿</h3><p>读懂来源，逐段精修，把有用的知识留给下一次。</p></div><span className="wk-simulation">交互模拟 · 无需账号</span></header>
 <Tabs value={scenario} onValueChange={setScenario}><TabsList className="wk-scenario-tabs">{writingScenarios.map(s=><TabsTrigger value={s.id} key={s.id}>{s.name}</TabsTrigger>)}</TabsList></Tabs>
 {writingScenarios.map(s=><div key={s.id} style={{display:scenario===s.id?'block':'none'}}><WritingWorkspace scenario={s} active={scenario===s.id}/></div>)}
 </div>
}

function WritingWorkspace({scenario,active}:{scenario:Scenario;active:boolean}){
 const [step,setStep]=useState('sources'),[sources,setSources]=useState<KnowledgeSource[]>(()=>clone(scenario.sources)),[selected,setSelected]=useState(()=>scenario.sources.filter(s=>s.state==='current').map(s=>s.id));
 const [query,setQuery]=useState(questions[1]),[asked,setAsked]=useState(questions[1]),[notice,setNotice]=useState(''),[error,setError]=useState(''),[preview,setPreview]=useState<Evidence|null>(null);
 const [addOpen,setAddOpen]=useState(false),[addTitle,setAddTitle]=useState('补充项目笔记'),[addText,setAddText]=useState(''),[uploading,setUploading]=useState(false),[uploadProgress,setUploadProgress]=useState(0),[importName,setImportName]=useState('');
 const [settings,setSettings]=useState<WritingSettings>(initialSettings),[doc,setDoc]=useState<WritingDocument|null>(null),[blockId,setBlockId]=useState('block-0'),[suggestion,setSuggestion]=useState<{body:string;mode:string;original:string}|null>(null),[working,setWorking]=useState(false);
 const [versions,setVersions]=useState<Version[]>([]),[historyOpen,setHistoryOpen]=useState(false),[cards,setCards]=useState<KnowledgeCard[]>([]),[knowledgeView,setKnowledgeView]=useState('map'),[mapTopic,setMapTopic]=useState<Topic>('risk'),[cardFilter,setCardFilter]=useState(''),[exporting,setExporting]=useState(false);
 const bodyEditor=useRef<HTMLTextAreaElement>(null);
 const [activeTool,setActiveTool]=useState(''),[transformError,setTransformError]=useState('');
 const fileInput=useRef<HTMLInputElement>(null),timer=useRef<ReturnType<typeof setInterval>|null>(null),versionId=useRef(0),generationTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const currentSources=sources.filter(s=>selected.includes(s.id)),context=sourceSignature(sources,selected),evidence=useMemo(()=>allEvidence(sources,selected),[sources,selected]);
 const answer=useMemo(()=>findEvidence(sources,selected,asked),[sources,selected,asked]);
 const current=doc?.blocks.find(b=>b.id===blockId)||doc?.blocks[0];
 const stale=!!doc&&doc.context!==context,issues=doc?.blocks.flatMap(b=>blockIssues(b).map(issue=>({id:b.id,heading:b.heading,issue})))||[],reviewed=doc?.blocks.filter(b=>b.reviewed).length||0;
 const ready=!!doc&&!!doc.title.trim()&&doc.blocks.length>0&&reviewed===doc.blocks.length&&!issues.length&&!stale;
 const review=useReviewFeedback(ready,()=>setStep('review'));
 const cardReview=useReviewFeedback(cards.length>0&&cards.every(c=>c.reviewed),()=>{setStep('knowledge');setKnowledgeView('cards')});
 const actionReview=useHumanReview(JSON.stringify(evidence.filter(e=>e.passage.topic==='action')),['行动原句与来源已逐项对照','责任人、日期及待确认信息已检查'],evidence.some(e=>e.passage.topic==='action'));
 const outdated=currentSources.some(s=>s.state==='old');
 const prompt=buildWritingPrompt(scenario.name,sources,selected,settings);
 useEffect(()=>()=>{if(timer.current)clearInterval(timer.current);if(generationTimer.current)clearTimeout(generationTimer.current)},[]);
 useEffect(()=>{if(!active){setPreview(null);setAddOpen(false);setHistoryOpen(false)}},[active]);
 function focusEditor(){requestAnimationFrame(()=>{const details=bodyEditor.current?.closest('details');if(details)details.open=true;bodyEditor.current?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'})})}
 function move(next:string){setStep(next);setSuggestion(null);setError('')}
 function saveVersion(label:string,value=doc){if(!value)return;const version={id:++versionId.current,label,time:new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}),doc:clone(value)};setVersions(v=>[version,...v].slice(0,12))}
 function editBlock(patch:Partial<WritingBlock>,save=false){if(!current||!doc)return;if(save)saveVersion('修改前 · '+current.heading);setDoc({...doc,blocks:doc.blocks.map(b=>b.id===current.id?{...b,...patch,reviewed:false}:b)});setSuggestion(null)}
 function refine(mode:string,label:string){
  if(!current)return;setActiveTool(mode);setTransformError('');
  if(mode==='table'||mode==='chart'){
   try{
    const refresh=!current.visual||current.visual.sourceText!==current.body;
    const next=refresh?extractWritingVisual(current.body,current.heading,mode):{...current.visual!,view:mode as 'table'|'chart'};
    const customInput=refresh&&next.note.startsWith('实际解析')&&current.body!==current.baseText;
    const inputRef:Evidence={sourceId:'student-table-'+current.id+'-'+Date.now(),sourceName:'学生自带表格',version:'本次输入 · 待人工核验',state:'current',passage:{id:'1',topic:current.topic,text:current.body}};
    editBlock({visual:next,...(customInput?{baseText:current.body,refs:[inputRef]}:{})},refresh);
    if(refresh)setNotice(customInput?'已按你的表格重新整理，以本次粘贴作为练习来源。原版本已保存，内容仍需人工核验。':'已按当前正文重新整理，替换前的内容已存入版本记录。')
   }
   catch(e){setTransformError((e instanceof Error?e.message:'无法识别表格格式。')+' 当前结果未被替换，请修正正文后重试。')}
  }else setSuggestion({body:rewriteParagraph(current.body,mode),mode:label,original:current.body});
 }
 function toggleSource(id:string,checked:boolean){setSelected(v=>checked?[...v,id]:v.filter(x=>x!==id));setSuggestion(null)}
 function cite(ref:Evidence){setPreview(ref)}
 function citationButtons(refs:Evidence[],compact=false){return <div className={`wk-citations ${compact?'compact':''}`}>{refs.map((r,i)=><button key={r.sourceId+'-'+r.passage.id} onClick={()=>cite(r)} title={`${r.sourceName} ${r.version} §${r.passage.id}`}><Quote size={12}/>{compact?`来源 ${i+1}`:`${r.sourceName} · §${r.passage.id}`}</button>)}</div>}
 function addSource(source:KnowledgeSource){setSources(v=>[...v,source]);setSelected(v=>[...v,source.id]);setNotice(`已加入“${source.name}”，可以勾选检索或纳入文稿。`);setError('');setAddOpen(false)}
 async function uploadFile(file?:File){if(!file)return;setError('');if(!/\.(txt|md)$/i.test(file.name)){setError('本地导入支持 UTF-8 的 .txt / .md。PDF 演示请使用“模拟导入示例 PDF”。');return}if(file.size>512*1024){setError('文本文件请控制在 512 KB 以内。');return}try{const text=await file.text();if(!text.trim()){setError('这个文件没有可读取的文字。');return}if(text.includes('\u0000')){setError('请使用 UTF-8 文本文件。');return}addSource(importTextSource(file.name,text,'upload'))}catch{setError('文件读取失败，请尝试粘贴文本。')}}
 function simulateImport(){if(uploading)return;setUploading(true);setUploadProgress(0);setImportName(`${scenario.name}_补充说明.pdf`);let value=0;timer.current=setInterval(()=>{value+=25;setUploadProgress(value);if(value===100){clearInterval(timer.current!);timer.current=null;setUploading(false);const source:KnowledgeSource={id:'sample-'+Date.now(),name:`${scenario.name}_补充说明.pdf`,kind:'PDF',version:'演示素材',date:'2026-09-20',state:'current',origin:'sample',passages:[{id:'1',topic:'risk',text:'补充说明：试点范围和验收口径如有变更，应记录申请原因、影响范围及确认人。现有材料未确认的新日期仍标为待确认。'}]};addSource(source)}},300)}
 function generate(){if(!selected.length){setError('请先至少选择一份资料。');return}if(working)return;setWorking(true);setError('');generationTimer.current=setTimeout(()=>{saveVersion('重新起草前');const next=createWritingDocument(scenario.name,sources,selected,settings);setDoc(next);setBlockId(next.blocks[0].id);setActiveTool('');saveVersion('初稿 · '+formatNames[settings.format],next);setSuggestion(null);setWorking(false);setNotice('初稿已生成。选择段落，体验文字精修、整理成表格或自动适配图表。')},600)}
 function saveAnswer(){if(!answer.length)return;const card:KnowledgeCard={id:'note-'+Date.now(),question:asked,body:answer.map(e=>e.passage.text).join('\n\n'),refs:clone(answer),tag:'问答摘录',owner:'待指定',reviewed:false};setCards(v=>[card,...v]);setNotice('已存入知识卡，来源与版本一并保留。');}
 function buildCards(){const topics=(Object.keys(topicLabels) as Topic[]);const added=topics.map(topic=>{const refs=evidence.filter(e=>e.passage.topic===topic);return {id:'topic-'+topic,question:`${scenario.name}：${topicLabels[topic]}`,body:refs.map(e=>e.passage.text).join('\n\n'),refs:clone(refs),tag:topicLabels[topic],owner:'待指定',reviewed:false}}).filter(c=>c.refs.length);setCards(v=>[...added,...v.filter(c=>!c.id.startsWith('topic-'))]);setKnowledgeView('cards');setNotice(`已按当前来源整理 ${added.length} 张知识卡，原有手动收藏保留。`)}
 async function exportWord(){if(!doc||exporting||!review.request())return;setExporting(true);setError('');try{const {exportWritingDocx}=await import('@/lib/writing-export');const result=await exportWritingDocx(doc,ready);setNotice(`Word 文件已生成（${Math.round(result.bytes/1024)} KB），正文、表格和来源可继续编辑；图表作为图片保留。`)}catch(e){setError(e instanceof Error?e.message:'Word 导出失败，请重试。')}finally{setExporting(false)}}
 const sourceCount=sources.length,shownCards=cards.filter(c=>(c.question+c.body+c.tag+c.owner).toLowerCase().includes(cardFilter.toLowerCase()));
 return <>
  <div className="wk-reference-strip">{writingReferences.map((r,i)=><button key={r.name} className={`wk-reference ref-${i}`} onClick={()=>move(r.step)}><span>{['01','02','03'][i]} / {r.name}</span><strong>{['带来源的资料问答','写得出，也改得好','从文稿到团队知识'][i]}<ArrowUpRight size={15}/></strong></button>)}</div>
  <p className="wk-sample-note">{scenario.tag} · 人名、日期、数字均为教学示例；本地导入仅在当前页面处理。</p>
  <Tabs value={step} onValueChange={move}><TabsList className="wk-step-tabs">{steps.map(([id,label,Icon])=><TabsTrigger key={id} value={id}><Icon size={17}/>{label}{id==='knowledge'&&cards.length>0&&<span>{cards.length}</span>}</TabsTrigger>)}</TabsList></Tabs>
  {notice&&<div className="wk-notice" role="status"><Check size={16}/><span>{notice}</span><button onClick={()=>setNotice('')} aria-label="关闭写作提示"><X size={14}/></button></div>}
  {error&&<div className="wk-error" role="alert"><AlertTriangle size={16}/>{error}</div>}
  {step==='sources'&&<div className="wk-research-grid">
   <aside className="wk-sources"><div className="wk-panel-heading"><h4><Files size={18}/>资料架</h4><span>{selected.length} / {sourceCount} 已选</span></div><div className="wk-source-actions"><Button size="sm" className="wk-add" onClick={()=>setAddOpen(true)}><Plus size={15}/>添加资料</Button><Button size="sm" variant="ghost" onClick={()=>setSelected(sources.filter(s=>s.state==='current').map(s=>s.id))}>只选最新</Button></div>
    <div className="wk-source-list">{sources.map(source=><div key={source.id} className={`wk-source-item ${selected.includes(source.id)?'selected':''}`}><Checkbox aria-label={`使用资料：${source.name}`} checked={selected.includes(source.id)} onCheckedChange={v=>toggleSource(source.id,!!v)}/><button className="wk-source-open" onClick={()=>cite({sourceId:source.id,sourceName:source.name,version:source.version,state:source.state,passage:source.passages[0]})}><span className="wk-file-kind">{source.kind}<small className={source.state==='old'?'old':''}>{source.state==='old'?'旧版':source.version}</small></span><strong>{source.name}</strong><small>{source.passages.length} 条摘录 · {source.date}</small></button>{!scenario.sources.some(s=>s.id===source.id)&&<button className="wk-remove-source" aria-label={`移除资料：${source.name}`} onClick={()=>{setSources(v=>v.filter(s=>s.id!==source.id));setSelected(v=>v.filter(id=>id!==source.id));setNotice('已移除本次导入资料，已有文稿与知识卡保留其引用快照。')}}><Trash2 size={14}/></button>}</div>)}</div>
    <div className="wk-source-footer"><Link2 size={16}/><p>勾选决定检索范围。点击资料名称，可以查看全文摘录。</p></div>
   </aside>
   <section className="wk-chat"><div className="wk-panel-heading"><h4><Sparkles size={19}/>只围绕你的资料回答</h4><span>提取式问答 · 模拟</span></div><div className="wk-question-chips">{questions.map(q=><button key={q} className={asked===q?'active':''} onClick={()=>{setQuery(q);setAsked(q)}}>{q}</button>)}</div>
    <div className="wk-question-bubble"><span>你想了解</span><p>{asked}</p></div><div className="wk-answer"><div className="wk-answer-heading"><span className="wk-ai-avatar"><Sparkles size={17}/></span><strong>根据 {selected.length} 份所选资料</strong><span>{answer.length} 条依据</span></div>
    {outdated&&<div className="wk-warning"><GitCompareArrows size={17}/><p>当前包含旧版。请对照最新记录判断，勿把早期设想当成已批准事项。</p></div>}
    {answer.length?<>{answer.map((ref,i)=><div className="wk-evidence-answer" key={ref.sourceId+ref.passage.id}><span>{String(i+1).padStart(2,'0')}</span><div><p>{ref.passage.text}</p>{citationButtons([ref])}</div></div>)}<div className="wk-answer-actions"><Button variant="outline" size="sm" onClick={saveAnswer}><Bookmark size={15}/>保存为知识卡</Button><Button size="sm" className="wk-primary" onClick={()=>move('write')}>基于资料起草 <ArrowRight size={15}/></Button></div></>:<div className="wk-empty"><Search size={29}/><h4>{selected.length?'所选材料未找到直接依据':'先选择一份资料'}</h4><p>{selected.length?'可以换一个具体问题，或添加相关文本。演示不会补写没有依据的答案。':'左侧勾选来源后，再提问。'}</p></div>}
    </div><form className="wk-question-form" onSubmit={e=>{e.preventDefault();if(query.trim())setAsked(query.trim())}}><Input aria-label="向资料提问" placeholder="例如：接口权限有哪些风险？" value={query} maxLength={200} onChange={e=>setQuery(e.target.value)}/><Button className="wk-primary" type="submit" disabled={!query.trim()||!selected.length}><Send size={16}/>提问</Button></form><p className="wk-footnote">选择来源或问题后，摘录随之更新。点引用回看原句，再判断它是否支持你的结论。</p>
   </section>
  </div>}
  {step==='write'&&<>
   <div className="wk-writing-config"><Choice label="文稿类型" value={settings.format} options={formatNames} onChange={v=>setSettings(s=>({...s,format:v as WritingSettings['format']}))}/><Choice label="写给谁" value={settings.audience} options={audienceNames} onChange={v=>setSettings(s=>({...s,audience:v as WritingSettings['audience']}))}/><Choice label="语气" value={settings.tone} options={{formal:'正式清楚',plain:'直接易懂'}} onChange={v=>setSettings(s=>({...s,tone:v as WritingSettings['tone']}))}/><Choice label="篇幅" value={settings.length} options={{short:'简短 · 每节 1 条依据',standard:'标准 · 每节最多 2 条',long:'详细 · 每节最多 3 条'}} onChange={v=>setSettings(s=>({...s,length:v as WritingSettings['length']}))}/><Button className="wk-primary" disabled={working||!selected.length} onClick={generate}>{working?<LoaderCircle size={16} className="spin"/>:<Sparkles size={16}/>} {doc?'重新起草':'生成初稿'}</Button></div>
   <details className="wk-prompt"><summary>查看并带走这次的写作提示词 <span>{selected.length} 份来源</span></summary><pre>{prompt}</pre><CopyText text={prompt}/></details>
   {stale&&<div className="wk-warning"><AlertTriangle size={18}/><p>来源范围已改变。当前文稿保留原版本，请按最新来源重新起草，再逐段复核。</p></div>}
   {doc&&current?<><div className="wk-editor-heading"><span><FileText size={17}/>{doc.format} · {doc.audience} · {doc.blocks.reduce((n,b)=>n+b.body.length,0)} 字</span><div><Button variant="ghost" size="sm" onClick={()=>{saveVersion('手动保存');setNotice('当前文稿已存为本次会话中的一个版本。')}}><Bookmark size={15}/>保存版本</Button><Button variant="outline" size="sm" onClick={()=>setHistoryOpen(true)}><History size={15}/>版本记录 {versions.length}</Button></div></div>
    <div className="wk-editor-grid"><aside className="wk-outline"><h4>文稿大纲</h4>{doc.blocks.map((b,i)=><button key={b.id} className={current.id===b.id?'active':''} onClick={()=>{setBlockId(b.id);setSuggestion(null);setActiveTool(b.visual?.view||'')}}><span>{String(i+1).padStart(2,'0')}</span><strong>{b.heading}</strong>{b.reviewed?<Check size={15}/>:<ChevronRight size={15}/>}</button>)}<div className="wk-outline-note"><Quote size={18}/><p>每段都有来源。修改只作用于选中段落。</p></div></aside>
    <section className="wk-document"><label className="wk-doc-title"><span>文稿标题</span><Input aria-label="文稿标题" value={doc.title} maxLength={120} onChange={e=>setDoc({...doc,title:e.target.value,blocks:doc.blocks.map(b=>({...b,reviewed:false}))})}/></label><WritingRefineToolbar active={activeTool||current.visual?.view||''} disabled={!current.body.trim()} onAction={refine}/><p className="flex-writing-hint">也可以把本段替换成自己的 CSV、Excel / WPS 粘贴内容或 Markdown 表格，再点“整理成表格”。第一行是表头；带换行的 CSV 单元格用双引号包住。</p>{transformError&&<div className="flex-table-error" role="alert">{transformError}</div>}
     <label className="wk-block-heading"><span>段落标题</span><Input aria-label="当前段落标题" value={current.heading} maxLength={60} onChange={e=>editBlock({heading:e.target.value})}/></label>{current.visual&&<WritingVisualEditor beforeExport={review.request} key={current.id} visual={current.visual} body={current.body} heading={current.heading} onChange={(visual,checkpoint)=>{editBlock({visual},checkpoint);setActiveTool(visual.view)}} onRemove={()=>{editBlock({visual:undefined},true);setActiveTool('')}}/>}{current.visual?<details className="wv-original-text"><summary><FileText size={15}/>整理前原文与补充说明 <span>保留原句，可继续修改</span></summary><Textarea ref={bodyEditor} className="wk-body-editor" aria-label="当前段落正文" value={current.body} maxLength={524288} onChange={e=>{setTransformError('');editBlock({body:e.target.value})}}/></details>:<Textarea ref={bodyEditor} className="wk-body-editor" aria-label="当前段落正文" value={current.body} maxLength={524288} onChange={e=>{setTransformError('');editBlock({body:e.target.value})}}/>}
     <div className="wk-block-meta"><span>{current.body.length} 字 · {current.reviewed?'已人工确认':'待人工复核'}</span><button onClick={()=>editBlock({body:current.baseText},true)}><Undo2 size={14}/>恢复有来源的初稿</button></div>{citationButtons(current.refs)}
     {suggestion&&<div className="wk-rewrite"><div className="wk-panel-heading"><h4><GitCompareArrows size={17}/>{suggestion.mode} · 修改建议</h4><button aria-label="关闭改写建议" onClick={()=>setSuggestion(null)}><X size={16}/></button></div><div className="wk-rewrite-compare"><section><span>修改前 · {suggestion.original.length} 字</span><p>{suggestion.original}</p></section><section><span>建议版本 · {suggestion.body.length} 字</span><p>{suggestion.body}</p></section></div><p className="wk-footnote">检查数字、时间与承诺是否变化，再决定是否采用。演示使用本地规则改写。</p><div className="wk-flex"><Button className="wk-accept" size="sm" onClick={()=>{editBlock({body:suggestion.body},true);focusEditor();setNotice('已采用建议，仅替换当前段落。修改前版本可在“版本记录”恢复。')}}><Check size={15}/>采用建议</Button><Button variant="outline" size="sm" onClick={()=>{setSuggestion(null);focusEditor()}}>保留原文</Button></div></div>}
    </section>
    </div><div className="wk-editor-bottom"><div className="wk-current-check"><strong><ListChecks size={17}/>当前段落检查</strong>{blockIssues(current).length?blockIssues(current).map(t=><p className="wk-issue" key={t}>{t}</p>):<p>示例规则未发现问题，仍需人工核对原文。</p>}<button className="wk-pitfall" onClick={()=>{editBlock({body:current.body+'\n\n项目已全面上线，准确率达到 100%，每年节省 100 万元。'},true);setNotice('已插入一段没有依据的示例表述，请观察检查提示并尝试修复。')}}><AlertTriangle size={14}/>体验一次“事实被改写错”</button></div><Button className="wk-primary" onClick={()=>move('review')}>预览全文并审核 <ArrowRight size={16}/></Button></div>
   </>:<div className="wk-draft-start"><div className="wk-paper-outline"><span>01 / 项目进展</span><i/><i/><span>02 / 风险与行动</span><i/><i/></div><div><h4>先定读者，再让 AI 起草</h4><p>从所选资料提取事实，生成周报、客户邮件、决策简报或复核清单。生成后可逐段编辑、比较和恢复版本。</p><small>重新起草会保存已有文稿的版本；切换案例也会保留本次页面内的练习。</small></div></div>}
  </>}
  {step==='knowledge'&&<><div className="wk-knowledge-toolbar"><div><h4>把一次写作，变成下一次的起点</h4><p>从资料提炼主题，保留出处，再补全负责人与复核状态。</p></div><Button className="wk-add" disabled={!evidence.length} onClick={buildCards}><Sparkles size={16}/>按来源整理知识卡</Button></div><Tabs value={knowledgeView} onValueChange={setKnowledgeView}><TabsList className="wk-view-tabs"><TabsTrigger value="map"><Network size={15}/>知识导图</TabsTrigger><TabsTrigger value="cards"><Bookmark size={15}/>知识卡片 {cards.length}</TabsTrigger><TabsTrigger value="tasks"><ListChecks size={15}/>行动清单</TabsTrigger></TabsList></Tabs>
   {knowledgeView==='map'&&<div className="wk-map-grid"><div className="wk-knowledge-map"><div className="wk-map-root"><BookOpen size={25}/><strong>{scenario.name}</strong><span>{selected.length} 份资料 · {evidence.length} 条摘录</span></div><div className="wk-map-branches">{(Object.entries(topicLabels) as [Topic,string][]).map(([topic,label],i)=><button key={topic} className={`wk-map-node node-${i} ${mapTopic===topic?'active':''}`} onClick={()=>setMapTopic(topic)}><span>{label}</span><b>{evidence.filter(e=>e.passage.topic===topic).length}</b><ChevronRight size={15}/></button>)}</div></div><div className="wk-map-detail"><span className="wk-eyebrow">SELECTED TOPIC</span><h4>{topicLabels[mapTopic]}</h4>{evidence.filter(e=>e.passage.topic===mapTopic).map(e=><div key={e.sourceId+e.passage.id}><p>{e.passage.text}</p>{citationButtons([e],true)}</div>)}{!evidence.some(e=>e.passage.topic===mapTopic)&&<p>所选资料中没有这个主题的摘录。</p>}</div></div>}
   {knowledgeView==='cards'&&<div ref={cardReview.ref} className={cardReview.className}><h4 data-review-trigger tabIndex={-1}>知识卡人工复核</h4><ReviewWarning show={cardReview.blocked}/><div className="wk-search-row"><Search size={17}/><Input aria-label="搜索知识卡" value={cardFilter} onChange={e=>setCardFilter(e.target.value)} placeholder="搜索标题、内容、标签或负责人…"/><span>{shownCards.length} 张卡片</span></div>{cards.length?<div className="wk-knowledge-cards">{shownCards.map(card=><article className="wk-knowledge-card" key={card.id}><div className="wk-card-top"><span>{card.tag}</span><button aria-label={`删除知识卡：${card.question}`} onClick={()=>setCards(v=>v.filter(c=>c.id!==card.id))}><Trash2 size={15}/></button></div><Input aria-label={`知识卡标题：${card.question}`} value={card.question} onChange={e=>setCards(v=>v.map(c=>c.id===card.id?{...c,question:e.target.value,reviewed:false}:c))}/><Textarea aria-label={`知识卡内容：${card.question}`} value={card.body} onChange={e=>setCards(v=>v.map(c=>c.id===card.id?{...c,body:e.target.value,reviewed:false}:c))}/>{citationButtons(card.refs,true)}<label className="wk-card-owner">维护人<Input aria-label={`知识卡维护人：${card.question}`} value={card.owner} onChange={e=>setCards(v=>v.map(c=>c.id===card.id?{...c,owner:e.target.value,reviewed:false}:c))}/></label><label className="wk-check-row" data-review-missing={!card.reviewed}><Checkbox aria-label={`复核知识卡：${card.question}`} checked={card.reviewed} onCheckedChange={v=>setCards(list=>list.map(c=>c.id===card.id?{...c,reviewed:!!v}:c))}/><span>已核对内容与来源</span></label></article>)}</div>:<div className="wk-empty"><Bookmark size={28}/><h4>把第一条有用的答案存下来</h4><p>在“资料与问答”保存答案，或点击上方“按来源整理知识卡”。</p></div>}{cards.length>0&&<div className="wk-flex"><Button variant="outline" onClick={()=>cardReview.request()&&downloadText(scenario.name+'-知识卡.json',JSON.stringify({scenario:scenario.name,notice:'教学演练 · 引用快照随卡片保留',cards},null,2),'application/json;charset=utf-8')}><Download size={16}/>下载知识卡 JSON</Button><Button variant="outline" onClick={()=>cardReview.request()&&downloadText(scenario.name+'-知识库.md',cards.map(c=>`## ${c.question}\n\n${c.body}\n\n维护人：${c.owner}；${c.reviewed?'已复核':'待复核'}\n来源：${c.refs.map(r=>r.sourceName+' '+r.version+' §'+r.passage.id).join('；')}`).join('\n\n'))}>下载知识库 Markdown</Button></div>}</div>}
   {knowledgeView==='tasks'&&<><p className="wk-task-intro">从所选资料中的行动段落提取。多人或多日期的原句先保留在一起，拆分与派发前仍需核对。</p><SmallTable headers={['行动原句','责任人','截止时间','依据']} rows={evidence.filter(e=>e.passage.topic==='action').map(e=>[e.passage.text,e.passage.owner||'待指定',e.passage.due||'待确认',<button className="wk-text-link" key={e.sourceId+e.passage.id} onClick={()=>cite(e)}>查看原文</button>])}/>{!evidence.some(e=>e.passage.topic==='action')&&<p className="wk-empty">当前来源没有可提取的行动项。</p>}<ReviewChecklist review={actionReview}/><Button variant="outline" disabled={!evidence.some(e=>e.passage.topic==='action')} onClick={()=>actionReview.request()&&downloadText(scenario.name+'-行动清单.csv','\uFEFF行动,责任人,截止,来源\n'+evidence.filter(e=>e.passage.topic==='action').map(e=>[e.passage.text,e.passage.owner||'待指定',e.passage.due||'待确认',e.sourceName+' '+e.version].map(s=>'"'+(/^[=+@\-]/.test(s)?"'":'')+s.replaceAll('"','""')+'"').join(',')).join('\n'),'text/csv;charset=utf-8')}><Download size={16}/>下载行动清单 CSV</Button></>}
  </>}
  {step==='review'&&(doc?<div ref={review.ref} className={review.className}><div className="wk-review-status" data-review-trigger tabIndex={-1}><span className={`wk-review-icon ${ready?'ready':''}`}><CheckCheck size={27}/></span><div><h4>{ready?'文稿已完成本次人工复核':'交付前，再核对一次事实'}</h4><p>{reviewed} / {doc.blocks.length} 段已确认 · {issues.length} 项规则提示{stale?' · 来源范围已改变':''}</p></div><Button className="wk-edit" onClick={()=>move('write')}><PenLine size={16}/>返回继续修改</Button></div><ReviewWarning show={review.blocked} text={stale?'来源已变化，请按最新来源重新起草并复核。':issues.length?'请修正交付检查中的问题，并完成每段人工确认。':!doc.title.trim()?'请填写文稿标题，再重新复核。':undefined}/><Progress value={reviewed/doc.blocks.length*100}/>{stale&&<div className="wk-warning"><AlertTriangle size={17}/><p>草稿引用的资料范围已与当前选择不同。请回到起草页，按最新来源重新生成后再确认。</p></div>}
   <div className="wk-review-grid"><article className="wk-full-document"><span className="wk-eyebrow">{doc.format} / {doc.audience}</span><h3>{doc.title}</h3>{doc.blocks.map(b=><section key={b.id}><div className="wk-panel-heading"><h4>{b.heading}</h4><button className="wk-text-link" onClick={()=>{setBlockId(b.id);setActiveTool(b.visual?.view||'');move('write')}}>修改本段 <PenLine size={13}/></button></div><>{b.visual?<div className="wv-reviewed-output"><h5>{b.visual.title}</h5><WritingVisualPreview visual={b.visual}/><p className="wv-source-note">{b.visual.note}</p><details className="wv-original-text"><summary>整理前原文与统计口径</summary><p>{b.body}</p></details></div>:<p className="wv-review-body">{b.body}</p>}</>{citationButtons(b.refs,true)}<label className="wk-check-row" data-review-missing={!b.reviewed}><Checkbox checked={b.reviewed} aria-label={`确认段落：${b.heading}`} onCheckedChange={v=>setDoc({...doc,blocks:doc.blocks.map(x=>x.id===b.id?{...x,reviewed:!!v}:x)})}/><span>已回查来源并确认本段</span></label></section>)}</article><aside className="wk-delivery"><h4><ListChecks size={20}/>交付检查</h4>{issues.length?issues.map((item,i)=><button className="wk-issue-card" key={i} onClick={()=>{setBlockId(item.id);move('write')}}><AlertTriangle size={15}/><span><strong>{item.heading}</strong>{item.issue}</span><ChevronRight size={14}/></button>):<div className="wk-check-pass"><Check size={20}/><p>示例规则未发现问题。请继续人工核对来源、口径与承诺。</p></div>}<div className="wk-export-writing"><h4>带走最终文稿</h4><p>{ready?'导出已审文稿':'逐段确认并解决检查提示后，才能导出。'}</p><Button className="wk-word-export" disabled={exporting||!doc.title.trim()} onClick={()=>void exportWord()}>{exporting?<LoaderCircle size={16} className="spin"/>:<Download size={16}/>}导出 Word .docx</Button><Button variant="outline" onClick={()=>review.request()&&downloadText(doc.title+'.md',documentMarkdown(doc,ready))}><Download size={16}/>导出 Markdown</Button><CopyText text={documentMarkdown(doc,ready)} label="复制完整文稿" beforeCopy={review.request}/><small>Word 包含当前正文、可编辑表格、图表图片及来源；Markdown 保留表格数据。</small></div></aside></div>
  </div>:<div className="wk-empty"><FileText size={30}/><h4>先生成一份文稿</h4><p>完成资料选择后，进入起草与精修。</p><Button className="wk-primary" onClick={()=>move('write')}>去起草 <ArrowRight size={16}/></Button></div>)}
  <div className="wk-learning-tip"><BookOpen size={20}/><div><strong>{writingReferences.find(r=>r.step===step)?.name||'从练习到工作'}</strong><p>{writingReferences.find(r=>r.step===step)?.guide||'先在预览中逐段检查，人工确认后再导出。发现问题时可以随时回到编辑页。'}</p></div>{writingReferences.find(r=>r.step===step)&&<a href={writingReferences.find(r=>r.step===step)!.url} target="_blank" rel="noopener noreferrer">官方说明 <ArrowUpRight size={14}/></a>}</div>
  <Sheet open={!!preview} onOpenChange={v=>{if(!v)setPreview(null)}}><SheetContent className="wk-source-sheet"><SheetHeader><span className="wk-eyebrow">SOURCE / 引用核对</span><SheetTitle>{preview?.sourceName}</SheetTitle><SheetDescription>{preview?.version} · §{preview?.passage.id} · {preview?.state==='old'?'旧版，仅供比较':'引用来源'}。演示材料不代表实际业务记录。</SheetDescription></SheetHeader>{preview&&<div className="wk-source-sheet-body"><div className="wk-source-quote"><Quote size={20}/><strong>本次引用原句</strong><p>{preview.passage.text}</p></div><h4>同一份资料中的其他摘录</h4>{(sources.find(s=>s.id===preview.sourceId)?.passages||[preview.passage]).map(p=><div className={p.id===preview.passage.id?'selected':''} key={p.id}><span>§{p.id} · {topicLabels[p.topic]}</span><p>{p.text}</p></div>)}<p className="wk-footnote">引用保留导出或收藏时的原句；来源后来被移除时，仍可回看这份快照。</p></div>}</SheetContent></Sheet>
  <Dialog open={addOpen} onOpenChange={setAddOpen}><DialogContent className="wk-import-dialog"><DialogHeader><DialogTitle>把资料放进工作台</DialogTitle><DialogDescription>上传或粘贴的文本会加入当前页面的资料架。离开或刷新页面后，本次练习不保留。</DialogDescription></DialogHeader><div className="wk-import-options"><section><h4><Upload size={19}/>本地文本</h4><p>真实读取 .txt / .md，UTF-8 编码，最大 512 KB。</p><input hidden type="file" ref={fileInput} accept=".txt,.md,text/plain,text/markdown" onChange={e=>{void uploadFile(e.target.files?.[0]);e.target.value=''}}/><Button variant="outline" onClick={()=>fileInput.current?.click()}>选择文本文件</Button></section><section><h4><FileText size={19}/>PDF 导入流程</h4><p>用预置补充说明模拟上传和解析，不读取真实 PDF。</p><Button variant="outline" disabled={uploading} onClick={simulateImport}>{uploading?<LoaderCircle size={15} className="spin"/>:<PlayIcon/>}模拟导入示例 PDF</Button></section></div>{uploading&&<div className="wk-import-progress"><span>{importName} · {uploadProgress<50?'上传中（模拟）':'提取段落（模拟）'}</span><Progress value={uploadProgress}/></div>}<div className="wk-paste"><h4>或粘贴一段工作笔记</h4><Input aria-label="资料名称" value={addTitle} maxLength={100} onChange={e=>setAddTitle(e.target.value)}/><Textarea aria-label="粘贴资料正文" value={addText} maxLength={12000} rows={5} onChange={e=>setAddText(e.target.value)} placeholder="每行一条事实，例如：接口权限待审批。下一步由李工确认申请进度。"/><Button className="wk-add" disabled={!addTitle.trim()||!addText.trim()} onClick={()=>{addSource(importTextSource(addTitle.trim(),addText,'paste'));setAddText('')}}><Plus size={16}/>加入资料架</Button></div>{error&&<p role="alert" className="wk-error">{error}</p>}</DialogContent></Dialog>
  <Sheet open={historyOpen} onOpenChange={setHistoryOpen}><SheetContent className="wk-history-sheet"><SheetHeader><SheetTitle>版本记录</SheetTitle><SheetDescription>保存当前页面内最近 12 个版本。恢复时会先保留当前文稿，恢复后需重新复核。</SheetDescription></SheetHeader><div className="wk-history-list">{versions.map(v=><article key={v.id}><span>V{v.id} · {v.time}</span><h4>{v.label}</h4><p>{v.doc.title}</p><small>{v.doc.blocks.length} 个段落 · {v.doc.blocks.reduce((sum,b)=>sum+b.body.length,0)} 字</small><Button variant="outline" onClick={()=>{saveVersion('恢复前的文稿');setDoc({...clone(v.doc),blocks:clone(v.doc.blocks).map(b=>({...b,reviewed:false}))});setBlockId(v.doc.blocks[0].id);setActiveTool(v.doc.blocks[0].visual?.view||'');setHistoryOpen(false);setSuggestion(null);focusEditor();setNotice(`已恢复 V${v.id}，恢复前的文稿也已保存。`)}}><Undo2 size={15}/>恢复这个版本</Button></article>)}</div></SheetContent></Sheet>
 </>
}
function PlayIcon(){return <ChevronRight size={15}/>}
