export type GlossaryTerm={id:string;name:string;en:string;category:string;definition:string;example:string;pitfall:string;href:string;action:string;related:string[]};
export const glossaryTerms:GlossaryTerm[]=[
 {id:'llm',name:'大语言模型',en:'Large Language Model · LLM',category:'入门概念',definition:'从上下文中预测并生成文字的模型，擅长语言理解、改写和归纳。输出是否正确仍需要依据与验证。',example:'让模型把采购差异字段整理成审核说明；金额差额由程序计算，再交给模型解释。',pitfall:'说得流畅，不等于事实准确或计算正确。',href:'/models',action:'观察模型回答',related:['token','hallucination','evaluation']},
 {id:'token',name:'词元',en:'Token',category:'入门概念',definition:'模型处理文本时使用的片段单位，不与中文汉字或英文单词一一对应。输入和输出都会占用词元。',example:'把整份采购手册塞进对话会占用上下文；先检索相关条款能减少无关信息。',pitfall:'同样的字数，换一种语言或分词器，词元数量可能不同。',href:'/models',action:'体验上下文预算',related:['context','rag','llm']},
 {id:'prompt',name:'提示词工程',en:'Prompt Engineering',category:'入门概念',definition:'把任务目标、输入、约束、示例和输出格式写清楚，让模型更容易完成指定任务。',example:'“依据以下三单字段，列出差异、引用字段、给出下一步；缺失字段标为待确认，输出表格。”',pitfall:'只写“你是专家”，不能代替任务信息与验收标准。',href:'/learn?lesson=prompt',action:'改写一条提示词',related:['context','evaluation','hallucination']},
 {id:'context',name:'上下文工程',en:'Context Engineering',category:'知识与数据',definition:'决定一次任务中给模型哪些规则、知识、工具说明和历史信息，并管理其版本、权限与有效期。',example:'采购助手只取当前公司的有效制度、相关单据和允许调用的接口，避免混入其他公司的规则。',pitfall:'上下文越多未必越好；过期和无关信息也会干扰结果。',href:'/learn?lesson=context',action:'练习选择上下文',related:['prompt','rag','tool']},
 {id:'rag',name:'检索增强生成',en:'Retrieval-Augmented Generation · RAG',category:'知识与数据',definition:'先从知识源检索与问题相关的内容，再让模型基于这些内容组织回答，并保留可核查的来源。',example:'问“这笔采购为什么要审批”，先查金额阈值条款，再引用条款与单据金额解释。',pitfall:'能检索到文档不等于已经理解业务，也不能保证回答没有错误。',href:'/learn?lesson=rag',action:'体验有依据的回答',related:['context','embedding','hallucination']},
 {id:'embedding',name:'向量表示',en:'Embedding',category:'知识与数据',definition:'把文本等内容转换为一组数字，使相近语义更容易被检索系统匹配。实际检索还可结合关键词与业务筛选。',example:'问题写“货没到齐”，检索仍可能找到“部分收货”的制度段落，再按公司和版本过滤。',pitfall:'语义相近不代表事实一致；金额、日期、公司等仍需要精确核对。',href:'/learn?lesson=rag',action:'理解检索链路',related:['rag','context','ontology']},
 {id:'ontology',name:'业务本体',en:'Ontology',category:'知识与数据',definition:'用明确的业务对象、属性和关系表达领域含义。在本站的供应链示例中，再把规则与受控动作连接到这些对象。',example:'“供应商 → 供应物料 → 库存 → 生产订单”，延迟到货会影响哪些订单，可沿关系追溯并提出加急建议。',pitfall:'画出关系图只是起点，还需要统一定义、真实数据映射与动作权限。',href:'/ontology',action:'走进 3D 业务关系',related:['rag','agent','human']},
 {id:'agent',name:'智能体',en:'AI Agent',category:'构建与交付',definition:'围绕目标，利用模型选择步骤或调用工具来完成任务的系统；应明确可行动的范围和停止条件。',example:'发现采购异常后，检索制度、组织差异说明，并把建议交给审核人。',pitfall:'能对话不等于能可靠执行；自主行动越多，越需要边界和评测。',href:'/agents',action:'观看并搭建智能体',related:['workflow','tool','human']},
 {id:'workflow',name:'工作流',en:'Workflow',category:'构建与交付',definition:'把任务拆成有输入、输出与条件分支的步骤，用明确顺序和规则协同完成。工作流可以包含模型节点。',example:'读取单据 → 检索制度 → 解释差异 → 校验阈值 → 必要时人工确认 → 输出结果。',pitfall:'固定规则能完成的计算不必交给模型；不是每个步骤都需要自主决策。',href:'/agents#agent-builder',action:'调整工作流节点',related:['agent','human','evaluation']},
 {id:'tool',name:'工具调用',en:'Tool / Function Calling',category:'构建与交付',definition:'模型提出结构化的工具调用请求，应用校验后执行接口或函数，再把结果提供给模型。',example:'“查询采购单”只读接口允许调用；“写回 ERP”要求校验权限、参数和审批状态。',pitfall:'模型提出调用，不等于工具已经执行成功，更不意味着已获得权限。',href:'/learn?lesson=dify',action:'认识节点与工具',related:['agent','context','mcp']},
 {id:'mcp',name:'模型上下文协议',en:'Model Context Protocol · MCP',category:'构建与交付',definition:'连接 AI 应用与外部工具、资源的一种协议，用统一的交互方式减少重复集成工作。',example:'把开发文档查询和工具能力提供给编程助手，再由应用控制允许访问的内容。',pitfall:'采用协议不会自动解决业务权限、数据质量或工具本身的可靠性。',href:'/coding',action:'进入 AI 编程实训',related:['tool','context','agent']},
 {id:'human',name:'人在回路',en:'Human-in-the-loop',category:'构建与交付',definition:'在关键判断或行动节点引入人的审核、修正或确认，使自动化流程有清晰的责任边界。',example:'三单不符或金额达到阈值时先暂停，把差异和依据一起交给审核人。',pitfall:'一个“确认”按钮不够，审核人必须看得到证据、修改入口和退回路径。',href:'/agents#agent-builder',action:'试一次人工审批',related:['workflow','evaluation','ontology']},
 {id:'hallucination',name:'幻觉',en:'Hallucination',category:'验证与运营',definition:'模型生成听起来合理、却缺乏依据或与事实不符的内容。需要通过来源、约束和评测降低其影响。',example:'材料仅写“计划试点”，汇报却写“已全面上线”，就是应被人工审校识别的问题。',pitfall:'降低温度不能保证回答真实；引用也必须回查是否支持结论。',href:'/tools?category=writing',action:'核对写作中的依据',related:['rag','evaluation','prompt']},
 {id:'evaluation',name:'评测',en:'Evaluation · Evals',category:'验证与运营',definition:'用代表性任务、明确标准和可复查结果，比较系统是否达到业务要求，并检查修改后的回归。',example:'准备正常、差异、缺失字段和大额样例，分别检查分支、依据和人工确认是否符合预期。',pitfall:'只看几次顺利演示，不能代替覆盖失败情况的验收。',href:'/learn?lesson=evaluation',action:'设计一个验收样例',related:['human','observability','llm']},
 {id:'observability',name:'可观测性',en:'Observability / Trace',category:'验证与运营',definition:'记录一次任务的输入、检索、工具调用、输出及耗时等信息，帮助定位问题与改进流程。',example:'查看运行轨迹，区分“没找到正确制度”“字段缺失”和“分支规则不合适”。',pitfall:'日志数量多不等于可追溯，还需要关联同一次运行并处理敏感字段。',href:'/agents#agent-builder',action:'查看节点运行轨迹',related:['evaluation','workflow','context']},
];
