import * as THREE from 'three';
/* CPU projection fallback for environments where a WebGL context is unavailable.
   Uses the same scene, camera, meshes, hit testing and calculations as the GPU view. */
export class SpatialSoftwareRenderer {
 domElement=document.createElement('canvas');outputColorSpace=THREE.SRGBColorSpace;private ctx=this.domElement.getContext('2d')!;private width=800;private height=500;private ratio=1;private background='#102533';
 setPixelRatio(n:number){this.ratio=Math.min(n,1.3)} setClearColor(c:string){this.background=c} setSize(w:number,h:number){this.width=w;this.height=h;this.domElement.width=w*this.ratio;this.domElement.height=h*this.ratio;this.domElement.style.width=`${w}px`;this.domElement.style.height=`${h}px`} dispose(){} forceContextLoss(){}
 render(scene:THREE.Scene,camera:THREE.PerspectiveCamera){const ctx=this.ctx,w=this.width,h=this.height;ctx.setTransform(this.ratio,0,0,this.ratio,0,0);ctx.fillStyle=this.background;ctx.fillRect(0,0,w,h);scene.updateMatrixWorld();camera.updateMatrixWorld();const vp=new THREE.Matrix4().multiplyMatrices(camera.projectionMatrix,camera.matrixWorldInverse);const project=(p:THREE.Vector3)=>{const q=p.clone().applyMatrix4(vp);return {x:(q.x+1)*w/2,y:(1-q.y)*h/2,z:q.z}};const faces:{points:{x:number,y:number,z:number}[],depth:number,color:string,alpha:number}[]=[];const lines:{a:{x:number,y:number,z:number},b:{x:number,y:number,z:number},color:string,alpha:number}[]=[];const sprites:THREE.Sprite[]=[];const keyLight=new THREE.Vector3(.5,1,.8).normalize();
scene.traverse(o=>{if(!o.visible||o.parent&&!o.parent.visible)return;if(o instanceof THREE.Sprite){sprites.push(o);return}if(o instanceof THREE.Mesh){const geom=o.geometry as THREE.BufferGeometry;const attr=geom.getAttribute('position');if(!attr)return;const index=geom.getIndex();const material=(Array.isArray(o.material)?o.material[0]:o.material) as THREE.MeshStandardMaterial;const base=material.color||new THREE.Color('#9db5c4');const normal=new THREE.Matrix3().getNormalMatrix(o.matrixWorld);const count=index?index.count:attr.count;for(let i=0;i<count;i+=3){const ids=[0,1,2].map(k=>index?index.getX(i+k):i+k);const local=ids.map(id=>new THREE.Vector3().fromBufferAttribute(attr,id));const world=local.map(p=>p.clone().applyMatrix4(o.matrixWorld));const faceNormal=new THREE.Vector3().subVectors(world[1],world[0]).cross(new THREE.Vector3().subVectors(world[2],world[0]));const center=world[0].clone().add(world[1]).add(world[2]).multiplyScalar(1/3);if(material.side!==THREE.DoubleSide&&faceNormal.dot(camera.position.clone().sub(center))<=0)continue;const points=world.map(project);if(points.some(p=>p.z<-1||p.z>1)||points.every(p=>p.x<0)||points.every(p=>p.x>w)||points.every(p=>p.y<0)||points.every(p=>p.y>h))continue;const cross=new THREE.Vector3().subVectors(local[1],local[0]).cross(new THREE.Vector3().subVectors(local[2],local[0])).applyMatrix3(normal).normalize();const shade=.56+.4*Math.max(0,cross.dot(keyLight));const color=base.clone().multiplyScalar(shade);if(material.emissive)color.add(material.emissive.clone().multiplyScalar(material.emissiveIntensity*.55));faces.push({points,depth:world.every(p=>p.y<=.1)?2:points.reduce((a,b)=>a+b.z,0)/3,color:color.getStyle(),alpha:material.opacity??1})}}
else if(o instanceof THREE.Line){const attr=o.geometry.getAttribute('position');const material=(Array.isArray(o.material)?o.material[0]:o.material) as THREE.LineBasicMaterial;if(!attr)return;const segments=o instanceof THREE.LineSegments;for(let i=0;i<attr.count-1;i+=segments?2:1){const a=project(new THREE.Vector3().fromBufferAttribute(attr,i).applyMatrix4(o.matrixWorld));const b=project(new THREE.Vector3().fromBufferAttribute(attr,i+1).applyMatrix4(o.matrixWorld));if(a.z>=-1&&a.z<=1&&b.z>=-1&&b.z<=1)lines.push({a,b,color:o.type==='GridHelper'?'#31505e':material.color.getStyle(),alpha:o.type==='GridHelper'?.48:(material.opacity??1)})}}});
// Mix floor lines and faces by camera depth so routes stay above the floor
// while walls and shelves still occlude segments behind them.
const drawables=[...faces.map(f=>({depth:f.depth,draw:()=>{ctx.globalAlpha=f.alpha;ctx.fillStyle=f.color;ctx.beginPath();f.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fill()}})),...lines.map(l=>({depth:(l.a.z+l.b.z)/2,draw:()=>{ctx.globalAlpha=l.alpha;ctx.strokeStyle=l.color;ctx.lineWidth=1.2;ctx.beginPath();ctx.moveTo(l.a.x,l.a.y);ctx.lineTo(l.b.x,l.b.y);ctx.stroke()}}))];drawables.sort((a,b)=>b.depth-a.depth);drawables.forEach(d=>d.draw());ctx.globalAlpha=1;
for(const sp of sprites){const mat=sp.material as THREE.SpriteMaterial;const canvas=mat.map?.image;if(!(canvas instanceof HTMLCanvasElement))continue;const pos=new THREE.Vector3();sp.getWorldPosition(pos);const p=project(pos);if(p.z<-1||p.z>1)continue;const cameraPoint=pos.clone().applyMatrix4(camera.matrixWorldInverse);const pixels=h/(2*Math.tan(THREE.MathUtils.degToRad(camera.fov/2))*Math.max(.1,-cameraPoint.z));const sw=sp.scale.x*pixels,sh=sp.scale.y*pixels;ctx.drawImage(canvas,p.x-sw/2,p.y-sh/2,sw,sh)}
 }
}
